Repository mapbox/mapbox-maps-ios, pull requests merged in 2021-11, with the labels that each got.

#802 Simplify DebugApp to make it easier to customize
  Apps/DebugApp/DebugApp.xcodeproj/project.pbxproj
  Apps/DebugApp/DebugApp/AppDelegate.swift
  Apps/DebugApp/DebugApp/Base.lproj/Main.storyboard
  Apps/DebugApp/DebugApp/Info.plist
  Apps/DebugApp/DebugApp/MainViewController.swift
Labels: skip changelog

#801 Use Xcode 13.0 for Examples device farm tests
  .circleci/config.yml
Labels: bug :beetle:, testing :100:

#803 [examples] Update the description for the FlyToExample and CameraAnimatorsExamples
  Apps/Examples/Examples/Models/Examples.swift
Labels: docs :scroll:

#807 Update to MapboxCoreMaps v10.1.0 & Common v20.1.0
  .swiftpm/xcode/xcshareddata/xcschemes/MapboxMaps.xcscheme
  Apps/Apps.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Apps/DebugApp/DebugApp.xcodeproj/project.pbxproj
  Apps/DebugApp/DebugApp.xcodeproj/xcshareddata/xcschemes/DebugApp.xcscheme
  Apps/Examples/Examples.xcodeproj/project.pbxproj
  Apps/Examples/Examples.xcodeproj/xcshareddata/xcschemes/Examples.xcscheme
  Apps/StressTest/StressTest.xcodeproj/xcshareddata/xcschemes/StressTest.xcscheme
  CHANGELOG.md
  MapboxMaps.podspec
  Package.resolved
  Package.swift
  scripts/release/packager/versions.json
Labels: skip changelog

#808 Update CI for long-lived release branches
  .circleci/config.yml
Labels: skip changelog

#814 Fix build warning in Examples app
  Apps/Examples/Examples/All Examples/FlyToExample.swift
Labels: skip changelog

#805 [testing] Address flaky TileStore tests
  .circleci/config.yml
  Tests/MapboxMapsTests/Foundation/Integration Tests/DeallocationObserver.swift
  Tests/MapboxMapsTests/Foundation/Integration Tests/OfflineManagerIntegrationTests.swift
  Tests/MapboxMapsTests/Foundation/MapViewTests.swift
Labels: testing :100:

#789 Address a jump when using camera animations after a gesture
  CHANGELOG.md
  Sources/MapboxMaps/Foundation/Camera/BasicCameraAnimator.swift
  Sources/MapboxMaps/Foundation/Extensions/FatalError.swift
  Tests/MapboxMapsTests/Foundation/Camera/BasicCameraAnimatorTests.swift
  Tests/MapboxMapsTests/Foundation/Camera/MockPropertyAnimator.swift
  Tests/MapboxMapsTests/Helpers/XCTestCase+FatalError.swift
Labels: bug :beetle:

#837 Implement iterative pan gesture handling
  CHANGELOG.md
  Sources/MapboxMaps/Foundation/Camera/CameraAnimationsManager.swift
  Sources/MapboxMaps/Foundation/Camera/GestureDecelerationCameraAnimator.swift
  Sources/MapboxMaps/Gestures/GestureHandlers/PanGestureHandler.swift
  Sources/MapboxMaps/Gestures/GestureHandlers/PinchGestureHandler.swift
  Tests/MapboxMapsTests/Foundation/Camera/Mocks/MockCameraAnimationsManager.swift
  Tests/MapboxMapsTests/Gestures/GestureHandlers/Mocks/MockGestureHandlerDelegate.swift
  Tests/MapboxMapsTests/Gestures/GestureHandlers/PanGestureHandlerTests.swift
  Tests/MapboxMapsTests/Gestures/GestureHandlers/PinchGestureHandlerTests.swift
Labels: bug :beetle:

#840 Refactor Annotations so that the gesture recognizer is managed by the AnnotationOrchestrator
  Sources/MapboxMaps/Annotations/AnnotationOrchestrator.swift
  Sources/MapboxMaps/Annotations/Generated/CircleAnnotationManager.swift
  Sources/MapboxMaps/Annotations/Generated/PointAnnotationManager.swift
  Sources/MapboxMaps/Annotations/Generated/PolygonAnnotationManager.swift
  Sources/MapboxMaps/Annotations/Generated/PolylineAnnotationManager.swift
Labels: feature :green_apple:

#839 Delete unused DebugApp tests
  Apps/DebugApp/DebugApp.xcodeproj/project.pbxproj
  Apps/DebugApp/DebugApp.xcodeproj/xcshareddata/xcschemes/DebugApp.xcscheme
  Apps/DebugApp/DebugAppTests/ApplicationTestCase.swift
  Apps/DebugApp/DebugAppTests/DebugAppTests.swift
  Apps/DebugApp/DebugAppTests/Info.plist
  Apps/DebugApp/DebugAppUITests/DebugAppUITests.swift
  Apps/DebugApp/DebugAppUITests/Info.plist
Labels: skip changelog

#843 Miscellaneous cleanup
  Package.swift
  Sources/MapboxMaps/Camera/AnimationCompletion.swift
  Sources/MapboxMaps/Camera/AnimationOwner.swift
  Sources/MapboxMaps/Camera/BasicCameraAnimator.swift
  Sources/MapboxMaps/Camera/CameraAnimationsManager.swift
  Sources/MapboxMaps/Camera/CameraAnimator.swift
  Sources/MapboxMaps/Camera/CameraBounds.swift
  Sources/MapboxMaps/Camera/CameraBoundsOptions.swift
  Sources/MapboxMaps/Camera/CameraOptions.swift
  Sources/MapboxMaps/Camera/CameraState.swift
  Sources/MapboxMaps/Camera/CameraTransition.swift
  Sources/MapboxMaps/Camera/CameraView.swift
  Sources/MapboxMaps/Camera/FlyToCameraAnimator.swift
  Sources/MapboxMaps/Camera/FlyToInterpolator.swift
  Sources/MapboxMaps/Camera/GestureDecelerationCameraAnimator.swift
  Sources/MapboxMaps/Foundation/Events/Event.swift
  Sources/MapboxMaps/Foundation/Events/EventsManager.swift
  Sources/MapboxMaps/Foundation/Events/EventsStringTokens.swift
  Sources/MapboxMaps/Foundation/PendingAnimationCompletion.swift
  Sources/MapboxMaps/Ornaments/InfoButtonOrnament.swift
  Sources/MapboxMaps/Ornaments/LogoView.swift
  Sources/MapboxMaps/Snapshot/AttributionMeasure.swift
  Sources/MapboxMaps/Snapshot/AttributionView.swift
  Tests/MapboxMapsTests/Camera/BasicCameraAnimatorIntegrationTests.swift
  Tests/MapboxMapsTests/Camera/BasicCameraAnimatorTests.swift
  Tests/MapboxMapsTests/Camera/CameraAnimationsManagerTests.swift
  Tests/MapboxMapsTests/Camera/CameraOptionsTests.swift
  Tests/MapboxMapsTests/Camera/CameraStateTests.swift
  Tests/MapboxMapsTests/Camera/CameraTransitionTests.swift
  Tests/MapboxMapsTests/Camera/CameraViewTests.swift
  Tests/MapboxMapsTests/Camera/FlyToCameraAnimatorTests.swift
  Tests/MapboxMapsTests/Camera/FlyToTests.swift
  Tests/MapboxMapsTests/Camera/GestureDecelerationCameraAnimatorTests.swift
  Tests/MapboxMapsTests/Camera/Mocks/MockCameraAnimationsManager.swift
  Tests/MapboxMapsTests/Camera/Mocks/MockCameraAnimatorDelegate.swift
  Tests/MapboxMapsTests/Camera/Mocks/MockCameraView.swift
  Tests/MapboxMapsTests/Camera/Mocks/MockPropertyAnimator.swift
  Tests/MapboxMapsTests/Foundation/Extensions/Turf/GeometryTests.swift
  Tests/MapboxMapsTests/Foundation/GeoJSON/FeatureCollectionTests.swift
  Tests/MapboxMapsTests/Foundation/GeoJSON/Fixture.swift
  Tests/MapboxMapsTests/Foundation/GeoJSON/Fixtures/featurecollection-no-properties.geojson
  Tests/MapboxMapsTests/Foundation/GeoJSON/Fixtures/featurecollection.geojson
  Tests/MapboxMapsTests/Foundation/GeoJSON/Fixtures/geometry-collection.geojson
  Tests/MapboxMapsTests/Foundation/GeoJSON/Fixtures/multiline.geojson
  Tests/MapboxMapsTests/Foundation/GeoJSON/Fixtures/multipoint.geojson
  Tests/MapboxMapsTests/Foundation/GeoJSON/Fixtures/multipolygon.geojson
  Tests/MapboxMapsTests/Foundation/GeoJSON/Fixtures/point.geojson
  Tests/MapboxMapsTests/Foundation/GeoJSON/Fixtures/simple-line.geojson
  Tests/MapboxMapsTests/Foundation/GeoJSON/GeometryCollectionTests.swift
  Tests/MapboxMapsTests/Foundation/GeoJSON/LineStringTests.swift
  Tests/MapboxMapsTests/Foundation/GeoJSON/MultiLineStringTests.swift
  Tests/MapboxMapsTests/Foundation/GeoJSON/MultiPointTests.swift
  Tests/MapboxMapsTests/Foundation/GeoJSON/MultiPolygonTests.swift
  Tests/MapboxMapsTests/Foundation/GeoJSON/PointTests.swift
  Tests/MapboxMapsTests/Foundation/GeoJSON/PolygonTests.swift
  Tests/MapboxMapsTests/Foundation/Mocks/MockMapboxMap.swift
  Tests/MapboxMapsTests/MigrationGuide/Fixtures/polygon.geojson
  Tests/MapboxMapsTests/MigrationGuide/MigrationGuideIntegrationTests.swift
  Tests/MapboxMapsTests/Ornaments/InfoButton/InfoButtonOrnamentTests.swift
Labels: skip changelog

#507 Add a distance expression example
  Apps/Examples/Examples.xcodeproj/project.pbxproj
  Apps/Examples/Examples/All Examples/DistanceExpressionExample.swift
  Apps/Examples/Examples/Models/Examples.swift
Labels: docs :scroll:

#776 View Annotations
  Apps/Examples/Examples.xcodeproj/project.pbxproj
  Apps/Examples/Examples/All Examples/ViewAnnotationExample.swift
  Apps/Examples/Examples/Assets.xcassets/blue_marker_view.imageset/Contents.json
  Apps/Examples/Examples/Assets.xcassets/blue_marker_view.imageset/blue_marker_view.png
  Apps/Examples/Examples/Models/Examples.swift
  Sources/MapboxMaps/Annotations/AnnotationView.swift
  Sources/MapboxMaps/Annotations/DelegatingViewAnnotationPositionsListener.swift
  Sources/MapboxMaps/Annotations/ViewAnnotation.swift
  Sources/MapboxMaps/Annotations/ViewAnnotationOptions.swift
  Sources/MapboxMaps/Foundation/MapView.swift
  Sources/MapboxMaps/Foundation/MapboxMap.swift
  Sources/MapboxMaps/Foundation/SubviewInteractionOnlyView.swift
  Tests/MapboxMapsTests/Foundation/Mocks/MockMapboxMap.swift
  Tests/MapboxMapsTests/Foundation/ViewAnnotationTests.swift
Labels: feature :green_apple:

#847 Fix StyleColor tests for iOS 12 and lower
  Tests/MapboxMapsTests/Style/StyleColorTests.swift
Labels: skip changelog, testing :100:

#856 Fix to only localize the primary localization and not the fall-throug…
  Sources/MapboxMaps/Style/Style+Localization.swift
  Tests/MapboxMapsTests/Style/Style+LocalizationTests.swift
Labels: bug :beetle:

#846 View Annotations follow-up
  Apps/Examples/Examples.xcodeproj/project.pbxproj
  Apps/Examples/Examples/All Examples/ViewAnnotationBasicExample.swift
  Apps/Examples/Examples/All Examples/ViewAnnotationMarkerExample.swift
  Apps/Examples/Examples/Models/Examples.swift
  Sources/MapboxMaps/Annotations/AnnotationView.swift
  Sources/MapboxMaps/Annotations/ViewAnnotation.swift
  Sources/MapboxMaps/Annotations/ViewAnnotationOptions.swift
  Sources/MapboxMaps/Foundation/SubviewInteractionOnlyView.swift
  Tests/MapboxMapsTests/Foundation/Annotations/DelegatingViewAnnotationPositionsUpdateListenerTests.swift
  Tests/MapboxMapsTests/Foundation/Annotations/Mocks/MockDelegatingViewAnnotationPositionsUpdateListenerDelegate.swift
  Tests/MapboxMapsTests/Foundation/Annotations/ViewAnnotationManagerTests.swift
  Tests/MapboxMapsTests/Foundation/Annotations/ViewAnnotationOptionsTests.swift
  Tests/MapboxMapsTests/Foundation/SubviewInteractionOnlyViewTests.swift
  Tests/MapboxMapsTests/Foundation/ViewAnnotationTests.swift
  Tests/MapboxMapsTests/Helpers/Extensions/ViewAnnotationPositionDescriptor.swift
Labels: feature :green_apple:

#861 Reduce geometry wrapping using GeometryConvertible
  Apps/Examples/Examples/All Examples/DistanceExpressionExample.swift
  Apps/Examples/Examples/All Examples/ViewAnnotationBasicExample.swift
  Apps/Examples/Examples/All Examples/ViewAnnotationMarkerExample.swift
  CHANGELOG.md
  Sources/MapboxMaps/Annotations/DelegatingViewAnnotationPositionsUpdateListener.swift
  Sources/MapboxMaps/Annotations/ViewAnnotationManager.swift
  Sources/MapboxMaps/Annotations/ViewAnnotationOptions.swift
  Sources/MapboxMaps/Foundation/Extensions/Turf/Geometry.swift
  Tests/MapboxMapsTests/Annotations/DelegatingViewAnnotationPositionsUpdateListenerTests.swift
  Tests/MapboxMapsTests/Annotations/Mocks/MockDelegatingViewAnnotationPositionsUpdateListenerDelegate.swift
  Tests/MapboxMapsTests/Annotations/ViewAnnotationManagerTests.swift
  Tests/MapboxMapsTests/Annotations/ViewAnnotationOptionsTests.swift
  Tests/MapboxMapsTests/Foundation/Extensions/Turf/GeometryTests.swift
  Tests/MapboxMapsTests/Offline/TileRegionLoadOptions+MapboxMapsTests.swift
  Tests/MapboxMapsTests/Style/Fixtures/Enums+Fixtures.swift
Labels: feature :green_apple:

#862 Delay adding puck images until adding layer
  CHANGELOG.md
  Sources/MapboxMaps/Location/Puck/Puck2D.swift
  Tests/MapboxMapsTests/Location/Puck/Puck2DTests.swift
Labels: bug :beetle:

#873 Add missing StyleColor support for exponentials
  CHANGELOG.md
  Sources/MapboxMaps/Style/Types/StyleColor.swift
Labels: bug :beetle:

#865 Fix attribution dialog initialization
  Sources/MapboxMaps/Foundation/Events/EventsManager.swift
Labels: bug :beetle:
