Repository mapbox/mapbox-maps-ios, pull requests merged in 2021-06, with the labels that each got.

#410 Bumped tilestore tests timeout to 60
  Sources/MapboxMaps/Offline/TileStore+MapboxMaps.swift
  Tests/MapboxMapsTests/MapView/Integration Tests/OfflineManagerIntegrationTests.swift
Labels: testing :100:

#419 [testing] Test compass tapped
  Mapbox/MapboxMaps.xcodeproj/project.pbxproj
  Tests/MapboxMapsTests/Ornaments/Compass/CompassDirectionFormatterTests.swift
  Tests/MapboxMapsTests/Ornaments/Compass/CompassMapViewIntegrationTests.swift
  Tests/MapboxMapsTests/Ornaments/Compass/MapboxCompassOrnamentViewTests.swift
Labels: testing :100:

#421 Update TileStore tests
  Sources/MapboxMaps/Offline/TileStore+MapboxMaps.swift
  Tests/MapboxMapsTests/Helpers/XCTestCase+MapboxAccessToken.swift
  Tests/MapboxMapsTests/MapView/Integration Tests/CacheManager/CacheManagerIntegrationTests.swift
  Tests/MapboxMapsTests/MapView/Integration Tests/IntegrationTestCase.swift
  Tests/MapboxMapsTests/MapView/Integration Tests/MapViewIntegrationTestCase.swift
  Tests/MapboxMapsTests/MapView/Integration Tests/OfflineManagerIntegrationTests.swift
  Tests/MapboxMapsTests/MigrationGuide/MigrationGuideIntegrationTests.swift
Labels: testing :100:

#424 Update CI to use MBX-CI
  .circleci/config.yml
  Makefile
Labels: skip changelog

#420 Fix Car Play Stretching
  Sources/MapboxMaps/Foundation/MapView.swift
Labels: bug :beetle:

#427 Remove MapCameraOptions and RenderOptions
  Apps/Examples/Examples/All Examples/RestrictCoordinateBoundsExample.swift
  CHANGELOG.md
  Mapbox/MapboxMaps.xcodeproj/project.pbxproj
  Sources/MapboxMaps/Foundation/Camera/CameraAnimationsManager.swift
  Sources/MapboxMaps/Foundation/Camera/CameraBounds.swift
  Sources/MapboxMaps/Foundation/Camera/CameraBoundsOptions.swift
  Sources/MapboxMaps/Foundation/Camera/FlyToCameraAnimator.swift
  Sources/MapboxMaps/Foundation/Camera/FlyToInterpolator.swift
  Sources/MapboxMaps/Foundation/Camera/MapCameraOptions.swift
  Sources/MapboxMaps/Foundation/MapView.swift
  Sources/MapboxMaps/Foundation/MapboxMap.swift
  Sources/MapboxMaps/Gestures/CameraAnimationsManagerProtocol.swift
  Sources/MapboxMaps/Gestures/GestureManager+GestureHandlerDelegate.swift
  Sources/MapboxMaps/Gestures/GestureManager.swift
  Sources/MapboxMaps/Location/Pucks/Puck3D.swift
  Sources/MapboxMaps/MapView/Configuration/RenderOptions.swift
  Tests/MapboxMapsTests/Foundation/Camera/FlyToAnimatorTests.swift
  Tests/MapboxMapsTests/Foundation/Camera/FlyToTests.swift
  Tests/MapboxMapsTests/Gestures/MockCameraManager.swift
  Tests/MapboxMapsTests/Helpers/XCTestCase+MapboxAccessToken.swift
  Tests/MapboxMapsTests/MapView/Integration Tests/Map/MapViewIntegrationTests.swift
  Tests/MapboxMapsTests/MapView/Integration Tests/MapViewIntegrationTestCase.swift
  Tests/MapboxMapsTests/MigrationGuide/MigrationGuideIntegrationTests.swift
Labels: breaking change :warning:

#426 Remove `CameraAnimationsManager.setCamera` in favor of `CameraManagerProtocol.setCamera`
  Apps/Examples/Examples/All Examples/BuildingExtrusionsExample.swift
  Apps/Examples/Examples/All Examples/CameraAnimatorsExample.swift
  Apps/Examples/Examples/All Examples/Custom2DPuckExample.swift
  Apps/Examples/Examples/All Examples/Custom3DPuckExample.swift
  Apps/Examples/Examples/All Examples/FitCameraToGeometryExample.swift
  Apps/Examples/Examples/All Examples/LineGradientExample.swift
  Apps/Examples/Examples/All Examples/RestrictCoordinateBoundsExample.swift
  Apps/Examples/Examples/All Examples/SwiftUIExample.swift
  CHANGELOG.md
  Sources/MapboxMaps/Foundation/Camera/CameraAnimationsManager.swift
  Sources/MapboxMaps/Foundation/CameraManagerProtocol.swift
  Sources/MapboxMaps/Foundation/MapView.swift
  Sources/MapboxMaps/Foundation/MapboxMap.swift
  Sources/MapboxMaps/Gestures/CameraAnimationsManagerProtocol.swift
  Sources/MapboxMaps/Gestures/GestureManager+GestureHandlerDelegate.swift
  Tests/MapboxMapsTests/Gestures/GestureManagerTests.swift
  Tests/MapboxMapsTests/Gestures/MockCameraManager.swift
  Tests/MapboxMapsTests/MapView/Integration Tests/FeatureQueryingTest.swift
  Tests/MapboxMapsTests/Ornaments/Compass/CompassMapViewIntegrationTests.swift
Labels: breaking change :warning:

#436 [Ornaments, testing] Update `isOnRight` when scale bar's position is updated
  Sources/MapboxMaps/Ornaments/OrnamentsManager.swift
  Tests/MapboxMapsTests/Ornaments/OrnamentManagerTests.swift
Labels: bug :beetle:, testing :100:

#438 Remove 'beta' references from codebase
  .circleci/config.yml
  package-lock.json
  package.json
  scripts/release/get_latest_tag.sh
Labels: skip changelog

#428 support CLLocationDirection/course for bearing
  Apps/Examples/Examples/All Examples/Custom2DPuckExample.swift
  CHANGELOG.md
  Sources/MapboxMaps/Location/LocationConsumer.swift
  Sources/MapboxMaps/Location/LocationManager.swift
  Sources/MapboxMaps/Location/LocationOptions.swift
  Sources/MapboxMaps/Location/LocationSupportableMapView.swift
  Sources/MapboxMaps/Location/Pucks/LocationPuckManager.swift
  Sources/MapboxMaps/Location/Pucks/Puck.swift
  Sources/MapboxMaps/Location/Pucks/Puck2D.swift
  Sources/MapboxMaps/Location/Pucks/Puck3D.swift
  Tests/MapboxMapsTests/Location/LocationManagerTests.swift
  Tests/MapboxMapsTests/Location/LocationSupportableMapViewMock.swift
  Tests/MapboxMapsTests/Location/Pucks/Puck2DIntegrationTests.swift
  Tests/MapboxMapsTests/MapView/Integration Tests/LocationManagerIntegrationTests.swift
Labels: bug :beetle:

#440 Update core to 10.0.0-rc.1
  Apps/Apps.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Apps/Examples/Examples/All Examples/OfflineManagerExample.swift
  CHANGELOG.md
  Mapbox/MapboxMaps.xcodeproj/project.pbxproj
  Mapbox/MapboxMaps.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Package.resolved
  Package.swift
  Sources/MapboxMaps/Foundation/Extensions/Core/CacheManager.swift
  Sources/MapboxMaps/Foundation/Extensions/Core/ResourceOptions.swift
  Sources/MapboxMaps/Offline/TileStore+MapboxMaps.swift
  Tests/MapboxMapsTests/Helpers/XCTestCase+MapboxAccessToken.swift
  Tests/MapboxMapsTests/MapView/Integration Tests/CacheManager/CacheManagerIntegrationTests.swift
  Tests/MapboxMapsTests/MapView/Integration Tests/DeallocationObserver.swift
  Tests/MapboxMapsTests/MapView/Integration Tests/IntegrationTestCase.swift
  Tests/MapboxMapsTests/MapView/Integration Tests/Map/DidIdleFailureIntegrationTest.swift
  Tests/MapboxMapsTests/MapView/Integration Tests/Map/MapViewIntegrationTests.swift
  Tests/MapboxMapsTests/MapView/Integration Tests/Map/MapboxMapIntegrationTests.swift
  Tests/MapboxMapsTests/MapView/Integration Tests/MapViewIntegrationTestCase.swift
  Tests/MapboxMapsTests/MapView/Integration Tests/OfflineManagerIntegrationTests.swift
  Tests/MapboxMapsTests/MigrationGuide/MigrationGuideIntegrationTests.swift
  Tests/MapboxMapsTests/MigrationGuide/OfflineGuideIntegrationTests.swift
  Tests/MapboxMapsTests/Offline/TileStore+Tests.swift
  Tests/MapboxMapsTests/Snapshot/MapboxMapsSnapshotTests.swift
  Tests/MapboxMapsTests/Style/Generated/IntegrationTests/Layers/LineLayerIntegrationTests.swift
Labels: breaking change :warning:

#430 Convert MapSnapshotOptions to struct
  CHANGELOG.md
  Sources/MapboxMaps/Foundation/Extensions/Core/MapSnapshotOptions.swift
  Sources/MapboxMaps/Snapshot/Snapshotter.swift
Labels: breaking change :warning:

#441 Embed MME framework in test host
  Mapbox/MapboxMaps.xcodeproj/project.pbxproj
  Tests/MapboxMapsTests/Gestures/GestureManagerTests.swift
Labels: skip changelog

#442 Update version files
  .circleci/config.yml
  MapboxMaps.podspec
  Sources/MapboxMaps/Foundation/MapView.swift
  scripts/release/packager/versions.json
Labels: skip changelog

#443 Ensure that animations / completion blocks are honored even when scheduleRepaint() isn't called
  Sources/MapboxMaps/Foundation/MapView.swift
Labels: bug :beetle:

#444 Push loaded event on map view init.
  Apps/DebugApp/DebugApp/Info.plist
  Sources/MapboxMaps/Foundation/Events/EventsManager.swift
  Sources/MapboxMaps/Foundation/MapView.swift
Labels: skip changelog

#445 Cleanup OfflineManager tests
  Tests/MapboxMapsTests/MapView/Integration Tests/OfflineManagerIntegrationTests.swift
Labels: skip changelog, testing :100:

#448 Update PaintCode asset metadata
  PCVD/DefaultAnnotationIcon.pcvd
  PCVD/compass.pcvd
Labels: skip changelog

#449 Internalize extensions of Core and Common types
  Apps/Examples/Examples/All Examples/AnimateGeoJSONLineExample.swift
  Apps/Examples/Examples/All Examples/AnimateLayerExample.swift
  CHANGELOG.md
  Sources/MapboxMaps/Foundation/Camera/CameraState.swift
  Sources/MapboxMaps/Foundation/Cancelable.swift
  Sources/MapboxMaps/Foundation/Extensions/Core/LayerPosition.swift
  Sources/MapboxMaps/Foundation/Extensions/Core/MBXGeometry.swift
  Sources/MapboxMaps/Foundation/Extensions/Turf/Feature.swift
  Sources/MapboxMaps/Foundation/Extensions/Turf/Geometry.swift
  Sources/MapboxMaps/Offline/OfflineManager+MapboxMaps.swift
  Sources/MapboxMaps/Offline/TileStore+MapboxMaps.swift
  Tests/MapboxMapsTests/Foundation/Camera/CameraStateTests.swift
  Tests/MapboxMapsTests/Foundation/Extensions/Core/LayerPositionTests.swift
Labels: breaking change :warning:, skip changelog

#452 Tweak setting of CameraBounds
  Tests/MapboxMapsTests/MigrationGuide/MigrationGuideIntegrationTests.swift
Labels: docs :scroll:, skip changelog, testing :100:

#456 Remove circle ci badge
  README.md
Labels: skip changelog

#458 Add podspec automation to update version script
  scripts/release/update-version.sh
Labels: skip changelog

#462 [examples] Rename GeoJSONSourceExample to MultipleGeometriesExample
  Apps/Examples/Examples.xcodeproj/project.pbxproj
  Apps/Examples/Examples/All Examples/MultipleGeometriesExample.swift
  Apps/Examples/Examples/All Examples/Sample Data/GeoJSONSourceExample.geojson
  Apps/Examples/Examples/Models/Examples.swift
Labels: docs :scroll:

#461 [examples] Add a point annotations example
  Apps/Examples/Examples.xcodeproj/project.pbxproj
  Apps/Examples/Examples/All Examples/MultiplePointAnnotationsExample.swift
  Apps/Examples/Examples/Assets.xcassets/custom_marker.imageset/Contents.json
  Apps/Examples/Examples/Assets.xcassets/custom_marker.imageset/custom-marker.png
  Apps/Examples/Examples/Models/Examples.swift
Labels: docs :scroll:

#465 [testing] Test the number of visible bars within the scale bar
  Sources/MapboxMaps/Ornaments/ScaleBar/MapboxScaleBarOrnamentView.swift
  Tests/MapboxMapsTests/Ornaments/ScaleBar/MapboxScaleBarOrnamentViewTests.swift
Labels: testing :100:

#467 Fix SwiftUI Example
  Apps/Examples/Examples/All Examples/SwiftUIExample.swift
Labels: bug :beetle:, skip changelog

#455 [testing] Test the distance for the bars in the scale bar
  Mapbox/MapboxMaps.xcodeproj/project.pbxproj
  Sources/MapboxMaps/Ornaments/ScaleBar/MapboxScaleBarOrnamentView.swift
  Tests/MapboxMapsTests/Ornaments/ScaleBar/MapboxScaleBarOrnamentViewTests.swift
Labels: testing :100:

#468 Add scroll edge appearance for iOS 15
  Apps/Examples/Examples/AppDelegate.swift
Labels: skip changelog

#473 [location] Update the location indicator to use layer persistence
  Sources/MapboxMaps/Location/LocationStyleDelegate.swift
  Sources/MapboxMaps/Location/LocationSupportableMapView.swift
  Sources/MapboxMaps/Location/Pucks/Puck2D.swift
  Sources/MapboxMaps/Location/Pucks/Puck3D.swift
  Sources/MapboxMaps/MapView/MapView+Supportable.swift
  Tests/MapboxMapsTests/Location/LocationSupportableMapViewMock.swift
  Tests/MapboxMapsTests/Location/MockLocationStyleDelegate.swift
  Tests/MapboxMapsTests/Location/Pucks/Puck2DIntegrationTests.swift
  Tests/MapboxMapsTests/Style/Generated/IntegrationTests/Layers/LocationIndicatorLayerIntegrationTests.swift
Labels: feature :green_apple:

#481 Pin to MapboxCommon v14.2.0
  .depsvalidator.yml
  Apps/Apps.xcworkspace/xcshareddata/swiftpm/Package.resolved
  CHANGELOG.md
  Mapbox/MapboxMaps.xcodeproj/project.pbxproj
  Mapbox/MapboxMaps.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  MapboxMaps.podspec
  Package.resolved
  Package.swift
  scripts/release/packager/versions.json
Labels: breaking change :warning:

#480 Feature/localization
  Apps/Examples/Examples.xcodeproj/project.pbxproj
  Apps/Examples/Examples/All Examples/LocalizationExample.swift
  Apps/Examples/Examples/Models/Examples.swift
  CHANGELOG.md
  Mapbox/MapboxMaps.xcodeproj/project.pbxproj
  Sources/MapboxMaps/Foundation/MapView.swift
  Sources/MapboxMaps/Style/Style+Localization.swift
  Sources/MapboxMaps/Style/SupportedLanguage.swift
Labels: feature :green_apple:

#483 Re-enable unit-test coverage
  .circleci/config.yml
Labels: operations, skip changelog

#479 [testing] Test the attribution button's behavior when tapped
  Mapbox/MapboxMaps.xcodeproj/project.pbxproj
  Sources/MapboxMaps/Ornaments/MapboxInfoButtonOrnament.swift
  Tests/MapboxMapsTests/Ornaments/InfoButton/MapboxInfoButtonOrnamentViewTests.swift
Labels: testing :100:

#485 Release v10.0.0-rc.2
  Apps/Apps.xcworkspace/xcshareddata/swiftpm/Package.resolved
  CHANGELOG.md
  Mapbox/MapboxMaps.xcodeproj/project.pbxproj
  Mapbox/MapboxMaps.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Mapbox/MapboxTestHost/Info.plist
  MapboxMaps.podspec
  Package.resolved
  Package.swift
  Sources/MapboxMaps/MapView/Info.plist
  Tests/MapboxMapsTests/MapView/Info.plist
  scripts/release/packager/versions.json
Labels: skip changelog

#495 Remove build settings that clash with M1 Macs
  Mapbox/Configurations/base.xcconfig
Labels: skip changelog

#498 [examples] Animate an image
  Apps/Examples/Examples.xcodeproj/project.pbxproj
  Apps/Examples/Examples/All Examples/AnimateImageLayerExample.swift
  Apps/Examples/Examples/All Examples/Sample Data/Radar/radar0.gif
  Apps/Examples/Examples/All Examples/Sample Data/Radar/radar1.gif
  Apps/Examples/Examples/All Examples/Sample Data/Radar/radar2.gif
  Apps/Examples/Examples/All Examples/Sample Data/Radar/radar3.gif
  Apps/Examples/Examples/All Examples/Sample Data/Radar/radar4.gif
  Apps/Examples/Examples/Models/Examples.swift
Labels: docs :scroll:

#497 Mark overridden designated initializers as unavailable
  CHANGELOG.md
  Sources/MapboxMaps/Foundation/MapView.swift
  Sources/MapboxMaps/MapView/Configuration/MapInitOptions.swift
Labels: skip changelog

#496 Update core to 10.0.0-rc.3, common to 14.2.0
  Apps/Apps.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Mapbox/MapboxMaps.xcodeproj/project.pbxproj
  Mapbox/MapboxMaps.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  MapboxMaps.podspec
  Package.resolved
  Package.swift
  Sources/MapboxMaps/Foundation/MapboxMap.swift
  Sources/MapboxMaps/Offline/OfflineCallbacks.swift
  Sources/MapboxMaps/Snapshot/Snapshotter.swift
  Tests/MapboxMapsTests/MapView/Integration Tests/Map/DidIdleFailureIntegrationTest.swift
  Tests/MapboxMapsTests/MapView/Integration Tests/Map/MapViewIntegrationTests.swift
  Tests/MapboxMapsTests/MapView/Integration Tests/Map/MapboxMapIntegrationTests.swift
  Tests/MapboxMapsTests/MapView/Integration Tests/MapViewIntegrationTestCase.swift
  Tests/MapboxMapsTests/MapView/Integration Tests/OfflineManagerIntegrationTests.swift
  Tests/MapboxMapsTests/Snapshot/MapboxMapsSnapshotTests.swift
  scripts/release/packager/versions.json
Labels: dependencies

#502 [examples] Update tile size for 3D terrain examples
  Apps/Examples/Examples/All Examples/SkyLayerExample.swift
  Apps/Examples/Examples/All Examples/TerrainExample.swift
Labels: bug :beetle:

#505 Prevent complete animators from causing drawing
  .swiftpm/xcode/xcshareddata/xcschemes/MapboxMaps.xcscheme
  Apps/DebugApp/DebugApp.xcodeproj/project.pbxproj
  Apps/DebugApp/DebugApp.xcodeproj/xcshareddata/xcschemes/DebugApp.xcscheme
  Apps/Examples/Examples.xcodeproj/project.pbxproj
  Apps/Examples/Examples.xcodeproj/xcshareddata/xcschemes/Examples.xcscheme
  Apps/StressTest/StressTest.xcodeproj/xcshareddata/xcschemes/StressTest.xcscheme
  CHANGELOG.md
  Mapbox/MapboxMaps.xcodeproj/project.pbxproj
  Package.swift
  Sources/MapboxMaps/Foundation/Camera/CameraAnimationsManager+CameraAnimatorDelegate.swift
  Sources/MapboxMaps/Foundation/Camera/CameraAnimationsManager.swift
  Sources/MapboxMaps/Foundation/DisplayLinkProtocol.swift
  Sources/MapboxMaps/Foundation/ForwardingDispalyLinkTarget.swift
  Sources/MapboxMaps/Foundation/MapInitOptions.swift
  Sources/MapboxMaps/Foundation/MapView+Supportable.swift
  Sources/MapboxMaps/Foundation/MapView.swift
  Sources/MapboxMaps/Foundation/MapViewDependencyProvider.swift
  Sources/MapboxMaps/Foundation/PendingAnimationCompletion.swift
  Sources/MapboxMaps/Info.plist
  Sources/MapboxMaps/MapboxMaps.h
  Tests/MapboxMapsTests/Foundation/Integration Tests/DeallocationObserver.swift
  Tests/MapboxMapsTests/Foundation/Integration Tests/ExampleIntegrationTest.swift
  Tests/MapboxMapsTests/Foundation/Integration Tests/FeatureQueryingTest.swift
  Tests/MapboxMapsTests/Foundation/Integration Tests/HTTP/HTTPIntegrationTests.swift
  Tests/MapboxMapsTests/Foundation/Integration Tests/IntegrationTestCase.swift
  Tests/MapboxMapsTests/Foundation/Integration Tests/LocationManagerIntegrationTests.swift
  Tests/MapboxMapsTests/Foundation/Integration Tests/Map/DidIdleFailureIntegrationTest.swift
  Tests/MapboxMapsTests/Foundation/Integration Tests/Map/MapInitOptionsIntegrationTests.swift
  Tests/MapboxMapsTests/Foundation/Integration Tests/Map/MapViewIntegrationTests.swift
  Tests/MapboxMapsTests/Foundation/Integration Tests/Map/MapboxMapIntegrationTests.swift
  Tests/MapboxMapsTests/Foundation/Integration Tests/Map/ObservableIntegrationTests.swift
  Tests/MapboxMapsTests/Foundation/Integration Tests/MapViewIntegrationTestCase.swift
  Tests/MapboxMapsTests/Foundation/Integration Tests/OfflineManagerIntegrationTests.swift
  Tests/MapboxMapsTests/Foundation/Integration Tests/Style/StyleLoadIntegrationTests.swift
  Tests/MapboxMapsTests/Foundation/MapInitOptionsTests.swift
  Tests/MapboxMapsTests/Foundation/MapViewTests.swift
  Tests/MapboxMapsTests/Foundation/Mocks/LocationProviderMock.swift
  Tests/MapboxMapsTests/Foundation/Mocks/MockCameraAnimator.swift
  Tests/MapboxMapsTests/Foundation/Mocks/MockDelegatingMapClientDelegate.swift
  Tests/MapboxMapsTests/Foundation/Mocks/MockDelegatingObserverDelegate.swift
  Tests/MapboxMapsTests/Foundation/Mocks/MockDisplayLink.swift
  Tests/MapboxMapsTests/Foundation/Mocks/MockMapClient.swift
  Tests/MapboxMapsTests/Foundation/Mocks/MockMapViewDependencyProvider.swift
  Tests/MapboxMapsTests/Foundation/Mocks/MockMetalView.swift
  Tests/MapboxMapsTests/Info.plist
  Tests/MapboxMapsTests/MapView/Unit Tests/MapViewTests.swift
  scripts/release/packager/project.yml
Labels: bug :beetle:, performance :zap:
