Repository mapbox/mapbox-maps-ios, pull requests merged in 2021-08, with the labels that each got.

#517 Enable panning while zooming
  CHANGELOG.md
  Sources/MapboxMaps/Gestures/GestureHandlerDelegate.swift
  Sources/MapboxMaps/Gestures/GestureHandlers/PinchGestureHandler.swift
  Sources/MapboxMaps/Gestures/GestureManager.swift
  Tests/MapboxMapsTests/Gestures/GestureManagerTests.swift
  Tests/MapboxMapsTests/Gestures/GestureSupportableViewMock.swift
  Tests/MapboxMapsTests/Gestures/PinchGestureHandlerTests.swift
Labels: bug :beetle:

#553 Add snappshotter options for logo and attribution
  CHANGELOG.md
  Package.swift
  Sources/MapboxMaps/Foundation/Extensions/Core/MapSnapshotOptions.swift
  Sources/MapboxMaps/Snapshot/Snapshotter.swift
  Tests/MapboxMapsTests/Resources/testDoNotShowsAttribution().png
  Tests/MapboxMapsTests/Resources/testDoNotShowsLogo().png
  Tests/MapboxMapsTests/Resources/testShowsAttribution().png
  Tests/MapboxMapsTests/Resources/testShowsLogo().png
  Tests/MapboxMapsTests/Snapshot/MapboxMapsSnapshotTests.swift
Labels: feature :green_apple:

#573 Fix image comparison for recent snapshot attribution tests
  Package.swift
  Tests/MapboxMapsTests/Helpers/XCTestCase+MapboxAccessToken.swift
  Tests/MapboxMapsTests/Snapshot/Snapshot.xcassets/Contents.json
  Tests/MapboxMapsTests/Snapshot/Snapshot.xcassets/testSnapshotAttribution-100.imageset/Contents.json
  Tests/MapboxMapsTests/Snapshot/Snapshot.xcassets/testSnapshotAttribution-100.imageset/testSnapshotAttribution-100_1_232D6148-268F-4BCC-B87A-A78007EF9688.png
  Tests/MapboxMapsTests/Snapshot/Snapshot.xcassets/testSnapshotAttribution-150.imageset/Contents.json
  Tests/MapboxMapsTests/Snapshot/Snapshot.xcassets/testSnapshotAttribution-150.imageset/testSnapshotAttribution-150_1_E8430267-DD22-4AA8-9727-BD94B2F99DF6.png
  Tests/MapboxMapsTests/Snapshot/Snapshot.xcassets/testSnapshotAttribution-200.imageset/Contents.json
  Tests/MapboxMapsTests/Snapshot/Snapshot.xcassets/testSnapshotAttribution-200.imageset/testSnapshotAttribution-200_1_11E08884-1F2F-4150-A662-909115267E7D.png
  Tests/MapboxMapsTests/Snapshot/Snapshot.xcassets/testSnapshotAttribution-250.imageset/Contents.json
  Tests/MapboxMapsTests/Snapshot/Snapshot.xcassets/testSnapshotAttribution-250.imageset/testSnapshotAttribution-250_1_8468A877-E93E-4EEE-BD0B-5D858260AF05.png
  Tests/MapboxMapsTests/Snapshot/Snapshot.xcassets/testSnapshotAttribution-300.imageset/Contents.json
  Tests/MapboxMapsTests/Snapshot/Snapshot.xcassets/testSnapshotAttribution-300.imageset/testSnapshotAttribution-300_1_BD9DE994-7E29-433D-895A-6A0A92C85D9A.png
  Tests/MapboxMapsTests/Snapshot/Snapshot.xcassets/testSnapshotAttribution-50.imageset/Contents.json
  Tests/MapboxMapsTests/Snapshot/Snapshot.xcassets/testSnapshotAttribution-50.imageset/testSnapshotAttribution-50_1_CD1F7DDD-002E-42F6-A6EF-6BFE78A46E06.png
  Tests/MapboxMapsTests/Snapshot/Snapshot.xcassets/testSnapshotLogoVisibility.imageset/Contents.json
  Tests/MapboxMapsTests/Snapshot/Snapshot.xcassets/testSnapshotLogoVisibility.imageset/testSnapshotLogoVisibility.png
  Tests/MapboxMapsTests/Snapshot/testDoNotShowsAttribution().png
  Tests/MapboxMapsTests/Snapshot/testDoNotShowsLogo().png
  Tests/MapboxMapsTests/Snapshot/testShowsAttribution().png
  Tests/MapboxMapsTests/Snapshot/testShowsLogo().png
  Tests/MapboxMapsTests/Snapshot/testSnapshotAttribution-100.png
  Tests/MapboxMapsTests/Snapshot/testSnapshotAttribution-150.png
  Tests/MapboxMapsTests/Snapshot/testSnapshotAttribution-200.png
  Tests/MapboxMapsTests/Snapshot/testSnapshotAttribution-250.png
  Tests/MapboxMapsTests/Snapshot/testSnapshotAttribution-300.png
  Tests/MapboxMapsTests/Snapshot/testSnapshotAttribution-50.png
  Tests/MapboxMapsTests/Snapshot/testSnapshotLogoVisibility.png
Labels: skip changelog

#575 Fix Map Events Docs
  Sources/MapboxMaps/Foundation/Extensions/Core/MapEvents.swift
Labels: docs :scroll:, skip changelog

#578 updating turf dependency
  Apps/Apps.xcworkspace/xcshareddata/swiftpm/Package.resolved
  MapboxMaps.podspec
  Package.resolved
  Package.swift
  scripts/release/packager/versions.json
Labels: skip changelog

#579 Test using CocoaImageHashing for image comparisons
  Apps/Apps.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Package.swift
  Tests/MapboxMapsTests/Helpers/XCTestCase+MapboxMaps.swift
  Tests/MapboxMapsTests/Snapshot/MapboxMapsSnapshotTests.swift
  project.yml
Labels: skip changelog, testing :100:

#582 Update for file rename
  project.yml
Labels: skip changelog

#590 Update *Annotations to get/set
  CHANGELOG.md
  Sources/MapboxMaps/Annotations/Generated/CircleAnnotation.swift
  Sources/MapboxMaps/Annotations/Generated/PointAnnotation.swift
  Sources/MapboxMaps/Annotations/Generated/PolygonAnnotation.swift
  Sources/MapboxMaps/Annotations/Generated/PolylineAnnotation.swift
Labels: bug :beetle:

#594 update core to rc7.1
  Apps/Apps.xcworkspace/xcshareddata/swiftpm/Package.resolved
  MapboxMaps.podspec
  Package.resolved
  Package.swift
  scripts/release/packager/versions.json
Labels: skip changelog

#601 Fix annotation property getters
  Sources/MapboxMaps/Annotations/Generated/CircleAnnotation.swift
  Sources/MapboxMaps/Annotations/Generated/PointAnnotation.swift
  Sources/MapboxMaps/Annotations/Generated/PolygonAnnotation.swift
  Sources/MapboxMaps/Annotations/Generated/PolylineAnnotation.swift
  Tests/MapboxMapsTests/Annotations/Generated/CircleAnnotationIntegrationTests.swift
  Tests/MapboxMapsTests/Annotations/Generated/CircleAnnotationTests.swift
  Tests/MapboxMapsTests/Annotations/Generated/PointAnnotationIntegrationTests.swift
  Tests/MapboxMapsTests/Annotations/Generated/PointAnnotationTests.swift
  Tests/MapboxMapsTests/Annotations/Generated/PolygonAnnotationIntegrationTests.swift
  Tests/MapboxMapsTests/Annotations/Generated/PolygonAnnotationTests.swift
  Tests/MapboxMapsTests/Annotations/Generated/PolylineAnnotationIntegrationTests.swift
  Tests/MapboxMapsTests/Annotations/Generated/PolylineAnnotationTests.swift
  Tests/MapboxMapsTests/Helpers/Encodable+MapboxMaps.swift
Labels: bug :beetle:, skip changelog

#602 Fixing padding issues
  Sources/MapboxMaps/Foundation/Camera/CameraView.swift
  Tests/MapboxMapsTests/Foundation/Camera/CameraViewTests.swift
Labels: bug :beetle:

#603 Delete GeoJSONManager
  CHANGELOG.md
  Sources/MapboxMaps/Foundation/GeoJSONManager.swift
  Sources/MapboxMaps/Style/Style.swift
  Tests/MapboxMapsTests/Foundation/GeoJSON/GeoJSONManagerTests.swift
Labels: skip changelog, breaking change :warning:

#597 Correctly support cluster properties
  CHANGELOG.md
  Sources/MapboxMaps/Style/Generated/Sources/GeojsonSource.swift
  Tests/MapboxMapsTests/Style/Fixtures/Fixtures.swift
  Tests/MapboxMapsTests/Style/Generated/Sources/GeoJsonSourceTests.swift
Labels: bug :beetle:

#609 Update core and common dependencies
  Apps/Apps.xcworkspace/xcshareddata/swiftpm/Package.resolved
  CHANGELOG.md
  MapboxMaps.podspec
  Package.resolved
  Package.swift
  scripts/release/packager/versions.json
Labels: skip changelog

#591 Display attribution in alert controller
  CHANGELOG.md
  Package.swift
  Sources/MapboxMaps/Foundation/Extensions/Bundle+MapboxMaps.swift
  Sources/MapboxMaps/Foundation/MapView+Attribution.swift
  Sources/MapboxMaps/Foundation/MapView.swift
  Sources/MapboxMaps/MapboxMaps.json
  Sources/MapboxMaps/Ornaments/MapboxInfoButtonOrnament.swift
  Sources/MapboxMaps/Ornaments/OrnamentsManager.swift
  Sources/MapboxMaps/Style/AttributionDialogManager.swift
  Tests/MapboxMapsTests/Ornaments/InfoButton/MapboxInfoButtonOrnamentTests.swift
  Tests/MapboxMapsTests/Ornaments/OrnamentManagerTests.swift
  Tests/MapboxMapsTests/Snapshot/AttributionTests.swift
  scripts/release/update-version.sh
Labels: skip changelog

#612 Add specific geometry types to annotations
  CHANGELOG.md
  Sources/MapboxMaps/Annotations/AnnotationOrchestrator.swift
  Sources/MapboxMaps/Annotations/Generated/CircleAnnotation.swift
  Sources/MapboxMaps/Annotations/Generated/CircleAnnotationManager.swift
  Sources/MapboxMaps/Annotations/Generated/PointAnnotation.swift
  Sources/MapboxMaps/Annotations/Generated/PointAnnotationManager.swift
  Sources/MapboxMaps/Annotations/Generated/PolygonAnnotation.swift
  Sources/MapboxMaps/Annotations/Generated/PolygonAnnotationManager.swift
  Sources/MapboxMaps/Annotations/Generated/PolylineAnnotation.swift
  Sources/MapboxMaps/Annotations/Generated/PolylineAnnotationManager.swift
  Tests/MapboxMapsTests/Annotations/Generated/CircleAnnotationTests.swift
  Tests/MapboxMapsTests/Annotations/Generated/PointAnnotationTests.swift
  Tests/MapboxMapsTests/Annotations/Generated/PolygonAnnotationTests.swift
  Tests/MapboxMapsTests/Annotations/Generated/PolylineAnnotationIntegrationTests.swift
  Tests/MapboxMapsTests/Annotations/Generated/PolylineAnnotationTests.swift
Labels: feature :green_apple:, skip changelog, breaking change :warning:

#611 Expose `setFeatureState` / `getFeatureState` / `removeFeatureState` and add associated example
  Apps/Examples/Examples.xcodeproj/project.pbxproj
  Apps/Examples/Examples/All Examples/FeatureStateExample.swift
  Apps/Examples/Examples/Models/Examples.swift
  CHANGELOG.md
  Sources/MapboxMaps/Foundation/MapboxMap.swift
  Tests/MapboxMapsTests/Foundation/Integration Tests/FeatureStateIntegrationTests.swift
Labels: feature :green_apple:

#631 Update Mobile Events
  Apps/Apps.xcworkspace/xcshareddata/swiftpm/Package.resolved
  CHANGELOG.md
  MapboxMaps.podspec
  Package.resolved
  Package.swift
  scripts/release/packager/versions.json
Labels: skip changelog, dependencies

#633 Remove source when deiniting annotation manager
  CHANGELOG.md
  Sources/MapboxMaps/Annotations/Generated/CircleAnnotationManager.swift
  Sources/MapboxMaps/Annotations/Generated/PointAnnotationManager.swift
  Sources/MapboxMaps/Annotations/Generated/PolygonAnnotationManager.swift
  Sources/MapboxMaps/Annotations/Generated/PolylineAnnotationManager.swift
Labels: bug :beetle:
