Repository mapbox/mapbox-maps-ios, pull requests merged in 2021-04, with the labels that each got.

#246 Ensure AnnotationManager's mapLoaded happens first
  CHANGELOG.md
  Sources/MapboxMaps/Annotations/AnnotationManager.swift
  Sources/MapboxMaps/Annotations/AnnotationSupportableMap.swift
  Tests/MapboxMapsTests/Annotations/AnnotationInteractionDelegateTests.swift
  Tests/MapboxMapsTests/Annotations/AnnotationManagerTests.swift
  Tests/MapboxMapsTests/Annotations/MockAnnotationStyleDelegate.swift
  Tests/MapboxMapsTests/Annotations/MockAnnotationSupportableMap.swift
Labels: breaking change :warning:, bug :beetle:

#247 Fix file references in Xcode project
  Mapbox/MapboxMaps.xcodeproj/project.pbxproj
Labels: skip changelog

#248 [style] Decode empty json if needed, regenerate sources + layers
  Sources/MapboxMaps/Style/Generated/Enums/Enums.swift
  Sources/MapboxMaps/Style/Types/Expression.swift
  Sources/MapboxMaps/Style/Types/ExpressionOptions.swift
  Tests/MapboxMapsTests/Style/ExpressionTests/ExpressionTests.swift
  Tests/MapboxMapsTests/Style/Generated/IntegrationTests/Layers/BackgroundLayerIntegrationTests.swift
  Tests/MapboxMapsTests/Style/Generated/IntegrationTests/Layers/CircleLayerIntegrationTests.swift
  Tests/MapboxMapsTests/Style/Generated/IntegrationTests/Layers/FillExtrusionLayerIntegrationTests.swift
  Tests/MapboxMapsTests/Style/Generated/IntegrationTests/Layers/FillLayerIntegrationTests.swift
  Tests/MapboxMapsTests/Style/Generated/IntegrationTests/Layers/HeatmapLayerIntegrationTests.swift
  Tests/MapboxMapsTests/Style/Generated/IntegrationTests/Layers/HillshadeLayerIntegrationTests.swift
  Tests/MapboxMapsTests/Style/Generated/IntegrationTests/Layers/LineLayerIntegrationTests.swift
  Tests/MapboxMapsTests/Style/Generated/IntegrationTests/Layers/LocationIndicatorLayerIntegrationTests.swift
  Tests/MapboxMapsTests/Style/Generated/IntegrationTests/Layers/RasterLayerIntegrationTests.swift
  Tests/MapboxMapsTests/Style/Generated/IntegrationTests/Layers/SkyLayerIntegrationTests.swift
  Tests/MapboxMapsTests/Style/Generated/IntegrationTests/Layers/SymbolLayerIntegrationTests.swift
  Tests/MapboxMapsTests/Style/Generated/IntegrationTests/Sources/GeoJsonSourceIntegrationTests.swift
  Tests/MapboxMapsTests/Style/Generated/IntegrationTests/Sources/ImageSourceIntegrationTests.swift
  Tests/MapboxMapsTests/Style/Generated/IntegrationTests/Sources/RasterDemSourceIntegrationTests.swift
  Tests/MapboxMapsTests/Style/Generated/IntegrationTests/Sources/RasterSourceIntegrationTests.swift
  Tests/MapboxMapsTests/Style/Generated/IntegrationTests/Sources/VectorSourceIntegrationTests.swift
Labels: breaking change :warning:

#238 Add style integration test for style.getLayer(with:)
  Sources/MapboxMaps/Style/Layers.swift
  Tests/MapboxMapsTests/Style/StyleIntegrationTests.swift
Labels: :stop_sign: blocked, skip changelog, testing :100:

#255 Disable Update Manifest Script
  .circleci/config.yml
  scripts/release/update-dependency-manager-manifests.sh
Labels: skip changelog

#256 [bug] Fix puck animation transition
  Sources/MapboxMaps/Location/Pucks/Puck2D.swift
  Sources/MapboxMaps/Style/Style.swift
Labels: bug :beetle:

#257 Update Dependencies
  Apps/Apps.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Apps/Examples/Examples/All Examples/ColorExpressionExample.swift
  Apps/Examples/Examples/All Examples/CustomLayerExample.swift
  Apps/Examples/Examples/All Examples/FeaturesAtPointExample.swift
  Apps/Examples/Examples/All Examples/OfflineRegionManagerExample.swift
  Apps/Examples/Examples/All Examples/SceneKitExample.swift
  Apps/Examples/Examples/All Examples/TrackingModeExample.swift
  Cartfile
  Cartfile.resolved
  Package.resolved
  Package.swift
  Sources/MapboxMaps/Annotations/AnnotationManager.swift
  Sources/MapboxMaps/Annotations/AnnotationSupportableMap.swift
  Sources/MapboxMaps/Foundation/BaseMapView.swift
  Sources/MapboxMaps/Foundation/Camera/CameraManager.swift
  Sources/MapboxMaps/Foundation/Camera/FlyToInterpolator.swift
  Sources/MapboxMaps/Foundation/Events/Event.swift
  Sources/MapboxMaps/Gestures/GestureManager+GestureHandlerDelegate.swift
  Sources/MapboxMaps/Location/Pucks/Puck2D.swift
  Sources/MapboxMaps/Location/Pucks/Puck3D.swift
  Sources/MapboxMaps/MapView/MapView+Managers.swift
  Sources/MapboxMaps/MapView/MapView+Supportable.swift
  Sources/MapboxMaps/Ornaments/OrnamentsManager.swift
  Sources/MapboxMaps/Snapshot/Snapshotter.swift
  Sources/MapboxMaps/Style/Style.swift
  Tests/MapboxMapsTests/Annotations/MockAnnotationSupportableMap.swift
  Tests/MapboxMapsTests/MapView/Integration Tests/AnnotationManagerIntegrationTests.swift
  Tests/MapboxMapsTests/MapView/Integration Tests/CacheManager/CacheManagerIntegrationTests.swift
  Tests/MapboxMapsTests/MapView/Integration Tests/FeatureQueryingTest.swift
  Tests/MapboxMapsTests/MapView/Integration Tests/Map/DidIdleFailureIntegrationTest.swift
  Tests/MapboxMapsTests/MapView/Integration Tests/Map/ObservableIntegrationTests.swift
  Tests/MapboxMapsTests/Style/StyleIntegrationTests.swift
  scripts/release/packager/versions.json
Labels: skip changelog

#262 Add dependency version validator
  .circleci/config.yml
  .depsvalidator.yml
  .swiftlint.yml
  Cartfile
  MapboxMaps.podspec
  scripts/depsvalidator/.gitignore
  scripts/depsvalidator/.swiftlint.yml
  scripts/depsvalidator/.swiftpm/xcode/package.xcworkspace/contents.xcworkspacedata
  scripts/depsvalidator/.swiftpm/xcode/xcshareddata/xcschemes/DepsValidator-Package.xcscheme
  scripts/depsvalidator/.swiftpm/xcode/xcshareddata/xcschemes/DepsValidatorLibrary.xcscheme
  scripts/depsvalidator/.swiftpm/xcode/xcshareddata/xcschemes/depsvalidator.xcscheme
  scripts/depsvalidator/Package.resolved
  scripts/depsvalidator/Package.swift
  scripts/depsvalidator/README.md
  scripts/depsvalidator/Sources/DepsValidator/main.swift
  scripts/depsvalidator/Sources/DepsValidatorLibrary/Commands/DepsValidator.swift
  scripts/depsvalidator/Sources/DepsValidatorLibrary/Commands/Validate.swift
  scripts/depsvalidator/Sources/DepsValidatorLibrary/Models/Carthage.swift
  scripts/depsvalidator/Sources/DepsValidatorLibrary/Models/Config.swift
  scripts/depsvalidator/Sources/DepsValidatorLibrary/Models/JSONManifest.swift
  scripts/depsvalidator/Sources/DepsValidatorLibrary/Models/ManifestCache.swift
  scripts/depsvalidator/Sources/DepsValidatorLibrary/Models/Package.swift
  scripts/depsvalidator/Sources/DepsValidatorLibrary/Models/Podspec.swift
  scripts/depsvalidator/Sources/DepsValidatorLibrary/Models/Process+Shell.swift
  scripts/depsvalidator/Sources/DepsValidatorLibrary/Models/ResolvedPackage.swift
  scripts/depsvalidator/Sources/DepsValidatorLibrary/Models/SemanticVersion.swift
  scripts/depsvalidator/Sources/DepsValidatorLibrary/Models/SemanticVersionProviding.swift
  scripts/depsvalidator/Sources/DepsValidatorLibrary/Models/SemanticVersionRequirement.swift
  scripts/depsvalidator/Sources/DepsValidatorLibrary/Models/VersionRequirementProviding.swift
  scripts/depsvalidator/Tests/DepsValidatorTests/Example Manifests/Example.podspec
  scripts/depsvalidator/Tests/DepsValidatorTests/Example Manifests/Package.swift.example
  scripts/depsvalidator/Tests/DepsValidatorTests/PackageTests.swift
  scripts/depsvalidator/Tests/DepsValidatorTests/PodspecTests.swift
  scripts/depsvalidator/Tests/DepsValidatorTests/SemanticVersionRequirementTests.swift
  scripts/depsvalidator/Tests/DepsValidatorTests/SemanticVersionTests.swift
Labels: skip changelog

#265 Encapsulate MapboxCoreMaps protocol conformances
  CHANGELOG.md
  Mapbox/MapboxMaps.xcodeproj/project.pbxproj
  Sources/MapboxMaps/Foundation/BaseMapView.swift
  Sources/MapboxMaps/Foundation/DelegatingMapClient.swift
  Sources/MapboxMaps/Foundation/DelegatingObserver.swift
  Sources/MapboxMaps/Foundation/PreferredFPS.swift
  Sources/MapboxMaps/Snapshot/Snapshotter.swift
  Tests/MapboxMapsTests/Foundation/DelegatingMapClientTests.swift
  Tests/MapboxMapsTests/Foundation/DelegatingObserverTests.swift
  Tests/MapboxMapsTests/Foundation/MockDelegatingMapClientDelegate.swift
  Tests/MapboxMapsTests/Foundation/MockDelegatingObserverDelegate.swift
  Tests/MapboxMapsTests/MapView/Integration Tests/Map/MapViewIntegrationTests.swift
Labels: breaking change :warning:

#269 Remove a hardcoded value for scale factor
  Sources/MapboxMaps/Style/Style.swift
Labels: bug :beetle:

#267 Cleaning up StyleTransition to use swift values
  Mapbox/MapboxMaps.xcodeproj/project.pbxproj
  Sources/MapboxMaps/Location/Pucks/Puck2D.swift
  Sources/MapboxMaps/Style/Style.swift
  Tests/MapboxMapsTests/Style/StyleTransitionTests.swift
Labels: skip changelog

#281 Remove the `manager` suffix from the MapView's manager properties
  Apps/Examples/Examples/All Examples/AnimateGeoJSONLineExample.swift
  Apps/Examples/Examples/All Examples/AnimateLayerExample.swift
  Apps/Examples/Examples/All Examples/BuildingExtrusionsExample.swift
  Apps/Examples/Examples/All Examples/CameraAnimationExample.swift
  Apps/Examples/Examples/All Examples/CameraAnimatorsExample.swift
  Apps/Examples/Examples/All Examples/ColorExpressionExample.swift
  Apps/Examples/Examples/All Examples/Custom2DPuckExample.swift
  Apps/Examples/Examples/All Examples/Custom3DPuckExample.swift
  Apps/Examples/Examples/All Examples/CustomPointAnnotationExample.swift
  Apps/Examples/Examples/All Examples/DataDrivenSymbolsExample.swift
  Apps/Examples/Examples/All Examples/ExternalVectorSourceExample.swift
  Apps/Examples/Examples/All Examples/FeaturesAtPointExample.swift
  Apps/Examples/Examples/All Examples/FitCameraToGeometryExample.swift
  Apps/Examples/Examples/All Examples/FlyToExample.swift
  Apps/Examples/Examples/All Examples/LayerBelowExample.swift
  Apps/Examples/Examples/All Examples/LayerPositionExample.swift
  Apps/Examples/Examples/All Examples/LineAnnotationExample.swift
  Apps/Examples/Examples/All Examples/LineGradientExample.swift
  Apps/Examples/Examples/All Examples/PointAnnotationExample.swift
  Apps/Examples/Examples/All Examples/PolygonAnnotationExample.swift
  Apps/Examples/Examples/All Examples/RestrictCoordinateBoundsExample.swift
  Apps/Examples/Examples/All Examples/SceneKitExample.swift
  Apps/Examples/Examples/All Examples/SelectAnnotationExample.swift
  Apps/Examples/Examples/All Examples/SnapshotterExample.swift
  Apps/Examples/Examples/All Examples/SwiftUIExample.swift
  Apps/Examples/Examples/All Examples/TerrainExample.swift
  Apps/Examples/Examples/All Examples/TrackingModeExample.swift
  Apps/Examples/Examples/All Examples/UpdatePointAnnotationPositionExample.swift
  Apps/StressTest/StressTest/ViewController.swift
  CHANGELOG.md
  Sources/MapboxMaps/Foundation/BaseMapView.swift
  Sources/MapboxMaps/Foundation/Camera/CameraManager.swift
  Sources/MapboxMaps/Foundation/Camera/CameraView.swift
  Sources/MapboxMaps/MapView/MapView+Managers.swift
  Sources/MapboxMaps/MapView/MapView.swift
  Tests/MapboxMapsTests/Foundation/Camera/MapboxMapsCameraTests.swift
  Tests/MapboxMapsTests/MapView/Integration Tests/Map/MapViewIntegrationTests.swift
  Tests/MapboxMapsTests/MapView/OptionsIntegrationTests.swift
Labels: breaking change :warning:

#280 Introduce MapboxMap
  Apps/Examples/Examples/All Examples/ColorExpressionExample.swift
  Apps/Examples/Examples/All Examples/CustomLayerExample.swift
  Apps/Examples/Examples/All Examples/SceneKitExample.swift
  Apps/StressTest/StressTest/ViewController.swift
  CHANGELOG.md
  Mapbox/MapboxMaps.xcodeproj/project.pbxproj
  Sources/MapboxMaps/Annotations/AnnotationSupportableMap.swift
  Sources/MapboxMaps/Foundation/BaseMapView.swift
  Sources/MapboxMaps/Foundation/Camera/CameraManager.swift
  Sources/MapboxMaps/Foundation/Camera/CameraOptions.swift
  Sources/MapboxMaps/Foundation/Extensions/Core/Size.swift
  Sources/MapboxMaps/Foundation/MapboxMap.swift
  Sources/MapboxMaps/Gestures/GestureManager+GestureHandlerDelegate.swift
  Sources/MapboxMaps/MapView/MapView+Managers.swift
  Sources/MapboxMaps/MapView/MapView+Supportable.swift
  Tests/MapboxMapsTests/Foundation/Extensions/Core/SizeTests.swift
  Tests/MapboxMapsTests/Foundation/MapboxMapTests.swift
  Tests/MapboxMapsTests/Foundation/MockMapClient.swift
  Tests/MapboxMapsTests/MapView/Integration Tests/AnnotationManagerIntegrationTests.swift
  Tests/MapboxMapsTests/MapView/Integration Tests/Map/DidIdleFailureIntegrationTest.swift
  Tests/MapboxMapsTests/MapView/Integration Tests/Map/MapInitOptionsIntegrationTests.swift
  Tests/MapboxMapsTests/MapView/Integration Tests/Map/ObservableIntegrationTests.swift
  Tests/MapboxMapsTests/Style/StyleIntegrationTests.swift
Labels: breaking change :warning:, skip changelog

#284 Introduce struct variant of CameraOptions
  CHANGELOG.md
  Mapbox/MapboxMaps.xcodeproj/project.pbxproj
  Sources/MapboxMaps/Foundation/Camera/CameraManager.swift
  Sources/MapboxMaps/Foundation/Camera/CameraOptions.swift
  Sources/MapboxMaps/Foundation/Camera/CameraView.swift
  Sources/MapboxMaps/Foundation/Extensions/NSNumber.swift
  Sources/MapboxMaps/Foundation/MapboxMap.swift
  Sources/MapboxMaps/Gestures/GestureManager+GestureHandlerDelegate.swift
  Sources/MapboxMaps/MapView/MapView+Supportable.swift
  Sources/MapboxMaps/Snapshot/Snapshotter.swift
  Tests/MapboxMapsTests/Foundation/Camera/CameraOptionsTests.swift
  Tests/MapboxMapsTests/Foundation/MapboxMapTests.swift
Labels: breaking change :warning:

#279 Add OfflineManager support and associated example
  Apps/Apps.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Apps/Examples/Examples.xcodeproj/project.pbxproj
  Apps/Examples/Examples/All Examples/OfflineManagerExample.storyboard
  Apps/Examples/Examples/All Examples/OfflineManagerExample.swift
  Apps/Examples/Examples/Models/Example.swift
  Apps/Examples/Examples/Models/Examples.swift
  CHANGELOG.md
  Cartfile
  Cartfile.resolved
  Mapbox/MapboxMaps.xcodeproj/project.pbxproj
  MapboxMaps.podspec
  Package.resolved
  Package.swift
  Sources/MapboxMaps/Foundation/BaseMapView.swift
  Sources/MapboxMaps/Foundation/Cancelable.swift
  Sources/MapboxMaps/Foundation/Extensions/Core/MapEvents.swift
  Sources/MapboxMaps/Foundation/Extensions/Core/MapSnapshotOptions.swift
  Sources/MapboxMaps/Foundation/Extensions/Core/ResourceOptions.swift
  Sources/MapboxMaps/Offline/OfflineCallbacks.swift
  Sources/MapboxMaps/Offline/OfflineErrors.swift
  Sources/MapboxMaps/Offline/OfflineManager+MapboxMaps.swift
  Sources/MapboxMaps/Offline/StylePackLoadOptions+MapboxMaps.swift
  Sources/MapboxMaps/Offline/TileRegionLoadOptions+MapboxMaps.swift
  Sources/MapboxMaps/Offline/TileStore+MapboxMaps.swift
  Sources/MapboxMaps/Offline/TilesetDescriptorOptions+MapboxMaps.swift
  Sources/MapboxMaps/Snapshot/MapSnapshotOptions.swift
  Tests/MapboxMapsTests/MapView/Integration Tests/CacheManager/CacheManagerIntegrationTests.swift
  Tests/MapboxMapsTests/MapView/Integration Tests/MapViewIntegrationTestCase.swift
  Tests/MapboxMapsTests/MapView/Integration Tests/Style/StyleLoadIntegrationTests.swift
  Tests/MapboxMapsTests/Style/GeoJSONSourceDataTests.swift
  Tests/MapboxMapsTests/Style/StyleIntegrationTests.swift
  scripts/release/packager/versions.json
Labels: breaking change :warning:, skip changelog

#288 Refactor ornaments library
  Mapbox/MapboxMaps.xcodeproj/project.pbxproj
  Package.swift
  Sources/MapboxMaps/Annotations/Info.plist
  Sources/MapboxMaps/Annotations/MapboxMapsAnnotations.h
  Sources/MapboxMaps/Foundation/Info.plist
  Sources/MapboxMaps/Foundation/LogoView.swift
  Sources/MapboxMaps/Foundation/MapboxMapsFoundation.h
  Sources/MapboxMaps/Gestures/Gestures.h
  Sources/MapboxMaps/Gestures/Info.plist
  Sources/MapboxMaps/Location/Info.plist
  Sources/MapboxMaps/Location/MapboxMapsLocation.h
  Sources/MapboxMaps/MapView/Configuration/OrnamentOptions.swift
  Sources/MapboxMaps/MapView/MapView+Managers.swift
  Sources/MapboxMaps/Offline/Info.plist
  Sources/MapboxMaps/Offline/MapboxMapsOffline.h
  Sources/MapboxMaps/Ornaments/Info.plist
  Sources/MapboxMaps/Ornaments/MapboxMapsOrnaments.h
  Sources/MapboxMaps/Ornaments/OrnamentConfig.swift
  Sources/MapboxMaps/Ornaments/OrnamentOptions.swift
  Sources/MapboxMaps/Ornaments/OrnamentsManager.swift
  Sources/MapboxMaps/Ornaments/ScaleBar/MapboxScaleBarConstants.swift
  Sources/MapboxMaps/Snapshot/Info.plist
  Sources/MapboxMaps/Snapshot/MapboxMapsSnapshot.h
  Sources/MapboxMaps/Style/Info.plist
  Sources/MapboxMaps/Style/MapboxMapsStyle.h
  Tests/MapboxMapsTests/Annotations/Info.plist
  Tests/MapboxMapsTests/Foundation/Info.plist
  Tests/MapboxMapsTests/Gestures/Info.plist
  Tests/MapboxMapsTests/Location/Info.plist
  Tests/MapboxMapsTests/MapView/OptionsIntegrationTests.swift
  Tests/MapboxMapsTests/Offline/Info.plist
  Tests/MapboxMapsTests/Ornaments/Info.plist
  Tests/MapboxMapsTests/Ornaments/OrnamentManagerTests.swift
  Tests/MapboxMapsTests/Snapshot/Info.plist
  Tests/MapboxMapsTests/Style/Info.plist
Labels: breaking change :warning:

#295 Fix Xcode project
  Mapbox/MapboxMaps.xcodeproj/project.pbxproj
Labels: skip changelog

#298 Remove unused scale param from Style.setStyleImage
  Apps/Examples/Examples/All Examples/DataDrivenSymbolsExample.swift
  Sources/MapboxMaps/Annotations/AnnotationManager.swift
  Sources/MapboxMaps/Annotations/AnnotationStyleDelegate.swift
  Sources/MapboxMaps/Location/Pucks/Puck2D.swift
  Sources/MapboxMaps/Style/Style.swift
  Tests/MapboxMapsTests/Annotations/MockAnnotationStyleDelegate.swift
  Tests/MapboxMapsTests/MapView/Integration Tests/AnnotationManagerIntegrationTests.swift
Labels: breaking change :warning:

#282 [Camera Animations] Introduce short-lived camera view
  Apps/Examples/Examples/All Examples/CameraAnimatorsExample.swift
  Apps/Examples/Examples/All Examples/FlyToExample.swift
  Apps/Examples/Examples/All Examples/GeoJSONSourceExample.swift
  CHANGELOG.md
  Mapbox/MapboxMaps.xcodeproj/project.pbxproj
  Sources/MapboxMaps/Foundation/BaseMapView.swift
  Sources/MapboxMaps/Foundation/Camera/AnimationOwner.swift
  Sources/MapboxMaps/Foundation/Camera/BasicCameraAnimator.swift
  Sources/MapboxMaps/Foundation/Camera/CameraAnimationDelegate.swift
  Sources/MapboxMaps/Foundation/Camera/CameraAnimationsManager+CameraAnimatorDelegate.swift
  Sources/MapboxMaps/Foundation/Camera/CameraAnimationsManager.swift
  Sources/MapboxMaps/Foundation/Camera/CameraAnimator.swift
  Sources/MapboxMaps/Foundation/Camera/CameraTransition.swift
  Sources/MapboxMaps/Foundation/Camera/CameraView.swift
  Sources/MapboxMaps/Foundation/Camera/FlyToCameraAnimator.swift
  Sources/MapboxMaps/Foundation/Camera/FlyToInterpolator.swift
  Sources/MapboxMaps/Foundation/Camera/WeakCameraAnimatorSet.swift
  Sources/MapboxMaps/Foundation/DateProvider.swift
  Sources/MapboxMaps/Foundation/Extensions/Core/MBXEdgeInsets.swift
  Sources/MapboxMaps/Gestures/GestureManager+GestureHandlerDelegate.swift
  Sources/MapboxMaps/Gestures/GestureManager.swift
  Sources/MapboxMaps/MapView/MapView+Managers.swift
  Sources/MapboxMaps/MapView/MapView+Supportable.swift
  Sources/MapboxMaps/MapView/MapView.swift
  Tests/MapboxMapsTests/Foundation/Camera/CameraAnimatorDelegateMock.swift
  Tests/MapboxMapsTests/Foundation/Camera/CameraAnimatorTests.swift
  Tests/MapboxMapsTests/Foundation/Camera/CameraTransitionTests.swift
  Tests/MapboxMapsTests/Foundation/Camera/CameraViewMock.swift
  Tests/MapboxMapsTests/Foundation/Camera/CameraViewTests.swift
  Tests/MapboxMapsTests/Foundation/Camera/FlyToAnimatorTests.swift
  Tests/MapboxMapsTests/Foundation/Camera/MapboxMapsCameraTests.swift
  Tests/MapboxMapsTests/Foundation/Camera/UIViewPropertyAnimatorMock.swift
  Tests/MapboxMapsTests/Gestures/GestureManagerTests.swift
  Tests/MapboxMapsTests/MapView/Integration Tests/ExampleIntegrationTest.swift
  Tests/MapboxMapsTests/MapView/Integration Tests/FeatureQueryingTest.swift
  Tests/MapboxMapsTests/MapView/Integration Tests/Map/DidIdleFailureIntegrationTest.swift
Labels: breaking change :warning:

#286 Move camera(for: methods to MapboxMap
  Apps/Examples/Examples/All Examples/FitCameraToGeometryExample.swift
  Apps/Examples/Examples/All Examples/RestrictCoordinateBoundsExample.swift
  CHANGELOG.md
  Mapbox/MapboxMaps.xcodeproj/project.pbxproj
  Sources/MapboxMaps/Annotations/AnnotationSupportableMap.swift
  Sources/MapboxMaps/Foundation/Camera/CameraAnimationsManager.swift
  Sources/MapboxMaps/Foundation/Extensions/Core/ScreenBox.swift
  Sources/MapboxMaps/Foundation/MapboxMap.swift
  Tests/MapboxMapsTests/Foundation/Camera/MapboxMapsCameraTests.swift
  Tests/MapboxMapsTests/Foundation/Extensions/Core/ScreenBoxTests.swift
  Tests/MapboxMapsTests/Foundation/MapboxMapTests.swift
Labels: breaking change :warning:

#302 Add styleURI and cameraOptions to MapInitOptions
  Apps/Examples/Examples/All Examples/AnimateGeoJSONLineExample.swift
  Apps/Examples/Examples/All Examples/AnimateLayerExample.swift
  Apps/Examples/Examples/All Examples/BuildingExtrusionsExample.swift
  Apps/Examples/Examples/All Examples/ColorExpressionExample.swift
  Apps/Examples/Examples/All Examples/CustomPointAnnotationExample.swift
  Apps/Examples/Examples/All Examples/CustomStyleURLExample.swift
  Apps/Examples/Examples/All Examples/DataDrivenSymbolsExample.swift
  Apps/Examples/Examples/All Examples/ExternalVectorSourceExample.swift
  Apps/Examples/Examples/All Examples/FeaturesAtPointExample.swift
  Apps/Examples/Examples/All Examples/FlyToExample.swift
  Apps/Examples/Examples/All Examples/GeoJSONSourceExample.swift
  Apps/Examples/Examples/All Examples/LayerBelowExample.swift
  Apps/Examples/Examples/All Examples/LayerPositionExample.swift
  Apps/Examples/Examples/All Examples/LineAnnotationExample.swift
  Apps/Examples/Examples/All Examples/LineGradientExample.swift
  Apps/Examples/Examples/All Examples/OfflineManagerExample.swift
  Apps/Examples/Examples/All Examples/OfflineRegionManagerExample.swift
  Apps/Examples/Examples/All Examples/PointAnnotationExample.swift
  Apps/Examples/Examples/All Examples/PolygonAnnotationExample.swift
  Apps/Examples/Examples/All Examples/SceneKitExample.swift
  Apps/Examples/Examples/All Examples/SelectAnnotationExample.swift
  Apps/Examples/Examples/All Examples/SnapshotterCoreGraphicsExample.swift
  Apps/Examples/Examples/All Examples/SnapshotterExample.swift
  Apps/Examples/Examples/All Examples/TerrainExample.swift
  Apps/Examples/Examples/All Examples/TrackingModeExample.swift
  Apps/Examples/Examples/All Examples/UpdatePointAnnotationPositionExample.swift
  Apps/StressTest/StressTest/ViewController.swift
  Package.swift
  Sources/MapboxMaps/Foundation/BaseMapView.swift
  Sources/MapboxMaps/Foundation/Extensions/Core/GlyphsRasterizationOptions.swift
  Sources/MapboxMaps/Foundation/Extensions/Core/MapSnapshotOptions.swift
  Sources/MapboxMaps/Foundation/Extensions/Core/ResourceOptions.swift
  Sources/MapboxMaps/MapView/Configuration/MapInitOptions.swift
  Sources/MapboxMaps/MapView/MapView.swift
  Sources/MapboxMaps/Snapshot/Snapshotter.swift
  Sources/MapboxMaps/Style/Style.swift
  Tests/MapboxMapsTests/Foundation/MapboxMapsFoundationTests.swift
  Tests/MapboxMapsTests/Gestures/GestureManagerTests.swift
  Tests/MapboxMapsTests/MapView/Integration Tests/Map/MapInitOptionsIntegrationTests.swift
  Tests/MapboxMapsTests/MapView/Integration Tests/Map/MapViewIntegrationTests.swift
  Tests/MapboxMapsTests/MapView/Integration Tests/MapViewIntegrationTestCase.swift
  Tests/MapboxMapsTests/MapView/Unit Tests/MapInitOptionsTests.swift
  Tests/MapboxMapsTests/Resources/empty-style-chicago.json
Labels: breaking change :warning:

#309 Fix NSNumber conversion.
  Mapbox/MapboxMaps.xcodeproj/project.pbxproj
  Sources/MapboxMaps/Foundation/MapboxMap.swift
  Tests/MapboxMapsTests/Foundation/MapboxMapTests.swift
Labels: skip changelog

#310 [Ornaments] Remove ornament options from MapConfig
  Apps/Examples/Examples/All Examples/BasicMapExample.swift
  CHANGELOG.md
  Sources/MapboxMaps/Foundation/LogoView.swift
  Sources/MapboxMaps/MapView/Configuration/MapConfig.swift
  Sources/MapboxMaps/MapView/MapView+Managers.swift
  Sources/MapboxMaps/MapView/MapView.swift
  Sources/MapboxMaps/Ornaments/OrnamentOptions.swift
  Sources/MapboxMaps/Ornaments/OrnamentsManager.swift
Labels: breaking change :warning:
