Repository mapbox/mapbox-maps-ios, pull requests merged in 2021-07, with the labels that each got.

#522 Update to MapboxCoreMaps v10.0.0-rc.4
  Apps/Apps.xcworkspace/xcshareddata/swiftpm/Package.resolved
  CHANGELOG.md
  Mapbox/MapboxMaps.xcodeproj/project.pbxproj
  Mapbox/MapboxMaps.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  MapboxMaps.podspec
  Package.resolved
  Package.swift
  Sources/MapboxMaps/Offline/OfflineErrors.swift
  scripts/release/packager/versions.json
Labels: skip changelog

#519 Fix animator bugs
  CHANGELOG.md
  Mapbox/MapboxMaps.xcodeproj/project.pbxproj
  Sources/MapboxMaps/Foundation/Camera/AnimationCompletion.swift
  Sources/MapboxMaps/Foundation/Camera/BasicCameraAnimator.swift
  Sources/MapboxMaps/Foundation/Camera/CameraAnimationDelegate.swift
  Sources/MapboxMaps/Foundation/Camera/CameraAnimationsManager+CameraAnimatorDelegate.swift
  Sources/MapboxMaps/Foundation/Camera/CameraAnimationsManager.swift
  Sources/MapboxMaps/Foundation/Camera/CameraAnimatorMapboxMap.swift
  Sources/MapboxMaps/Foundation/Camera/CameraTransition.swift
  Sources/MapboxMaps/Foundation/Camera/CameraView.swift
  Sources/MapboxMaps/Foundation/Camera/FlyToCameraAnimator.swift
  Sources/MapboxMaps/Foundation/Extensions/Core/CoordinateBounds.swift
  Sources/MapboxMaps/Foundation/MapView+Supportable.swift
  Sources/MapboxMaps/Foundation/MapView.swift
  Sources/MapboxMaps/Foundation/MapboxMap.swift
  Sources/MapboxMaps/Gestures/CameraAnimationsManagerProtocol.swift
  Sources/MapboxMaps/Gestures/GestureManager+GestureHandlerDelegate.swift
  Sources/MapboxMaps/Gestures/GestureManager.swift
  Tests/MapboxMapsTests/Foundation/Camera/BasicCameraAnimatorIntegrationTests.swift
  Tests/MapboxMapsTests/Foundation/Camera/BasicCameraAnimatorTests.swift
  Tests/MapboxMapsTests/Foundation/Camera/CameraAnimatorDelegateMock.swift
  Tests/MapboxMapsTests/Foundation/Camera/CameraAnimatorTests.swift
  Tests/MapboxMapsTests/Foundation/Camera/CameraViewMock.swift
  Tests/MapboxMapsTests/Foundation/Camera/CameraViewTests.swift
  Tests/MapboxMapsTests/Foundation/Camera/FlyToAnimatorTests.swift
  Tests/MapboxMapsTests/Foundation/Camera/FlyToCameraAnimatorTests.swift
  Tests/MapboxMapsTests/Foundation/Camera/MapboxMapsCameraTests.swift
  Tests/MapboxMapsTests/Foundation/Camera/MockCameraAnimatorMapboxMap.swift
  Tests/MapboxMapsTests/Foundation/Camera/MockPropertyAnimator.swift
  Tests/MapboxMapsTests/Foundation/MapViewTests.swift
  Tests/MapboxMapsTests/Foundation/Mocks/MockCameraAnimator.swift
  Tests/MapboxMapsTests/Foundation/Mocks/MockDateProvider.swift
  Tests/MapboxMapsTests/Gestures/GestureManagerTests.swift
  Tests/MapboxMapsTests/Gestures/MockCameraAnimationsManager.swift
Labels: bug :beetle:, skip changelog

#527 Expose display link duration and timestamp for metrics purposes
  Sources/MapboxMaps/Foundation/DisplayLinkProtocol.swift
  Sources/MapboxMaps/Foundation/MapView.swift
  Tests/MapboxMapsTests/Foundation/MapViewTests.swift
  Tests/MapboxMapsTests/Foundation/Mocks/MockDisplayLink.swift
Labels: skip changelog

#529 Fix Xcode project errors and warnings
  Mapbox/Configurations/Mapbox.xcconfig
  Mapbox/MapboxMaps.xcodeproj/project.pbxproj
  Sources/MapboxMaps/Foundation/Extensions/Turf/Feature.swift
  scripts/release/packager/project.yml
Labels: skip changelog

#512 Allow localization by Layer ID
  Apps/Examples/Examples/All Examples/LocalizationExample.swift
  CHANGELOG.md
  Mapbox/MapboxMaps.xcodeproj/project.pbxproj
  Sources/MapboxMaps/Foundation/MapView.swift
  Sources/MapboxMaps/Style/Style+Localization.swift
  Sources/MapboxMaps/Style/SupportedLanguage.swift
  Tests/MapboxMapsTests/Style/StyleIntegrationTests.swift
Labels: breaking change :warning:, feature :green_apple:

#542 Move check for simulator to the beginning of `checkForMetalSupport`
  Sources/MapboxMaps/Foundation/MapView.swift
Labels: performance :zap:

#545 update to core rc.5
  Apps/Apps.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Mapbox/MapboxMaps.xcodeproj/project.pbxproj
  Mapbox/MapboxMaps.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  MapboxMaps.podspec
  Package.resolved
  Package.swift
  scripts/release/packager/versions.json
Labels: skip changelog

#536 [examples] Add an example that shows how to show or hide a layer
  Apps/Examples/Examples.xcodeproj/project.pbxproj
  Apps/Examples/Examples/All Examples/ShowHideLayerExample.swift
  Apps/Examples/Examples/Models/Examples.swift
Labels: docs :scroll:

#532 [examples] Check whether an annotation was selected
  Apps/Examples/Examples/All Examples/SelectAnnotationExample.swift
Labels: bug :beetle:

#544 adding xcode 13 to matrix
  .circleci/config.yml
Labels: skip changelog

#554 [Examples] Add live data example
  Apps/Examples/Examples.xcodeproj/project.pbxproj
  Apps/Examples/Examples/All Examples/LiveDataExample.swift
  Apps/Examples/Examples/Models/Examples.swift
Labels: docs :scroll:

#562 Fixes leak in creating UIImage from MBMImage
  Sources/MapboxMaps/Foundation/Extensions/UIImage.swift
Labels: bug :beetle:
