Repository mapbox/mapbox-maps-ios, pull requests merged in 2021-02, with the labels that each got.

#61 Remove unused MapboxMapsCommons files
  Mapbox/MapboxMaps.xcodeproj/project.pbxproj
  Mapbox/MapboxMaps.xcodeproj/xcshareddata/xcschemes/All simulator tests.xcscheme
  Mapbox/MapboxMapsCommons/Info.plist
  Mapbox/MapboxMapsCommons/MapboxMapsCommons.h
  Mapbox/MapboxMapsCommonsTests/Info.plist
  Mapbox/MapboxMapsCommonsTests/MapboxMapsEventsManagerTests.swift
Labels: skip changelog

#64 [Tests] Re-enables and updates the HTTP stack replacement tests
  Mapbox/MapboxMaps.xcodeproj/project.pbxproj
  Mapbox/MapboxMaps.xcodeproj/xcshareddata/xcschemes/MapboxMapsHTTPTestsWithHost.xcscheme
  Mapbox/MapboxMapsTests/Integration Tests/HTTP/HTTPIntegrationTests.swift
  StressTest/StressTest/ViewController.swift
Labels: skip changelog

#71 Include generated files in code coverage number
  codecov.yml
Labels: skip changelog

#58 Run examples tests on devices
  .circleci/config.yml
  DebugApp/DebugApp.xcodeproj/project.pbxproj
  DebugApp/insert_access_token.sh
  Examples/Examples.xcodeproj/project.pbxproj
  Examples/Examples/All Examples/AnimateGeoJSONLineExample.swift
  Examples/Examples/Models/Examples.swift
  Examples/insert_access_token.sh
  Makefile
  Mapbox/Configurations/testhost.xcconfig
  scripts/device-farm/testspec.yml
  scripts/insert_access_token.sh
Labels: build

#70 Refactor Annotation "properties"
  Mapbox/MapboxMapsAnnotations/Annotation.swift
  Mapbox/MapboxMapsAnnotations/AnnotationManager.swift
  Mapbox/MapboxMapsAnnotations/LineAnnotation.swift
  Mapbox/MapboxMapsAnnotations/PointAnnotation.swift
  Mapbox/MapboxMapsAnnotations/PolygonAnnotation.swift
  Mapbox/MapboxMapsTests/Integration Tests/AnnotationManagerIntegrationTests.swift
Labels: bug :beetle:

#76 [style] Convert `ColorRepresentable` to a struct
  Mapbox/MapboxMaps.xcodeproj/project.pbxproj
  Mapbox/MapboxMapsStyle/Types/Color.swift
  Mapbox/MapboxMapsStyle/Types/ExpressionOptions.swift
  Mapbox/MapboxMapsStyleTests/ColorTests.swift
  Mapbox/MapboxMapsStyleTests/Fixtures/Value+Fixtures.swift
Labels: skip changelog

#77 Check that displayLink is not nil in updateDisplayLinkPreferredFramesPerSecond
  Mapbox/MapboxMapsFoundation/BaseMapView.swift
  Mapbox/MapboxMapsTests/Integration Tests/Map/MapViewIntegrationTests.swift
Labels: skip changelog

#82 [build] Add version script and update Mapbox project targets (only)
  Mapbox/MapboxMaps.xcodeproj/project.pbxproj
  Mapbox/MapboxMaps/Info.plist
  Mapbox/MapboxMapsAnnotations/Info.plist
  Mapbox/MapboxMapsAnnotationsTests/Info.plist
  Mapbox/MapboxMapsFoundation/Info.plist
  Mapbox/MapboxMapsFoundationTests/Info.plist
  Mapbox/MapboxMapsGestures/Info.plist
  Mapbox/MapboxMapsGesturesTests/Info.plist
  Mapbox/MapboxMapsLocation/Info.plist
  Mapbox/MapboxMapsLocationTests/Info.plist
  Mapbox/MapboxMapsOffline/Info.plist
  Mapbox/MapboxMapsOfflineTests/Info.plist
  Mapbox/MapboxMapsOrnaments/Info.plist
  Mapbox/MapboxMapsOrnamentsTests/Info.plist
  Mapbox/MapboxMapsSnapshot/Info.plist
  Mapbox/MapboxMapsSnapshotTests/Info.plist
  Mapbox/MapboxMapsStyle/Info.plist
  Mapbox/MapboxMapsStyleTests/Info.plist
  Mapbox/MapboxMapsTests/Info.plist
  Mapbox/MapboxTestHost/Info.plist
  scripts/release/update-version.sh
Labels: skip changelog

#83 Update CI/CD Automation For Releases
  .circleci/config.yml
  MapboxMaps.podspec
  scripts/release/update-spm-manifest.sh
  scripts/release/update-version.sh
Labels: skip changelog

#68 Fix Inconsistent Camera Heading
  Mapbox/MapboxMapsFoundation/Camera/CameraManager.swift
  Mapbox/MapboxMapsFoundationTests/Camera/MapboxMapsCameraTests.swift
Labels: bug :beetle:

#84 [ornaments] Honor updates to the ornament options
  Mapbox/MapboxMaps.xcodeproj/project.pbxproj
  Mapbox/MapboxMaps/MapView+Managers.swift
  Mapbox/MapboxMapsTests/OptionsIntegrationTests.swift
Labels: bug :beetle:

#75 [tests] Adding generated integration tests
  Mapbox/MapboxMaps.xcodeproj/project.pbxproj
  Mapbox/MapboxMapsStyle/Generated/Layers/BackgroundLayer.swift
  Mapbox/MapboxMapsStyle/Generated/Layers/CircleLayer.swift
  Mapbox/MapboxMapsStyle/Generated/Layers/FillExtrusionLayer.swift
  Mapbox/MapboxMapsStyle/Generated/Layers/FillLayer.swift
  Mapbox/MapboxMapsStyle/Generated/Layers/HeatmapLayer.swift
  Mapbox/MapboxMapsStyle/Generated/Layers/HillshadeLayer.swift
  Mapbox/MapboxMapsStyle/Generated/Layers/LineLayer.swift
  Mapbox/MapboxMapsStyle/Generated/Layers/LocationIndicatorLayer.swift
  Mapbox/MapboxMapsStyle/Generated/Layers/ModelLayer.swift
  Mapbox/MapboxMapsStyle/Generated/Layers/RasterLayer.swift
  Mapbox/MapboxMapsStyle/Generated/Layers/SkyLayer.swift
  Mapbox/MapboxMapsStyle/Generated/Layers/SymbolLayer.swift
  Mapbox/MapboxMapsStyle/Style.swift
  Mapbox/MapboxMapsStyleTests/Generated/IntegrationTests/Layers/BackgroundLayerIntegrationTests.swift
  Mapbox/MapboxMapsStyleTests/Generated/IntegrationTests/Layers/CircleLayerIntegrationTests.swift
  Mapbox/MapboxMapsStyleTests/Generated/IntegrationTests/Layers/FillExtrusionLayerIntegrationTests.swift
  Mapbox/MapboxMapsStyleTests/Generated/IntegrationTests/Layers/FillLayerIntegrationTests.swift
  Mapbox/MapboxMapsStyleTests/Generated/IntegrationTests/Layers/HeatmapLayerIntegrationTests.swift
  Mapbox/MapboxMapsStyleTests/Generated/IntegrationTests/Layers/HillshadeLayerIntegrationTests.swift
  Mapbox/MapboxMapsStyleTests/Generated/IntegrationTests/Layers/LineLayerIntegrationTests.swift
  Mapbox/MapboxMapsStyleTests/Generated/IntegrationTests/Layers/LocationIndicatorLayerIntegrationTests.swift
  Mapbox/MapboxMapsStyleTests/Generated/IntegrationTests/Layers/ModelLayerIntegrationTests.swift
  Mapbox/MapboxMapsStyleTests/Generated/IntegrationTests/Layers/RasterLayerIntegrationTests.swift
  Mapbox/MapboxMapsStyleTests/Generated/IntegrationTests/Layers/SkyLayerIntegrationTests.swift
  Mapbox/MapboxMapsStyleTests/Generated/IntegrationTests/Layers/SymbolLayerIntegrationTests.swift
  Mapbox/MapboxMapsStyleTests/Generated/Layers/HeatmapLayerTests.swift
  Mapbox/MapboxMapsStyleTests/Generated/Layers/LineLayerTests.swift
  Mapbox/MapboxMapsStyleTests/Generated/Layers/SkyLayerTests.swift
Labels: testing :100:

#87 Fix MapViewIntegrationTests
  Mapbox/MapboxMapsTests/Integration Tests/Map/MapViewIntegrationTests.swift
Labels: skip changelog

#86 [location] Rely on consumer provided view models directly to customize location pucks
  Examples/Examples/All Examples/CustomLocationIndicatorLayerExample.swift
  Examples/Examples/All Examples/PuckModelLayerExample.swift
  Mapbox/MapboxMaps.xcodeproj/project.pbxproj
  Mapbox/MapboxMapsLocation/Pucks/LocationPuckManager.swift
  Mapbox/MapboxMapsLocation/Pucks/PuckLocationIndicatorLayer.swift
  Mapbox/MapboxMapsLocation/Pucks/PuckModelLayer.swift
  Mapbox/MapboxMapsLocationTests/LocationPuckTests.swift
Labels: breaking change :warning:

#81 [style] Sort stops dictionaries before conversion to expression
  Examples/Examples/All Examples/ColorExpressionExample.swift
  Mapbox/MapboxMaps.xcodeproj/project.pbxproj
  Mapbox/MapboxMapsStyle/Types/ExpressionBuilder.swift
  Mapbox/MapboxMapsStyleTests/ExpressionTests/ExpressionBuilderTests.swift
  Mapbox/MapboxMapsStyleTests/ExpressionTests/ExpressionTests.swift
Labels: bug :beetle:

#92 Use a proxy target for BaseMapView.displayLink
  Mapbox/MapboxMapsFoundation/BaseMapView.swift
Labels: performance :zap:, skip changelog

#94 [map] Expose presentsWithTransaction inside RenderOptions
  Mapbox/MapboxMaps.xcodeproj/project.pbxproj
  Mapbox/MapboxMaps/Configuration/MapOptions.swift
  Mapbox/MapboxMaps/Configuration/RenderOptions.swift
  Mapbox/MapboxMaps/MapView+Managers.swift
  Mapbox/MapboxMapsFoundation/BaseMapView.swift
  Mapbox/MapboxMapsTests/OptionsIntegrationTests.swift
Labels: feature :green_apple:

#98 [style] Make internal representation of colorRepresentable an expression
  Mapbox/MapboxMapsStyle/Types/Color.swift
Labels: skip changelog

#99 Fix pan drift with non-zero bearing
  Mapbox/MapboxMapsFoundation/BaseMapView.swift
  Mapbox/MapboxMapsFoundation/Camera/CameraManager.swift
  Mapbox/MapboxMapsFoundationTests/Camera/MapboxMapsCameraTests.swift
Labels: bug :beetle:

#101 [location] Fix bug where locationOptions were not being set correctly
  Mapbox/MapboxMapsLocation/LocationManager.swift
  Mapbox/MapboxMapsTests/OptionsIntegrationTests.swift
Labels: bug :beetle:

#100 [bug] Disable pan drift for pitched maps
  Mapbox/MapboxMapsGestures/GestureHandlers/PanGestureHandler.swift
  Mapbox/MapboxMapsGestures/GestureManager.swift
  Mapbox/MapboxMapsGesturesTests/PanGestureHandlerTests.swift
Labels: bug :beetle:

#89 Update to Common v10.0.0-beta.9.1 and Core v10.0.0-beta.14.1
  Cartfile
  Cartfile.resolved
  MapboxMaps.podspec
  Package.swift
Labels: breaking change :warning:

#105 Update Changelog 10.0.0 beta.13
  CHANGELOG.md
Labels: skip changelog

#67 Enable code coverage for Device Farm
  .circleci/config.yml
  DEVELOPING.md
  Makefile
  Mapbox/Configurations/Examples_testhost.xcconfig
  Mapbox/Configurations/MapboxTestHost_testhost.xcconfig
  Mapbox/Configurations/testhost.xcconfig
  Mapbox/MapboxMaps.xcodeproj/xcshareddata/xcschemes/MapboxMapsTestsWithHost.xcscheme
  codecov.yml
  scripts/code-coverage/generate-json-report.sh
  scripts/device-farm/devicefarm.mk
  scripts/device-farm/extract-xcresult.py
  scripts/device-farm/testspec.yml
Labels: skip changelog

#78 [examples] Add SwiftUI example
  Examples/Examples.xcodeproj/project.pbxproj
  Examples/Examples/All Examples/ColorExpressionExample.swift
  Examples/Examples/All Examples/SwiftUIExample.swift
  Examples/Examples/All Examples/TerrainExample.swift
  Examples/Examples/Controllers/ExampleTableViewController.swift
  Examples/Examples/Models/Examples.swift
  Examples/ExamplesTests/ExamplesTests.swift
  Mapbox/MapboxMapsStyle/MapboxStyleURL.swift
Labels: docs :scroll:

#103 Prevent pitch and zoom from exceeding limits
  Mapbox/MapboxMaps.xcodeproj/project.pbxproj
  Mapbox/MapboxMapsFoundation/Camera/CameraManager.swift
  Mapbox/MapboxMapsFoundation/Camera/FlyToInterpolator.swift
  Mapbox/MapboxMapsFoundation/Camera/MapCameraOptions.swift
  Mapbox/MapboxMapsFoundation/Extensions/Comparable+Clamped.swift
  Mapbox/MapboxMapsFoundationTests/Camera/MapboxMapsCameraTests.swift
  Mapbox/MapboxMapsFoundationTests/Comparable+ClampedTests.swift
Labels: bug :beetle:

#109 Fix quick zoom gesture at high zoom levels
  Mapbox/Configurations/unitTests.xcconfig
  Mapbox/MapboxMaps.xcodeproj/project.pbxproj
  Mapbox/MapboxMapsFoundation/Camera/CameraManager.swift
  Mapbox/MapboxMapsGestures/GestureHandlers/PinchGestureHandler.swift
  Mapbox/MapboxMapsGestures/GestureHandlers/QuickZoomGestureHandler.swift
  Mapbox/MapboxMapsGestures/GestureManager.swift
  Mapbox/MapboxMapsGesturesTests/GestureManagerTests.swift
  Mapbox/MapboxMapsGesturesTests/GestureSupportableViewMock.swift
  Mapbox/MapboxMapsGesturesTests/MockCameraManager.swift
  Mapbox/MapboxMapsGesturesTests/PinchGestureHandlerTests.swift
  Mapbox/MapboxMapsGesturesTests/QuickZoomGestureHandlerTests.swift
  Mapbox/TestHelpers/Stub.swift
Labels: breaking change :warning:, bug :beetle:

#112 [style] Fix issue where color components were not in the correct range for use by renderer
  Mapbox/MapboxMapsStyle/Types/Color.swift
  Mapbox/MapboxMapsStyleTests/ColorTests.swift
Labels: bug :beetle:

#85 [style] Improve update layer support
  Mapbox/MapboxMaps.xcodeproj/project.pbxproj
  Mapbox/MapboxMapsStyle/Style.swift
  Mapbox/MapboxMapsStyle/StyleErrors.swift
  Mapbox/MapboxMapsStyle/Types/Value.swift
  Mapbox/MapboxMapsStyleTests/StyleIntegrationTests.swift
Labels: feature :green_apple:

#116 Enable Warnings As Errors
  Mapbox/Configurations/base.xcconfig
  Mapbox/MapboxMapsAnnotations/AnnotationSupportableMap.swift
  Mapbox/MapboxMapsFoundation/BaseMapView.swift
  Mapbox/MapboxMapsFoundation/Camera/CameraManager.swift
  Mapbox/MapboxMapsFoundation/Events/Event.swift
  Mapbox/MapboxMapsFoundation/Events/EventsManager.swift
  Mapbox/MapboxMapsFoundation/Extensions/Core/GlyphsRasterizationOptions.swift
  Mapbox/MapboxMapsFoundation/Extensions/Core/MBXGeometry.swift
  Mapbox/MapboxMapsFoundation/Extensions/Core/MapEvents.swift
  Mapbox/MapboxMapsFoundation/Extensions/Core/ScreenCoordinate.swift
  Mapbox/MapboxMapsFoundation/Extensions/CoreGraphics.swift
  Mapbox/MapboxMapsGestures/GestureManager.swift
  Mapbox/MapboxMapsLocation/LocationManager.swift
  Mapbox/MapboxMapsLocation/LocationOptions.swift
  Mapbox/MapboxMapsLocation/Pucks/PuckLocationIndicatorLayer.swift
  Mapbox/MapboxMapsLocation/Pucks/PuckModelLayer.swift
  Mapbox/MapboxMapsOrnaments/OrnamentConfig.swift
  Mapbox/MapboxMapsOrnaments/OrnamentsManager.swift
  Mapbox/MapboxMapsSnapshot/Snapshotter.swift
  Mapbox/MapboxMapsStyle/Layers.swift
  Mapbox/MapboxMapsStyle/ModelSource.swift
  Mapbox/MapboxMapsStyle/Style.swift
  Mapbox/MapboxMapsStyle/Types/Value.swift
  xcode-12.xcconfig
Labels: operations

#129 Revert Examples scheme change from #125
  Examples/Examples.xcodeproj/xcshareddata/xcschemes/Examples.xcscheme
Labels: skip changelog

#118 Cocoapods Build From Source
  Mapbox/Configurations/Mapbox.xcconfig
  MapboxMaps.podspec
  Sources/MapboxMaps/Foundation/Extensions/Core/MBXGeometry.swift
Labels: operations

#131 [CI] Script fixes
  .circleci/config.yml
  scripts/release/update-spm-manifest.sh
Labels: skip changelog

#110 Upload code coverage
  .circleci/config.yml
  Makefile
  cloudformation/ci.template.js
  codecov.yml
  package-lock.json
  scripts/code-coverage/generate-json-report.sh
  scripts/code-coverage/parse-code-coverage.py
  scripts/code-coverage/publish_to_aws.sh
  scripts/device-farm/extract-xcresult.py
  scripts/device-farm/testspec.yml
Labels: skip changelog

#124 [scripts] Introduce packaging scripts to support binary distribution
  .gitignore
  Mapbox/STYLE_README.md
  scripts/release/packager/PACKAGE.md
  scripts/release/packager/build-dependency.sh
  scripts/release/packager/create-xcframework.sh
  scripts/release/packager/download-dependency.sh
  scripts/release/packager/package-mapbox-maps.sh
  scripts/release/packager/project.yml
  scripts/release/packager/versions.json
Labels: skip changelog

#133 Update to Turf v2.0.0-alpha.3
  Cartfile
  Cartfile.resolved
  MapboxMaps.podspec
  Package.resolved
  Package.swift
  scripts/release/packager/versions.json
Labels: breaking change :warning:

#135 Add script to select higher version of Xcode.
  scripts/device-farm/testspec.yml
Labels: operations, skip changelog

#134 Swiftlint fixes & configuration changes; Make GestureManager.delegate weak
  .circleci/config.yml
  .swiftlint.yml
  Examples/ExamplesTests/ExamplesTests.swift
  Examples/ExamplesTests/TestableExampleTests.swift
  Sources/.swiftlint.yml
  Sources/MapboxMaps/Foundation/BaseMapView.swift
  Sources/MapboxMaps/Foundation/Camera/CameraManager.swift
  Sources/MapboxMaps/Foundation/Extensions/Core/MapEvents.swift
  Sources/MapboxMaps/Foundation/Extensions/Turf/Geometry.swift
  Sources/MapboxMaps/Gestures/GestureManager.swift
  Sources/MapboxMaps/Location/Pucks/PuckLocationIndicatorLayer.swift
  Sources/MapboxMaps/Ornaments/OrnamentsManager.swift
  Sources/MapboxMaps/Style/Style.swift
  StressTest/StressTest/SceneDelegate.swift
  StressTest/StressTest/ViewController.swift
  Tests/.swiftlint.yml
  Tests/MapboxMapsTests/Foundation/Camera/MapboxMapsCameraTests.swift
  Tests/MapboxMapsTests/MapView/Integration Tests/CacheManager/CacheManagerIntegrationTests.swift
  Tests/MapboxMapsTests/MapView/Integration Tests/FeatureQueryingTest.swift
  Tests/MapboxMapsTests/MapView/Integration Tests/HTTP/HTTPIntegrationTests.swift
  Tests/MapboxMapsTests/MapView/Integration Tests/Map/DidIdleFailureIntegrationTest.swift
  Tests/MapboxMapsTests/MapView/Integration Tests/Map/MapViewIntegrationTests.swift
  Tests/MapboxMapsTests/MapView/Integration Tests/Map/ObservableIntegrationTests.swift
  Tests/MapboxMapsTests/MapView/Integration Tests/MapViewIntegrationTestCase.swift
  Tests/MapboxMapsTests/Style/ExpressionTests/ExpressionTests.swift
  Tests/MapboxMapsTests/Style/Fixtures/SouceProperties+Fixtures.swift
  Tests/MapboxMapsTests/Style/StyleIntegrationTests.swift
Labels: breaking change :warning:, bug :beetle:

#137 [build] Update automation for new package scripts
  .circleci/config.yml
  scripts/framework/make-core-maps-framework.sh
  scripts/framework/make-xcframework.sh
  scripts/release/create-api-downloads-pr.sh
  scripts/release/create-github-draft-release.sh
  scripts/release/packager/PACKAGE.md
  scripts/release/packager/package-mapbox-maps.sh
  scripts/release/upload-to-registry.sh
Labels: operations

#120 Camera Pan Fix
  Sources/MapboxMaps/Foundation/Camera/CameraManager.swift
  Sources/MapboxMaps/Gestures/GestureHandlers/PanGestureHandler.swift
  Sources/MapboxMaps/Gestures/GestureManager.swift
  Tests/MapboxMapsTests/Foundation/Camera/MapboxMapsCameraTests.swift
  Tests/MapboxMapsTests/Gestures/MockCameraManager.swift
Labels: bug :beetle:

#144 Deduplicate version in podspec
  MapboxMaps.podspec
Labels: skip changelog

#146 Update Examples project to target iOS 11
  Examples/Configurations/base.xcconfig
  Examples/Examples.xcodeproj/project.pbxproj
  Examples/Examples/All Examples/CustomStyleURLExample.swift
  Examples/Examples/All Examples/FlyToExample.swift
  Examples/Examples/All Examples/MapViewExample.swift
  Examples/Examples/All Examples/SnapshotterCoreGraphicsExample.swift
  Examples/Examples/All Examples/SnapshotterExample.swift
  Examples/Examples/All Examples/SwiftUIExample.swift
  Examples/Examples/AppDelegate.swift
  Examples/Examples/Controllers/ExampleTableViewController.swift
  Examples/Examples/Info.plist
  Examples/Examples/SceneDelegate.swift
Labels: skip changelog

#139 Updates coverage format.
  cloudformation/ci.template.js
  scripts/code-coverage/parse-code-coverage.py
Labels: skip changelog

#149 Add static XCFramework option to packager scripts
  scripts/release/README-dynamic.md
  scripts/release/README-static.md
  scripts/release/README.md
  scripts/release/packager/build-dependency.sh
  scripts/release/packager/create-xcframework.sh
  scripts/release/packager/package-mapbox-maps.sh
Labels: feature :green_apple:
