Repository mapbox/mapbox-maps-ios, pull requests merged in 2021-10, with the labels that each got.

#727 Check whether the userInfo for annotations is nil
  Sources/MapboxMaps/Annotations/Generated/CircleAnnotation.swift
  Sources/MapboxMaps/Annotations/Generated/PointAnnotation.swift
  Sources/MapboxMaps/Annotations/Generated/PolygonAnnotation.swift
  Sources/MapboxMaps/Annotations/Generated/PolylineAnnotation.swift
Labels: bug :beetle:

#732 Upgrade Core & Common
  Apps/Apps.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Apps/Examples/Examples/All Examples/CustomLayerExample.swift
  Apps/Examples/Examples/All Examples/OfflineRegionManagerExample.swift
  Apps/Examples/Examples/All Examples/SceneKitExample.swift
  CHANGELOG.md
  MapboxMaps.podspec
  Package.resolved
  Package.swift
  Sources/MapboxMaps/Foundation/DelegatingObserver.swift
  Sources/MapboxMaps/Foundation/MapView.swift
  Sources/MapboxMaps/Foundation/MapboxMap.swift
  Sources/MapboxMaps/Foundation/ObservableProtocol.swift
  Sources/MapboxMaps/Snapshot/Snapshotter.swift
  Tests/MapboxMapsTests/Foundation/DelegatingObserverTests.swift
  Tests/MapboxMapsTests/Foundation/Mocks/MockDelegatingObserverDelegate.swift
  Tests/MapboxMapsTests/MigrationGuide/MigrationGuideIntegrationTests.swift
  scripts/release/packager/versions.json
Labels: skip changelog

#706 Refine OfflineRegionGeometryDefinition for Swift
  Apps/Examples/Examples/All Examples/OfflineRegionManagerExample.swift
  CHANGELOG.md
  Sources/MapboxMaps/Annotations/AnnotationOrchestrator.swift
  Sources/MapboxMaps/Annotations/Generated/CircleAnnotation.swift
  Sources/MapboxMaps/Annotations/Generated/CircleAnnotationManager.swift
  Sources/MapboxMaps/Annotations/Generated/PointAnnotation.swift
  Sources/MapboxMaps/Annotations/Generated/PointAnnotationManager.swift
  Sources/MapboxMaps/Annotations/Generated/PolygonAnnotation.swift
  Sources/MapboxMaps/Annotations/Generated/PolygonAnnotationManager.swift
  Sources/MapboxMaps/Annotations/Generated/PolylineAnnotation.swift
  Sources/MapboxMaps/Annotations/Generated/PolylineAnnotationManager.swift
  Sources/MapboxMaps/Foundation/Extensions/Core/MBXGeometry.swift
  Sources/MapboxMaps/Foundation/Extensions/Core/OfflineRegionGeometryDefinition.swift
  Sources/MapboxMaps/Foundation/Extensions/Core/QueriedFeature.swift
  Sources/MapboxMaps/Foundation/Extensions/CoreLocation.swift
  Sources/MapboxMaps/Foundation/Extensions/Turf/Feature.swift
  Sources/MapboxMaps/Foundation/Extensions/Turf/Geometry.swift
  Sources/MapboxMaps/Foundation/MapFeatureQueryable.swift
  Sources/MapboxMaps/Foundation/MapboxMap.swift
  Sources/MapboxMaps/Offline/TileRegionLoadOptions+MapboxMaps.swift
  Sources/MapboxMaps/Style/Style.swift
  Sources/MapboxMaps/Style/Types/GeoJSONSourceData.swift
  Tests/MapboxMapsTests/Foundation/Extensions/Core/OfflineRegionGeometryDefinitionTests.swift
  Tests/MapboxMapsTests/Foundation/Extensions/Turf/FeatureTests.swift
  Tests/MapboxMapsTests/Foundation/GeoJSON/Geometry+MBXGeometryTests.swift
  Tests/MapboxMapsTests/Foundation/GeoJSON/MultiPolygonTests.swift
  Tests/MapboxMapsTests/Foundation/Integration Tests/FeatureStateIntegrationTests.swift
  Tests/MapboxMapsTests/Offline/TileRegionLoadOptions+MapboxMaps.swift
  Tests/MapboxMapsTests/Style/Fixtures/SourceProperties+Fixtures.swift
Labels: breaking change :warning:

#725 Hold on to annotation managers once constructed
  Apps/DebugApp/DebugApp/DebugViewController.swift
  Apps/Examples/Examples.xcodeproj/project.pbxproj
  Apps/Examples/Examples/All Examples/CustomPointAnnotationExample.swift
  Apps/Examples/Examples/All Examples/LineAnnotationExample.swift
  Apps/Examples/Examples/All Examples/MultiplePointAnnotationsExample.swift
  Apps/Examples/Examples/All Examples/OfflineManagerExample.swift
  Apps/Examples/Examples/All Examples/PolygonAnnotationExample.swift
  Apps/Examples/Examples/All Examples/SelectAnnotationExample.swift
  Apps/Examples/Examples/All Examples/SwiftUIExample.swift
  Apps/Examples/Examples/All Examples/UpdatePointAnnotationPositionExample.swift
  CHANGELOG.md
  Sources/MapboxMaps/Annotations/AnnotationOrchestrator.swift
  Sources/MapboxMaps/Annotations/Generated/CircleAnnotationManager.swift
  Sources/MapboxMaps/Annotations/Generated/PointAnnotationManager.swift
  Sources/MapboxMaps/Annotations/Generated/PolygonAnnotationManager.swift
  Sources/MapboxMaps/Annotations/Generated/PolylineAnnotationManager.swift
  Sources/MapboxMaps/Foundation/Extensions/Core/MBXGeometry.swift
  Sources/MapboxMaps/Foundation/Extensions/Turf/Geometry.swift
  Sources/MapboxMaps/Foundation/MapView.swift
  Tests/MapboxMapsTests/Annotations/Generated/CircleAnnotationIntegrationTests.swift
  Tests/MapboxMapsTests/Annotations/Generated/PointAnnotationIntegrationTests.swift
  Tests/MapboxMapsTests/Annotations/Generated/PolygonAnnotationIntegrationTests.swift
  Tests/MapboxMapsTests/Annotations/Generated/PolylineAnnotationIntegrationTests.swift
  Tests/MapboxMapsTests/Foundation/Integration Tests/MapViewIntegrationTestCase.swift
Labels: skip changelog, breaking change :warning:

#730 GeoJSON objects as expression arguments
  CHANGELOG.md
  Sources/MapboxMaps/Style/Types/Expression.swift
  Sources/MapboxMaps/Style/Types/ExpressionArgumentBuilder.swift
  Tests/MapboxMapsTests/Style/ExpressionTests/ExpressionTests.swift
Labels: feature :green_apple:

#737 Refine and expose TileRegionObserver API
  Apps/DebugApp/DebugApp/DebugViewController.swift
  Apps/Examples/Examples/All Examples/FeaturesAtPointExample.swift
  Apps/Examples/Examples/All Examples/SymbolClusteringExample.swift
  CHANGELOG.md
  Sources/MapboxMaps/Annotations/Generated/CircleAnnotationManager.swift
  Sources/MapboxMaps/Annotations/Generated/PointAnnotationManager.swift
  Sources/MapboxMaps/Annotations/Generated/PolygonAnnotationManager.swift
  Sources/MapboxMaps/Annotations/Generated/PolylineAnnotationManager.swift
  Sources/MapboxMaps/Foundation/Extensions/Core/QueriedFeature.swift
  Sources/MapboxMaps/Foundation/Extensions/Turf/Feature.swift
  Sources/MapboxMaps/Offline/OfflineCallbacks.swift
  Sources/MapboxMaps/Offline/TileStore+MapboxMaps.swift
  Sources/MapboxMaps/Offline/TileStoreObserver.swift
  Sources/MapboxMaps/Offline/TileStoreObserverCancelable.swift
  Sources/MapboxMaps/Offline/TileStoreObserverWrapper.swift
  Sources/MapboxMaps/Offline/TileStoreProtocol.swift
  Sources/MapboxMaps/Style/StyleErrors.swift
  Tests/MapboxMapsTests/Foundation/Extensions/Core/DownloadStatusTests.swift
  Tests/MapboxMapsTests/Foundation/Integration Tests/FeatureQueryingTest.swift
  Tests/MapboxMapsTests/Helpers/XCTestCase+TemporaryCacheDirectory.swift
  Tests/MapboxMapsTests/Offline/Mocks/MockMapboxCommonTileStoreObserver.swift
  Tests/MapboxMapsTests/Offline/Mocks/MockTileStore.swift
  Tests/MapboxMapsTests/Offline/Mocks/MockTileStoreObserver.swift
  Tests/MapboxMapsTests/Offline/TileRegionLoadOptions+MapboxMapsTests.swift
  Tests/MapboxMapsTests/Offline/TileStoreObserverCancelableTests.swift
  Tests/MapboxMapsTests/Offline/TileStoreObserverWrapperTests.swift
Labels: skip changelog

#738 Fix xcodegen config
  project.yml
Labels: skip changelog

#740 Fix TileStoreObserverWrapperTests
  Tests/MapboxMapsTests/Offline/TileStoreObserverWrapperTests.swift
Labels: skip changelog, testing :100:

#741 Turf v2.0.0
  Apps/Apps.xcworkspace/xcshareddata/swiftpm/Package.resolved
  CHANGELOG.md
  MapboxMaps.podspec
  Package.resolved
  Package.swift
  scripts/release/packager/versions.json
Labels: dependencies

#743 Fix telemetry opt-out through attribution dialog
  CHANGELOG.md
  Sources/MapboxMaps/Ornaments/MapboxInfoButtonOrnament.swift
  Sources/MapboxMaps/Ornaments/OrnamentsManager.swift
  Sources/MapboxMaps/Style/AttributionDialogManager.swift
  Tests/MapboxMapsTests/Ornaments/InfoButton/MapboxInfoButtonOrnamentTests.swift
Labels: bug :beetle:
