Repository mapbox/mapbox-maps-ios, pull requests merged in 2021-12, with the labels that each got.

#882 Add MapboxMaps.json to podspec
  MapboxMaps.podspec
Labels: bug :beetle:

#896 Breaking API checks
  .circleci/config.yml
  scripts/api-compatibility-check/.baseapi
  scripts/api-compatibility-check/.baseline.zip
  scripts/api-compatibility-check/README.md
  scripts/api-compatibility-check/breaking-api-check.sh
  scripts/api-compatibility-check/rebuild-baseline.sh
  scripts/release/packager/.gitignore
Labels: build 🛠

#910 [style] Add tile request delay APIs.
  Apps/Examples/Examples/All Examples/RasterTileSourceExample.swift
  Sources/MapboxMaps/Style/Generated/Sources/RasterDemSource.swift
  Sources/MapboxMaps/Style/Generated/Sources/RasterSource.swift
  Sources/MapboxMaps/Style/Generated/Sources/VectorSource.swift
  Tests/MapboxMapsTests/Style/Generated/IntegrationTests/Sources/RasterDemSourceIntegrationTests.swift
  Tests/MapboxMapsTests/Style/Generated/IntegrationTests/Sources/RasterSourceIntegrationTests.swift
  Tests/MapboxMapsTests/Style/Generated/IntegrationTests/Sources/VectorSourceIntegrationTests.swift
  Tests/MapboxMapsTests/Style/Generated/Sources/RasterDemSourceTests.swift
  Tests/MapboxMapsTests/Style/Generated/Sources/RasterSourceTests.swift
  Tests/MapboxMapsTests/Style/Generated/Sources/VectorSourceTests.swift
Labels: feature :green_apple:

#945 Add first view annotation before map load in view annotation samples
  Apps/Examples/Examples/All Examples/ViewAnnotationBasicExample.swift
  Apps/Examples/Examples/All Examples/ViewAnnotationMarkerExample.swift
Labels: skip changelog

#908 Send a turnstile event using Snapshotter
  CHANGELOG.md
  Sources/MapboxMaps/Foundation/Events/Event.swift
  Sources/MapboxMaps/Foundation/Events/EventsManager.swift
  Sources/MapboxMaps/Foundation/Events/EventsStringTokens.swift
  Sources/MapboxMaps/Foundation/Events/MapboxMobileEvents+TelemetryProtocol.swift
  Sources/MapboxMaps/Foundation/MapView.swift
  Sources/MapboxMaps/Snapshot/Snapshotter.swift
  Tests/MapboxMapsTests/Foundation/Events/EventsManagerTests.swift
Labels: feature :green_apple:
