Repository mapbox/mapbox-maps-ios, pull requests merged in 2021-05, with the labels that each got.

#300 Refactor and expose CompassDirectionFormatter
  CHANGELOG.md
  Mapbox/MapboxMaps.xcodeproj/project.pbxproj
  Sources/MapboxMaps/Foundation/Extensions/FloatingPoint.swift
  Sources/MapboxMaps/Ornaments/Compass/CompassDirectionFormatter.swift
  Sources/MapboxMaps/Ornaments/Compass/MapboxCompassOrnamentView.swift
  Sources/MapboxMaps/Ornaments/Compass/bg.lproj/CompassDirectionLong.strings
  Sources/MapboxMaps/Ornaments/Compass/bg.lproj/CompassDirectionShort.strings
  Sources/MapboxMaps/Ornaments/Compass/ca.lproj/CompassDirectionLong.strings
  Sources/MapboxMaps/Ornaments/Compass/ca.lproj/CompassDirectionShort.strings
  Sources/MapboxMaps/Ornaments/Compass/cs.lproj/CompassDirectionLong.strings
  Sources/MapboxMaps/Ornaments/Compass/cs.lproj/CompassDirectionShort.strings
  Sources/MapboxMaps/Ornaments/Compass/da.lproj/CompassDirectionLong.strings
  Sources/MapboxMaps/Ornaments/Compass/da.lproj/CompassDirectionShort.strings
  Sources/MapboxMaps/Ornaments/Compass/de.lproj/CompassDirectionLong.strings
  Sources/MapboxMaps/Ornaments/Compass/de.lproj/CompassDirectionShort.strings
  Sources/MapboxMaps/Ornaments/Compass/en.lproj/CompassDirectionLong.strings
  Sources/MapboxMaps/Ornaments/Compass/en.lproj/CompassDirectionShort.strings
  Sources/MapboxMaps/Ornaments/Compass/es.lproj/CompassDirectionLong.strings
  Sources/MapboxMaps/Ornaments/Compass/es.lproj/CompassDirectionShort.strings
  Sources/MapboxMaps/Ornaments/Compass/fr.lproj/CompassDirectionLong.strings
  Sources/MapboxMaps/Ornaments/Compass/fr.lproj/CompassDirectionShort.strings
  Sources/MapboxMaps/Ornaments/Compass/gl.lproj/CompassDirectionLong.strings
  Sources/MapboxMaps/Ornaments/Compass/gl.lproj/CompassDirectionShort.strings
  Sources/MapboxMaps/Ornaments/Compass/he.lproj/CompassDirectionLong.strings
  Sources/MapboxMaps/Ornaments/Compass/he.lproj/CompassDirectionShort.strings
  Sources/MapboxMaps/Ornaments/Compass/ja.lproj/CompassDirectionLong.strings
  Sources/MapboxMaps/Ornaments/Compass/ja.lproj/CompassDirectionShort.strings
  Sources/MapboxMaps/Ornaments/Compass/ko.lproj/CompassDirectionLong.strings
  Sources/MapboxMaps/Ornaments/Compass/ko.lproj/CompassDirectionShort.strings
  Sources/MapboxMaps/Ornaments/Compass/lt.lproj/CompassDirectionLong.strings
  Sources/MapboxMaps/Ornaments/Compass/lt.lproj/CompassDirectionShort.strings
  Sources/MapboxMaps/Ornaments/Compass/pt-BR.lproj/CompassDirectionLong.strings
  Sources/MapboxMaps/Ornaments/Compass/pt-BR.lproj/CompassDirectionShort.strings
  Sources/MapboxMaps/Ornaments/Compass/ru.lproj/CompassDirectionLong.strings
  Sources/MapboxMaps/Ornaments/Compass/ru.lproj/CompassDirectionShort.strings
  Sources/MapboxMaps/Ornaments/Compass/sv.lproj/CompassDirectionLong.strings
  Sources/MapboxMaps/Ornaments/Compass/sv.lproj/CompassDirectionShort.strings
  Sources/MapboxMaps/Ornaments/Compass/uk.lproj/CompassDirectionLong.strings
  Sources/MapboxMaps/Ornaments/Compass/uk.lproj/CompassDirectionShort.strings
  Sources/MapboxMaps/Ornaments/Compass/vi.lproj/CompassDirectionLong.strings
  Sources/MapboxMaps/Ornaments/Compass/vi.lproj/CompassDirectionShort.strings
  Sources/MapboxMaps/Ornaments/Compass/zh-Hans.lproj/CompassDirectionLong.strings
  Sources/MapboxMaps/Ornaments/Compass/zh-Hans.lproj/CompassDirectionShort.strings
  Sources/MapboxMaps/Ornaments/Compass/zh-Hant.lproj/CompassDirectionLong.strings
  Sources/MapboxMaps/Ornaments/Compass/zh-Hant.lproj/CompassDirectionShort.strings
  Sources/MapboxMaps/Ornaments/DistanceFormatter.swift
  Sources/MapboxMaps/Ornaments/en.lproj/OrnamentsLocalizable.strings
  Tests/MapboxMapsTests/Foundation/Extensions/FloatingPointTests.swift
  Tests/MapboxMapsTests/Ornaments/CompassDirectionFormatterTests.swift
Labels: feature :green_apple:

#301 Document safe area interaction with ornaments
  Sources/MapboxMaps/Ornaments/OrnamentOptions.swift
  Sources/MapboxMaps/Ornaments/OrnamentsManager.swift
Labels: bug :beetle:, skip changelog

#315 Update metrics triggers
  .circleci/config.yml
Labels: skip changelog

#318 Move options for ornaments into individual structs
  Apps/Examples/Examples/All Examples/BasicMapExample.swift
  CHANGELOG.md
  Sources/MapboxMaps/Ornaments/OrnamentOptions.swift
  Sources/MapboxMaps/Ornaments/OrnamentsManager.swift
  Tests/MapboxMapsTests/Ornaments/OrnamentManagerTests.swift
Labels: breaking change :warning:

#319 Move coordinate conversion methods from BaseMapView --> MapboxMap
  Apps/Examples/Examples/All Examples/UpdatePointAnnotationPositionExample.swift
  Sources/MapboxMaps/Foundation/BaseMapView.swift
  Sources/MapboxMaps/Foundation/MapboxMap.swift
  Tests/MapboxMapsTests/Foundation/MapboxMapsFoundationTests.swift
Labels: breaking change :warning:

#320 Add source and source properties to StyleManagerProtocol
  Apps/Examples/Examples/All Examples/AnimateGeoJSONLineExample.swift
  Apps/Examples/Examples/All Examples/AnimateLayerExample.swift
  Apps/Examples/Examples/All Examples/DataDrivenSymbolsExample.swift
  Apps/Examples/Examples/All Examples/ExternalVectorSourceExample.swift
  Apps/Examples/Examples/All Examples/FeaturesAtPointExample.swift
  Apps/Examples/Examples/All Examples/FitCameraToGeometryExample.swift
  Apps/Examples/Examples/All Examples/GeoJSONSourceExample.swift
  Apps/Examples/Examples/All Examples/LayerBelowExample.swift
  Apps/Examples/Examples/All Examples/LayerPositionExample.swift
  Apps/Examples/Examples/All Examples/LineGradientExample.swift
  Apps/Examples/Examples/All Examples/SceneKitExample.swift
  Apps/Examples/Examples/All Examples/TerrainExample.swift
  Sources/MapboxMaps/Annotations/AnnotationManager.swift
  Sources/MapboxMaps/Annotations/AnnotationStyleDelegate.swift
  Sources/MapboxMaps/Foundation/GeoJSONManager.swift
  Sources/MapboxMaps/Location/Pucks/Puck3D.swift
  Sources/MapboxMaps/Style/Sources.swift
  Sources/MapboxMaps/Style/Style.swift
  Sources/MapboxMaps/Style/StyleErrors.swift
  Sources/MapboxMaps/Style/StyleManagerProtocol.swift
  Tests/MapboxMapsTests/Annotations/MockAnnotationStyleDelegate.swift
  Tests/MapboxMapsTests/MapView/Integration Tests/AnnotationManagerIntegrationTests.swift
  Tests/MapboxMapsTests/MapView/Integration Tests/ExampleIntegrationTest.swift
  Tests/MapboxMapsTests/MapView/Integration Tests/HTTP/HTTPIntegrationTests.swift
  Tests/MapboxMapsTests/Style/Generated/IntegrationTests/Layers/BackgroundLayerIntegrationTests.swift
  Tests/MapboxMapsTests/Style/Generated/IntegrationTests/Layers/CircleLayerIntegrationTests.swift
  Tests/MapboxMapsTests/Style/Generated/IntegrationTests/Layers/FillExtrusionLayerIntegrationTests.swift
  Tests/MapboxMapsTests/Style/Generated/IntegrationTests/Layers/FillLayerIntegrationTests.swift
  Tests/MapboxMapsTests/Style/Generated/IntegrationTests/Layers/HeatmapLayerIntegrationTests.swift
  Tests/MapboxMapsTests/Style/Generated/IntegrationTests/Layers/HillshadeLayerIntegrationTests.swift
  Tests/MapboxMapsTests/Style/Generated/IntegrationTests/Layers/LineLayerIntegrationTests.swift
  Tests/MapboxMapsTests/Style/Generated/IntegrationTests/Layers/LocationIndicatorLayerIntegrationTests.swift
  Tests/MapboxMapsTests/Style/Generated/IntegrationTests/Layers/ModelLayerIntegrationTests.swift
  Tests/MapboxMapsTests/Style/Generated/IntegrationTests/Layers/RasterLayerIntegrationTests.swift
  Tests/MapboxMapsTests/Style/Generated/IntegrationTests/Layers/SkyLayerIntegrationTests.swift
  Tests/MapboxMapsTests/Style/Generated/IntegrationTests/Layers/SymbolLayerIntegrationTests.swift
  Tests/MapboxMapsTests/Style/Generated/IntegrationTests/Sources/GeoJsonSourceIntegrationTests.swift
  Tests/MapboxMapsTests/Style/Generated/IntegrationTests/Sources/ImageSourceIntegrationTests.swift
  Tests/MapboxMapsTests/Style/Generated/IntegrationTests/Sources/RasterDemSourceIntegrationTests.swift
  Tests/MapboxMapsTests/Style/Generated/IntegrationTests/Sources/RasterSourceIntegrationTests.swift
  Tests/MapboxMapsTests/Style/Generated/IntegrationTests/Sources/VectorSourceIntegrationTests.swift
Labels: breaking change :warning:

#322 Remove animation capabilities from CameraAnimationsManager.setCamera()
  Apps/Examples/Examples/All Examples/CameraAnimationExample.swift
  Apps/Examples/Examples/All Examples/FitCameraToGeometryExample.swift
  Apps/Examples/Examples/All Examples/LineGradientExample.swift
  Apps/Examples/Examples/All Examples/RestrictCoordinateBoundsExample.swift
  Apps/Examples/Examples/All Examples/SwiftUIExample.swift
  Apps/Examples/Examples/All Examples/TrackingModeExample.swift
  Sources/MapboxMaps/Foundation/Camera/CameraAnimationsManager.swift
  Sources/MapboxMaps/Gestures/GestureManager+GestureHandlerDelegate.swift
  Sources/MapboxMaps/Gestures/GestureManager.swift
  Tests/MapboxMapsTests/Foundation/MapboxMapsFoundationTests.swift
  Tests/MapboxMapsTests/Gestures/MockCameraManager.swift
  Tests/MapboxMapsTests/MapView/Integration Tests/Map/MapViewIntegrationTests.swift
Labels: breaking change :warning:

#321 StyleManagerProtocol pt3 (Updates cluster, image, light, terrain and custom geometry source APIS)
  Apps/Examples/Examples/All Examples/DataDrivenSymbolsExample.swift
  Apps/Examples/Examples/All Examples/SceneKitExample.swift
  Apps/Examples/Examples/All Examples/TerrainExample.swift
  Sources/MapboxMaps/Annotations/AnnotationManager.swift
  Sources/MapboxMaps/Annotations/AnnotationStyleDelegate.swift
  Sources/MapboxMaps/Foundation/Extensions/Turf/Feature.swift
  Sources/MapboxMaps/Location/Pucks/Puck2D.swift
  Sources/MapboxMaps/Style/Style.swift
  Sources/MapboxMaps/Style/StyleErrors.swift
  Sources/MapboxMaps/Style/StyleManagerProtocol.swift
  Tests/MapboxMapsTests/Annotations/MockAnnotationStyleDelegate.swift
  Tests/MapboxMapsTests/MapView/Integration Tests/AnnotationManagerIntegrationTests.swift
Labels: breaking change :warning:

#324 Refactor cache path
  Sources/MapboxMaps/Foundation/Extensions/Core/ResourceOptions.swift
Labels: bug :beetle:

#323 Style: refactor getX and generic functions
  Apps/Examples/Examples/All Examples/AnimateGeoJSONLineExample.swift
  Apps/Examples/Examples/All Examples/AnimateLayerExample.swift
  CHANGELOG.md
  Sources/MapboxMaps/Style/Style.swift
  Sources/MapboxMaps/Style/StyleEncodable.swift
  Sources/MapboxMaps/Style/StyleErrors.swift
  Sources/MapboxMaps/Style/StyleManagerProtocol.swift
  Tests/MapboxMapsTests/MapView/Integration Tests/AnnotationManagerIntegrationTests.swift
  Tests/MapboxMapsTests/Style/Generated/IntegrationTests/Layers/BackgroundLayerIntegrationTests.swift
  Tests/MapboxMapsTests/Style/Generated/IntegrationTests/Layers/CircleLayerIntegrationTests.swift
  Tests/MapboxMapsTests/Style/Generated/IntegrationTests/Layers/FillExtrusionLayerIntegrationTests.swift
  Tests/MapboxMapsTests/Style/Generated/IntegrationTests/Layers/FillLayerIntegrationTests.swift
  Tests/MapboxMapsTests/Style/Generated/IntegrationTests/Layers/HeatmapLayerIntegrationTests.swift
  Tests/MapboxMapsTests/Style/Generated/IntegrationTests/Layers/HillshadeLayerIntegrationTests.swift
  Tests/MapboxMapsTests/Style/Generated/IntegrationTests/Layers/LineLayerIntegrationTests.swift
  Tests/MapboxMapsTests/Style/Generated/IntegrationTests/Layers/LocationIndicatorLayerIntegrationTests.swift
  Tests/MapboxMapsTests/Style/Generated/IntegrationTests/Layers/ModelLayerIntegrationTests.swift
  Tests/MapboxMapsTests/Style/Generated/IntegrationTests/Layers/RasterLayerIntegrationTests.swift
  Tests/MapboxMapsTests/Style/Generated/IntegrationTests/Layers/SkyLayerIntegrationTests.swift
  Tests/MapboxMapsTests/Style/Generated/IntegrationTests/Layers/SymbolLayerIntegrationTests.swift
  Tests/MapboxMapsTests/Style/Generated/IntegrationTests/Sources/GeoJsonSourceIntegrationTests.swift
  Tests/MapboxMapsTests/Style/Generated/IntegrationTests/Sources/ImageSourceIntegrationTests.swift
  Tests/MapboxMapsTests/Style/Generated/IntegrationTests/Sources/RasterDemSourceIntegrationTests.swift
  Tests/MapboxMapsTests/Style/Generated/IntegrationTests/Sources/RasterSourceIntegrationTests.swift
  Tests/MapboxMapsTests/Style/Generated/IntegrationTests/Sources/VectorSourceIntegrationTests.swift
  Tests/MapboxMapsTests/Style/StyleIntegrationTests.swift
  scripts/device-farm/testspec.yml
Labels: breaking change :warning:

#331 Check whether puck layer exists before trying to remove
  CHANGELOG.md
  Sources/MapboxMaps/Location/Pucks/Puck2D.swift
Labels: bug :beetle:

#289 [Offline] Offline Integration Tests
  Sources/MapboxMaps/Offline/OfflineErrors.swift
  Tests/MapboxMapsTests/MapView/Integration Tests/LocationManagerIntegrationTests.swift
  Tests/MapboxMapsTests/MapView/Integration Tests/OfflineManagerIntegrationTests.swift
Labels: testing :100:

#330 Add offlineManager convenience function
  Apps/Examples/Examples/All Examples/OfflineManagerExample.swift
  Sources/MapboxMaps/Foundation/BaseMapView.swift
Labels: feature :green_apple:

#339 Move MapEvents `on` handling from BaseMapView to MapboxMap
  Apps/DebugApp/DebugApp/DebugViewController.swift
  Apps/Examples/Examples/All Examples/AnimateGeoJSONLineExample.swift
  Apps/Examples/Examples/All Examples/AnimateLayerExample.swift
  Apps/Examples/Examples/All Examples/BuildingExtrusionsExample.swift
  Apps/Examples/Examples/All Examples/CameraAnimationExample.swift
  Apps/Examples/Examples/All Examples/CameraAnimatorsExample.swift
  Apps/Examples/Examples/All Examples/ColorExpressionExample.swift
  Apps/Examples/Examples/All Examples/Custom2DPuckExample.swift
  Apps/Examples/Examples/All Examples/Custom3DPuckExample.swift
  Apps/Examples/Examples/All Examples/CustomLayerExample.swift
  Apps/Examples/Examples/All Examples/CustomPointAnnotationExample.swift
  Apps/Examples/Examples/All Examples/CustomStyleURLExample.swift
  Apps/Examples/Examples/All Examples/DataDrivenSymbolsExample.swift
  Apps/Examples/Examples/All Examples/ExternalVectorSourceExample.swift
  Apps/Examples/Examples/All Examples/FeaturesAtPointExample.swift
  Apps/Examples/Examples/All Examples/FitCameraToGeometryExample.swift
  Apps/Examples/Examples/All Examples/FlyToExample.swift
  Apps/Examples/Examples/All Examples/GeoJSONSourceExample.swift
  Apps/Examples/Examples/All Examples/LayerBelowExample.swift
  Apps/Examples/Examples/All Examples/LayerPositionExample.swift
  Apps/Examples/Examples/All Examples/LineAnnotationExample.swift
  Apps/Examples/Examples/All Examples/LineGradientExample.swift
  Apps/Examples/Examples/All Examples/MapViewExample.swift
  Apps/Examples/Examples/All Examples/OfflineManagerExample.swift
  Apps/Examples/Examples/All Examples/OfflineRegionManagerExample.swift
  Apps/Examples/Examples/All Examples/PointAnnotationExample.swift
  Apps/Examples/Examples/All Examples/PolygonAnnotationExample.swift
  Apps/Examples/Examples/All Examples/SceneKitExample.swift
  Apps/Examples/Examples/All Examples/SelectAnnotationExample.swift
  Apps/Examples/Examples/All Examples/SnapshotterCoreGraphicsExample.swift
  Apps/Examples/Examples/All Examples/SnapshotterExample.swift
  Apps/Examples/Examples/All Examples/SwiftUIExample.swift
  Apps/Examples/Examples/All Examples/TerrainExample.swift
  Apps/Examples/Examples/All Examples/TrackingModeExample.swift
  Apps/Examples/Examples/All Examples/UpdatePointAnnotationPositionExample.swift
  Apps/StressTest/StressTest/ViewController.swift
  Mapbox/MapboxMaps.xcodeproj/project.pbxproj
  Sources/MapboxMaps/Annotations/AnnotationManager.swift
  Sources/MapboxMaps/Annotations/AnnotationSupportableMap.swift
  Sources/MapboxMaps/Foundation/BaseMapView.swift
  Sources/MapboxMaps/Foundation/MapEventHandler.swift
  Sources/MapboxMaps/Foundation/MapboxMap.swift
  Sources/MapboxMaps/Foundation/ObservableProtocol.swift
  Sources/MapboxMaps/Foundation/WeakSet.swift
  Sources/MapboxMaps/MapView/MapView+Managers.swift
  Sources/MapboxMaps/MapView/MapView+Supportable.swift
  Sources/MapboxMaps/MapView/MapView.swift
  Sources/MapboxMaps/Snapshot/Snapshotter.swift
  Tests/MapboxMapsTests/Annotations/AnnotationInteractionDelegateTests.swift
  Tests/MapboxMapsTests/Annotations/AnnotationManagerTests.swift
  Tests/MapboxMapsTests/Annotations/MockAnnotationSupportableMap.swift
  Tests/MapboxMapsTests/Foundation/MapEventHandlerTests.swift
  Tests/MapboxMapsTests/MapView/Integration Tests/AnnotationManagerIntegrationTests.swift
  Tests/MapboxMapsTests/MapView/Integration Tests/Map/DidIdleFailureIntegrationTest.swift
  Tests/MapboxMapsTests/MapView/Integration Tests/Map/MapInitOptionsIntegrationTests.swift
  Tests/MapboxMapsTests/MapView/Integration Tests/Map/MapViewIntegrationTests.swift
  Tests/MapboxMapsTests/MapView/Integration Tests/MapViewIntegrationTestCase.swift
  Tests/MapboxMapsTests/MapView/Integration Tests/OfflineManagerIntegrationTests.swift
Labels: breaking change :warning:

#341 Fix for next changes.
  Tests/MapboxMapsTests/MigrationGuide/MigrationGuideIntegrationTests.swift
Labels: skip changelog

#340 Project file clean up
  Mapbox/MapboxMaps.xcodeproj/project.pbxproj
Labels: skip changelog

#346 Temporarily disable offline tests
  Tests/MapboxMapsTests/MapView/Integration Tests/OfflineManagerIntegrationTests.swift
  Tests/MapboxMapsTests/MigrationGuide/OfflineGuideIntegrationTests.swift
Labels: skip changelog, testing :100:

#347 Make Style.uri optional and do not set a default URI if developer provides `nil`
  Apps/Examples/Examples/All Examples/OfflineRegionManagerExample.swift
  Sources/MapboxMaps/MapView/Configuration/MapInitOptions.swift
  Sources/MapboxMaps/Style/Style.swift
  Sources/MapboxMaps/Style/StyleManagerProtocol.swift
  Tests/MapboxMapsTests/MapView/Integration Tests/Style/StyleLoadIntegrationTests.swift
Labels: breaking change :warning:

#348 Simplify Style APIs that take a type parameter that is unnecessary
  Sources/MapboxMaps/Style/Generated/Layers/FillLayer.swift
  Sources/MapboxMaps/Style/Style.swift
  Tests/MapboxMapsTests/MapView/Integration Tests/AnnotationManagerIntegrationTests.swift
  Tests/MapboxMapsTests/Style/Generated/IntegrationTests/Layers/BackgroundLayerIntegrationTests.swift
  Tests/MapboxMapsTests/Style/Generated/IntegrationTests/Layers/CircleLayerIntegrationTests.swift
  Tests/MapboxMapsTests/Style/Generated/IntegrationTests/Layers/FillExtrusionLayerIntegrationTests.swift
  Tests/MapboxMapsTests/Style/Generated/IntegrationTests/Layers/FillLayerIntegrationTests.swift
  Tests/MapboxMapsTests/Style/Generated/IntegrationTests/Layers/HeatmapLayerIntegrationTests.swift
  Tests/MapboxMapsTests/Style/Generated/IntegrationTests/Layers/HillshadeLayerIntegrationTests.swift
  Tests/MapboxMapsTests/Style/Generated/IntegrationTests/Layers/LineLayerIntegrationTests.swift
  Tests/MapboxMapsTests/Style/Generated/IntegrationTests/Layers/LocationIndicatorLayerIntegrationTests.swift
  Tests/MapboxMapsTests/Style/Generated/IntegrationTests/Layers/ModelLayerIntegrationTests.swift
  Tests/MapboxMapsTests/Style/Generated/IntegrationTests/Layers/RasterLayerIntegrationTests.swift
  Tests/MapboxMapsTests/Style/Generated/IntegrationTests/Layers/SkyLayerIntegrationTests.swift
  Tests/MapboxMapsTests/Style/Generated/IntegrationTests/Layers/SymbolLayerIntegrationTests.swift
  Tests/MapboxMapsTests/Style/Generated/IntegrationTests/Sources/GeoJsonSourceIntegrationTests.swift
  Tests/MapboxMapsTests/Style/Generated/IntegrationTests/Sources/ImageSourceIntegrationTests.swift
  Tests/MapboxMapsTests/Style/Generated/IntegrationTests/Sources/RasterDemSourceIntegrationTests.swift
  Tests/MapboxMapsTests/Style/Generated/IntegrationTests/Sources/RasterSourceIntegrationTests.swift
  Tests/MapboxMapsTests/Style/Generated/IntegrationTests/Sources/VectorSourceIntegrationTests.swift
  Tests/MapboxMapsTests/Style/StyleIntegrationTests.swift
Labels: breaking change :warning:

#343 [MapView][Part 1] Move GestureOptions into GestureManager
  Mapbox/MapboxMaps.xcodeproj/project.pbxproj
  Sources/MapboxMaps/Gestures/CameraManagerProtocol.swift
  Sources/MapboxMaps/Gestures/GestureHandlers/GestureHandler.swift
  Sources/MapboxMaps/Gestures/GestureManager.swift
  Sources/MapboxMaps/Gestures/GestureType.swift
  Sources/MapboxMaps/MapView/Configuration/MapConfig.swift
  Sources/MapboxMaps/MapView/MapView+Managers.swift
  Tests/MapboxMapsTests/Gestures/GestureManagerTests.swift
  Tests/MapboxMapsTests/MapView/OptionsIntegrationTests.swift
  Tests/MapboxMapsTests/MigrationGuide/MigrationGuideIntegrationTests.swift
Labels: breaking change :warning:

#344 [MapView][Part 2] Make LocationManager hold LocationOptions directly
  Apps/DebugApp/DebugApp/DebugViewController.swift
  Apps/Examples/Examples/All Examples/Custom2DPuckExample.swift
  Apps/Examples/Examples/All Examples/Custom3DPuckExample.swift
  Apps/Examples/Examples/All Examples/TrackingModeExample.swift
  Sources/MapboxMaps/Location/LocationManager.swift
  Sources/MapboxMaps/MapView/Configuration/MapConfig.swift
  Sources/MapboxMaps/MapView/MapView+Managers.swift
  Tests/MapboxMapsTests/Location/LocationManagerTests.swift
  Tests/MapboxMapsTests/Location/Pucks/Puck3DIntegrationTests.swift
  Tests/MapboxMapsTests/MapView/Integration Tests/LocationManagerIntegrationTests.swift
  Tests/MapboxMapsTests/MapView/OptionsIntegrationTests.swift
  Tests/MapboxMapsTests/MigrationGuide/MigrationGuideIntegrationTests.swift
Labels: breaking change :warning:

#345 [MapView][Part 3]Move mapCameraOptions to CameraAnimationsManager
  Apps/Examples/Examples/All Examples/RestrictCoordinateBoundsExample.swift
  Sources/MapboxMaps/Foundation/Camera/CameraAnimationsManager.swift
  Sources/MapboxMaps/Gestures/CameraManagerProtocol.swift
  Sources/MapboxMaps/Gestures/GestureManager+GestureHandlerDelegate.swift
  Sources/MapboxMaps/MapView/Configuration/MapConfig.swift
  Sources/MapboxMaps/MapView/MapView+Managers.swift
  Tests/MapboxMapsTests/Gestures/MockCameraManager.swift
  Tests/MapboxMapsTests/MapView/Integration Tests/FeatureQueryingTest.swift
  Tests/MapboxMapsTests/MapView/OptionsIntegrationTests.swift
  Tests/MapboxMapsTests/MigrationGuide/MigrationGuideIntegrationTests.swift
Labels: breaking change :warning:

#350 [MapView][Part 4] Make BaseMapView own rendering-related configuration options.
  Sources/MapboxMaps/Foundation/BaseMapView.swift
  Sources/MapboxMaps/MapView/Configuration/MapConfig.swift
  Sources/MapboxMaps/MapView/MapView+Managers.swift
Labels: breaking change :warning:

#221 Add enum for layer position
  Apps/Examples/Examples/All Examples/CustomLayerExample.swift
  Apps/Examples/Examples/All Examples/ExternalVectorSourceExample.swift
  Apps/Examples/Examples/All Examples/LayerBelowExample.swift
  Apps/Examples/Examples/All Examples/LayerPositionExample.swift
  Apps/Examples/Examples/All Examples/SceneKitExample.swift
  Sources/MapboxMaps/Annotations/AnnotationManager.swift
  Sources/MapboxMaps/Annotations/Configuration/AnnotationOptions.swift
  Sources/MapboxMaps/Foundation/Extensions/Core/LayerPosition.swift
  Sources/MapboxMaps/Style/Layers.swift
  Sources/MapboxMaps/Style/Style.swift
  Tests/MapboxMapsTests/Annotations/AnnotationManagerTests.swift
  Tests/MapboxMapsTests/Foundation/Extensions/Core/LayerPositionTests.swift
  Tests/MapboxMapsTests/MapView/Integration Tests/AnnotationManagerIntegrationTests.swift
  Tests/MapboxMapsTests/Style/StyleIntegrationTests.swift
Labels: breaking change :warning:, p0

#352 Split out style from LocationSupportableMapView
  Mapbox/MapboxMaps.xcodeproj/project.pbxproj
  Sources/MapboxMaps/Foundation/MapView.swift
  Sources/MapboxMaps/Location/LocationManager.swift
  Sources/MapboxMaps/Location/LocationStyleDelegate.swift
  Sources/MapboxMaps/Location/LocationSupportableMapView.swift
  Sources/MapboxMaps/Location/Pucks/LocationPuckManager.swift
  Sources/MapboxMaps/Location/Pucks/Puck2D.swift
  Sources/MapboxMaps/Location/Pucks/Puck3D.swift
  Sources/MapboxMaps/MapView/MapView+Supportable.swift
  Sources/MapboxMaps/Style/Sources.swift
  Tests/MapboxMapsTests/Location/LocationManagerTests.swift
  Tests/MapboxMapsTests/Location/LocationSupportableMapViewMock.swift
  Tests/MapboxMapsTests/Location/MockLocationStyleDelegate.swift
  Tests/MapboxMapsTests/MapView/Integration Tests/LocationManagerIntegrationTests.swift
Labels: breaking change :warning:

#354 Add loadStyleURI/loadStyleJSON
  Apps/DebugApp/DebugApp.xcodeproj/xcshareddata/xcschemes/DebugApp.xcscheme
  Apps/DebugApp/DebugApp/Base.lproj/Main.storyboard
  Apps/DebugApp/DebugApp/DebugViewController.swift
  Apps/DebugApp/DebugApp/MainViewController.swift
  Apps/Examples/Examples/All Examples/AnimateGeoJSONLineExample.swift
  Apps/Examples/Examples/All Examples/AnimateLayerExample.swift
  Apps/Examples/Examples/All Examples/BuildingExtrusionsExample.swift
  Apps/Examples/Examples/All Examples/DataDrivenSymbolsExample.swift
  Apps/Examples/Examples/All Examples/ExternalVectorSourceExample.swift
  Apps/Examples/Examples/All Examples/FeaturesAtPointExample.swift
  Apps/Examples/Examples/All Examples/FitCameraToGeometryExample.swift
  Apps/Examples/Examples/All Examples/GeoJSONSourceExample.swift
  Apps/Examples/Examples/All Examples/LayerBelowExample.swift
  Apps/Examples/Examples/All Examples/LayerPositionExample.swift
  Apps/Examples/Examples/All Examples/LineGradientExample.swift
  Apps/Examples/Examples/All Examples/MapViewExample.swift
  Apps/Examples/Examples/All Examples/OfflineRegionManagerExample.swift
  Apps/Examples/Examples/All Examples/SceneKitExample.swift
  Apps/Examples/Examples/All Examples/SwiftUIExample.swift
  Apps/Examples/Examples/All Examples/TerrainExample.swift
  Apps/StressTest/StressTest/ViewController.swift
  Sources/MapboxMaps/Foundation/MapboxMap.swift
  Sources/MapboxMaps/Style/StyleErrors.swift
  Tests/MapboxMapsTests/MapView/Integration Tests/AnnotationManagerIntegrationTests.swift
  Tests/MapboxMapsTests/MapView/Integration Tests/Map/DidIdleFailureIntegrationTest.swift
  Tests/MapboxMapsTests/MapView/Integration Tests/Map/MapInitOptionsIntegrationTests.swift
  Tests/MapboxMapsTests/MapView/Integration Tests/Map/MapboxMapIntegrationTests.swift
  Tests/MapboxMapsTests/MapView/Integration Tests/MapViewIntegrationTestCase.swift
  Tests/MapboxMapsTests/MigrationGuide/MigrationGuideIntegrationTests.swift
Labels: breaking change :warning:

#355 Re-enable offline tests
  Sources/MapboxMaps/Foundation/Extensions/Core/ResourceOptions.swift
  Sources/MapboxMaps/Offline/TileStore+MapboxMaps.swift
  Tests/MapboxMapsTests/MapView/Integration Tests/OfflineManagerIntegrationTests.swift
  Tests/MapboxMapsTests/MigrationGuide/OfflineGuideIntegrationTests.swift
  Tests/MapboxMapsTests/Offline/TileStore+Tests.swift
Labels: skip changelog

#359 [tests] Test adding and removing a Puck2D
  Sources/MapboxMaps/Location/Pucks/Puck2D.swift
  Tests/MapboxMapsTests/Location/Pucks/Puck2DIntegrationTests.swift
Labels: testing :100:

#338 Reduce the frequency of ornaments calling layoutSubviews
  Sources/MapboxMaps/Ornaments/Compass/MapboxCompassOrnamentView.swift
  Sources/MapboxMaps/Ornaments/OrnamentsManager.swift
  Sources/MapboxMaps/Ornaments/ScaleBar/MapboxScaleBarOrnamentView.swift
  Tests/MapboxMapsTests/Ornaments/MapboxCompassOrnamentViewTests.swift
Labels: bug :beetle:

#365 Add missing style parameter to Puck2D initializer in tests
  Tests/MapboxMapsTests/Location/Pucks/Puck2DIntegrationTests.swift
Labels: testing :100:

#362 [Style] Flatten Layout and Paint sub-structs into root struct for all layers
  Apps/Examples/Examples/All Examples/AnimateGeoJSONLineExample.swift
  Apps/Examples/Examples/All Examples/AnimateLayerExample.swift
  Apps/Examples/Examples/All Examples/BuildingExtrusionsExample.swift
  Apps/Examples/Examples/All Examples/DataDrivenSymbolsExample.swift
  Apps/Examples/Examples/All Examples/ExternalVectorSourceExample.swift
  Apps/Examples/Examples/All Examples/FeaturesAtPointExample.swift
  Apps/Examples/Examples/All Examples/FitCameraToGeometryExample.swift
  Apps/Examples/Examples/All Examples/GeoJSONSourceExample.swift
  Apps/Examples/Examples/All Examples/LayerBelowExample.swift
  Apps/Examples/Examples/All Examples/LayerPositionExample.swift
  Apps/Examples/Examples/All Examples/LineGradientExample.swift
  Apps/Examples/Examples/All Examples/SceneKitExample.swift
  Apps/Examples/Examples/All Examples/TerrainExample.swift
  CHANGELOG.md
  Sources/MapboxMaps/Annotations/AnnotationManager.swift
  Sources/MapboxMaps/Location/Pucks/Puck2D.swift
  Sources/MapboxMaps/Style/Generated/Layers/BackgroundLayer.swift
  Sources/MapboxMaps/Style/Generated/Layers/CircleLayer.swift
  Sources/MapboxMaps/Style/Generated/Layers/FillExtrusionLayer.swift
  Sources/MapboxMaps/Style/Generated/Layers/FillLayer.swift
  Sources/MapboxMaps/Style/Generated/Layers/HeatmapLayer.swift
  Sources/MapboxMaps/Style/Generated/Layers/HillshadeLayer.swift
  Sources/MapboxMaps/Style/Generated/Layers/LineLayer.swift
  Sources/MapboxMaps/Style/Generated/Layers/LocationIndicatorLayer.swift
  Sources/MapboxMaps/Style/Generated/Layers/RasterLayer.swift
  Sources/MapboxMaps/Style/Generated/Layers/SkyLayer.swift
  Sources/MapboxMaps/Style/Generated/Layers/SymbolLayer.swift
  Sources/MapboxMaps/Style/ModelLayer.swift
  Tests/MapboxMapsTests/MigrationGuide/MigrationGuideIntegrationTests.swift
  Tests/MapboxMapsTests/Style/Generated/IntegrationTests/Layers/BackgroundLayerIntegrationTests.swift
  Tests/MapboxMapsTests/Style/Generated/IntegrationTests/Layers/CircleLayerIntegrationTests.swift
  Tests/MapboxMapsTests/Style/Generated/IntegrationTests/Layers/FillExtrusionLayerIntegrationTests.swift
  Tests/MapboxMapsTests/Style/Generated/IntegrationTests/Layers/FillLayerIntegrationTests.swift
  Tests/MapboxMapsTests/Style/Generated/IntegrationTests/Layers/HeatmapLayerIntegrationTests.swift
  Tests/MapboxMapsTests/Style/Generated/IntegrationTests/Layers/HillshadeLayerIntegrationTests.swift
  Tests/MapboxMapsTests/Style/Generated/IntegrationTests/Layers/LineLayerIntegrationTests.swift
  Tests/MapboxMapsTests/Style/Generated/IntegrationTests/Layers/LocationIndicatorLayerIntegrationTests.swift
  Tests/MapboxMapsTests/Style/Generated/IntegrationTests/Layers/RasterLayerIntegrationTests.swift
  Tests/MapboxMapsTests/Style/Generated/IntegrationTests/Layers/SkyLayerIntegrationTests.swift
  Tests/MapboxMapsTests/Style/Generated/IntegrationTests/Layers/SymbolLayerIntegrationTests.swift
  Tests/MapboxMapsTests/Style/Generated/Layers/BackgroundLayerTests.swift
  Tests/MapboxMapsTests/Style/Generated/Layers/CircleLayerTests.swift
  Tests/MapboxMapsTests/Style/Generated/Layers/FillExtrusionLayerTests.swift
  Tests/MapboxMapsTests/Style/Generated/Layers/FillLayerTests.swift
  Tests/MapboxMapsTests/Style/Generated/Layers/HeatmapLayerTests.swift
  Tests/MapboxMapsTests/Style/Generated/Layers/HillshadeLayerTests.swift
  Tests/MapboxMapsTests/Style/Generated/Layers/LineLayerTests.swift
  Tests/MapboxMapsTests/Style/Generated/Layers/LocationIndicatorLayerTests.swift
  Tests/MapboxMapsTests/Style/Generated/Layers/RasterLayerTests.swift
  Tests/MapboxMapsTests/Style/Generated/Layers/SkyLayerTests.swift
  Tests/MapboxMapsTests/Style/Generated/Layers/SymbolLayerTests.swift
  Tests/MapboxMapsTests/Style/StyleIntegrationTests.swift
Labels: breaking change :warning:

#363 Expose prefetchZoomDelta directly as part of RenderOptions
  Sources/MapboxMaps/Foundation/MapView.swift
  Sources/MapboxMaps/MapView/Configuration/RenderOptions.swift
Labels: breaking change :warning:

#369 Change Default Render Options
  Sources/MapboxMaps/MapView/Configuration/RenderOptions.swift
Labels: skip changelog

#371 Update migration guide tests
  Tests/MapboxMapsTests/MigrationGuide/MigrationGuideIntegrationTests.swift
Labels: skip changelog

#368 [examples] Add a point clustering example
  Apps/Examples/Examples.xcodeproj/project.pbxproj
  Apps/Examples/Examples/All Examples/PointClusteringExample.swift
  Apps/Examples/Examples/Models/Examples.swift
Labels: docs :scroll:

#384 Reorganize examples, update some titles and descriptions to match Android
  Apps/Examples/Examples/Models/Examples.swift
Labels: docs :scroll:

#386 Added missing camera methods to Snapshotter
  CHANGELOG.md
  Sources/MapboxMaps/Snapshot/Snapshotter.swift
Labels: feature :green_apple:

#388 Update to Core beta.23
  .circleci/config.yml
  .depsvalidator.yml
  Apps/Apps.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Apps/Examples/Examples/All Examples/OfflineManagerExample.swift
  Apps/Examples/Examples/All Examples/OfflineRegionManagerExample.swift
  CHANGELOG.md
  Cartfile
  Cartfile.resolved
  DEVELOPING.md
  Makefile
  Mapbox/MapboxMaps.xcodeproj/project.pbxproj
  Mapbox/MapboxMaps.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  MapboxMaps.podspec
  MapboxMaps.xcworkspace/contents.xcworkspacedata
  MapboxMaps.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  MapboxMaps.xcworkspace/xcshareddata/WorkspaceSettings.xcsettings
  MapboxMaps.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Package.resolved
  Package.swift
  Sources/MapboxMaps/Annotations/AnnotationManager_Legacy.swift
  Sources/MapboxMaps/Foundation/CameraManagerProtocol.swift
  Sources/MapboxMaps/Foundation/Extensions/Core/HttpResponse.swift
  Sources/MapboxMaps/Foundation/Extensions/Core/MBXGeometry.swift
  Sources/MapboxMaps/Foundation/Extensions/Turf/Feature.swift
  Sources/MapboxMaps/Foundation/Extensions/Turf/Geometry.swift
  Sources/MapboxMaps/Foundation/MapFeatureQueryable.swift
  Sources/MapboxMaps/Foundation/MapboxMap.swift
  Sources/MapboxMaps/Offline/OfflineCallbacks.swift
  Sources/MapboxMaps/Offline/OfflineManager+MapboxMaps.swift
  Sources/MapboxMaps/Offline/TileRegionLoadOptions+MapboxMaps.swift
  Sources/MapboxMaps/Offline/TileStore+MapboxMaps.swift
  Sources/MapboxMaps/Snapshot/Snapshotter.swift
  Sources/MapboxMaps/Style/Style.swift
  Sources/MapboxMaps/Style/StyleManagerProtocol.swift
  Sources/MapboxMaps/Style/Types/ExpressionArgumentBuilder.swift
  Sources/MapboxMaps/Style/Types/GeoJSONSourceData.swift
  Tests/MapboxMapsTests/Annotations/MockMapFeatureQueryable.swift
  Tests/MapboxMapsTests/Foundation/GeoJSON/GeoJSONManagerTests.swift
  Tests/MapboxMapsTests/Foundation/GeoJSON/Geometry+MBXGeometryTests.swift
  Tests/MapboxMapsTests/Foundation/GeoJSON/GeometryCollectionTests.swift
  Tests/MapboxMapsTests/Foundation/GeoJSON/PointTests.swift
  Tests/MapboxMapsTests/MapView/Integration Tests/FeatureQueryingTest.swift
  Tests/MapboxMapsTests/MapView/Integration Tests/HTTP/HTTPIntegrationTests.swift
  Tests/MapboxMapsTests/MapView/Integration Tests/Map/MapViewIntegrationTests.swift
  Tests/MapboxMapsTests/MapView/Integration Tests/OfflineManagerIntegrationTests.swift
  Tests/MapboxMapsTests/MigrationGuide/MigrationGuideIntegrationTests.swift
  Tests/MapboxMapsTests/MigrationGuide/OfflineGuideIntegrationTests.swift
  scripts/binary-size/binary-sizes.csv
  scripts/binary-size/measure-binary-size.rb
  scripts/release/packager/versions.json
  xcode-12.xcconfig
Labels: breaking change :warning:

#372 Make testMapCanBeLoadedWithoutNetworkConnectivity concurrent
  Tests/MapboxMapsTests/MapView/Integration Tests/OfflineManagerIntegrationTests.swift
Labels: skip changelog, testing :100:

#374 Make __map private
  .circleci/config.yml
  CHANGELOG.md
  Makefile
  Mapbox/MapboxMaps.xcodeproj/project.pbxproj
  Sources/MapboxMaps/Foundation/Camera/CameraAnimationsManager.swift
  Sources/MapboxMaps/Foundation/CameraManagerProtocol.swift
  Sources/MapboxMaps/Foundation/Extensions/Core/MapEvents.swift
  Sources/MapboxMaps/Foundation/MapView.swift
  Sources/MapboxMaps/Foundation/MapboxMap.swift
  Sources/MapboxMaps/Gestures/GestureManager+GestureHandlerDelegate.swift
  Sources/MapboxMaps/Location/LocationSupportableMapView.swift
  Sources/MapboxMaps/MapView/Configuration/RenderOptions.swift
  Sources/MapboxMaps/MapView/MapView+Supportable.swift
  Sources/MapboxMaps/Offline/OfflineCallbacks.swift
  Sources/MapboxMaps/Style/Generated/Sources/GeojsonSource.swift
  Sources/MapboxMaps/Style/StyleEncodable.swift
  Sources/MapboxMaps/Style/StyleErrors.swift
  Tests/MapboxMapsTests/Foundation/MapboxMapTests.swift
  Tests/MapboxMapsTests/Location/LocationSupportableMapViewMock.swift
  Tests/MapboxMapsTests/MapView/Integration Tests/Map/DidIdleFailureIntegrationTest.swift
  Tests/MapboxMapsTests/MapView/Integration Tests/Map/MapInitOptionsIntegrationTests.swift
  Tests/MapboxMapsTests/MapView/Integration Tests/Map/ObservableIntegrationTests.swift
Labels: breaking change :warning:

#390 Add internal map delegates, create platform Projection class
  CHANGELOG.md
  Mapbox/MapboxMaps.xcodeproj/project.pbxproj
  Package.resolved
  Sources/MapboxMaps/Foundation/Camera/FlyToInterpolator.swift
  Sources/MapboxMaps/Foundation/MapProjectionDelegate.swift
  Sources/MapboxMaps/Foundation/MapTransformDelegate.swift
  Sources/MapboxMaps/Foundation/MapboxMap.swift
  Sources/MapboxMaps/MapView/MapView+Supportable.swift
  Sources/MapboxMaps/Offline/TileStore+MapboxMaps.swift
  Sources/MapboxMaps/Ornaments/OrnamentsManager.swift
  Tests/MapboxMapsTests/Foundation/MapboxMapTests.swift
  Tests/MapboxMapsTests/Foundation/Projection/ProjectionTests.swift
Labels: breaking change :warning:

#393 Update example for projection changes
  Apps/Examples/Examples/All Examples/SceneKitExample.swift
Labels: skip changelog

#394 Fix doc generation
  scripts/doc-generation/generate-docs.sh
Labels: skip changelog

#395 Add destroyRenderer to MapboxMap deinit
  CHANGELOG.md
  Sources/MapboxMaps/Foundation/MapView.swift
  Sources/MapboxMaps/Foundation/MapboxMap.swift
Labels: bug :beetle:

#396 Introduce ResourceOptionsManager
  .circleci/config.yml
  .swiftpm/xcode/xcshareddata/xcschemes/MapboxMaps.xcscheme
  Apps/Examples/Examples/Models/ExampleProtocol.swift
  CHANGELOG.md
  Mapbox/MapboxMaps.xcodeproj/project.pbxproj
  Sources/MapboxMaps/Foundation/CredentialsManager.swift
  Sources/MapboxMaps/Foundation/Extensions/Core/CacheManager.swift
  Sources/MapboxMaps/Foundation/Extensions/Core/MapSnapshotOptions.swift
  Sources/MapboxMaps/Foundation/Extensions/Core/OfflineRegionManager.swift
  Sources/MapboxMaps/Foundation/Extensions/Core/ResourceOptions.swift
  Sources/MapboxMaps/Foundation/Extensions/Int.swift
  Sources/MapboxMaps/Foundation/MapProjectionDelegate.swift
  Sources/MapboxMaps/Foundation/MapView.swift
  Sources/MapboxMaps/Foundation/MapboxMap.swift
  Sources/MapboxMaps/Foundation/ResourceOptionsManager.swift
  Sources/MapboxMaps/MapView/Configuration/MapInitOptions.swift
  Sources/MapboxMaps/Offline/OfflineManager+MapboxMaps.swift
  Sources/MapboxMaps/Style/Style.swift
  Tests/MapboxMapsTests/Foundation/CredentialsManagerTests.swift
  Tests/MapboxMapsTests/Foundation/Extensions/Core/ResourceOptionsTests.swift
  Tests/MapboxMapsTests/Foundation/Glyphs/GlyphsRasterizationOptionsTests.swift
  Tests/MapboxMapsTests/Foundation/Projection/ProjectionTests.swift
  Tests/MapboxMapsTests/Foundation/ResourceOptionsManagerTests.swift
  Tests/MapboxMapsTests/Gestures/GestureManagerTests.swift
  Tests/MapboxMapsTests/Helpers/XCTestCase+MapboxAccessToken.swift
  Tests/MapboxMapsTests/MapView/Integration Tests/CacheManager/CacheManagerIntegrationTests.swift
  Tests/MapboxMapsTests/MapView/Integration Tests/IntegrationTestCase.swift
  Tests/MapboxMapsTests/MapView/Integration Tests/Map/DidIdleFailureIntegrationTest.swift
  Tests/MapboxMapsTests/MapView/Integration Tests/Map/MapInitOptionsIntegrationTests.swift
  Tests/MapboxMapsTests/MapView/Integration Tests/Map/MapViewIntegrationTests.swift
  Tests/MapboxMapsTests/MapView/Integration Tests/Map/MapboxMapIntegrationTests.swift
  Tests/MapboxMapsTests/MapView/Integration Tests/MapViewIntegrationTestCase.swift
  Tests/MapboxMapsTests/MapView/Integration Tests/OfflineManagerIntegrationTests.swift
  Tests/MapboxMapsTests/MapView/Unit Tests/MapInitOptionsTests.swift
  Tests/MapboxMapsTests/MigrationGuide/MigrationGuideIntegrationTests.swift
  Tests/MapboxMapsTests/MigrationGuide/OfflineGuideIntegrationTests.swift
  Tests/MapboxMapsTests/Offline/TileStore+Tests.swift
  Tests/MapboxMapsTests/Snapshot/MapboxMapsSnapshotTests.swift
Labels: breaking change :warning:

#404 Fix aggressive teardowns
  Tests/MapboxMapsTests/MapView/Integration Tests/HTTP/HTTPIntegrationTests.swift
  Tests/MapboxMapsTests/MapView/Integration Tests/IntegrationTestCase.swift
  Tests/MapboxMapsTests/MapView/Integration Tests/Map/MapViewIntegrationTests.swift
  Tests/MapboxMapsTests/MapView/Integration Tests/OfflineManagerIntegrationTests.swift
  baselines/binary-size/MapboxMaps.json
Labels: skip changelog, testing :100:

#406 Remove ResourceOptionsManager.reset
  Sources/MapboxMaps/Foundation/ResourceOptionsManager.swift
  Tests/MapboxMapsTests/Foundation/ResourceOptionsManagerTests.swift
Labels: skip changelog

#405 Re-enable snapshot tests
  Tests/MapboxMapsTests/Snapshot/MapboxMapsSnapshotTests.swift
Labels: skip changelog, testing :100:

#401 Make GestureManager.delegate public
  Sources/MapboxMaps/Gestures/GestureManager.swift
Labels: bug :beetle:

#402 [tests] Add tests for tapping the compass view, updating the bearing
  Tests/MapboxMapsTests/Ornaments/Compass/CompassDirectionFormatterTests.swift
  Tests/MapboxMapsTests/Ornaments/Compass/CompassMapViewIntegrationTests.swift
  Tests/MapboxMapsTests/Ornaments/Compass/MapboxCompassOrnamentViewTests.swift
Labels: testing :100:
