Repository mapbox/mapbox-maps-ios, pull requests merged in 2021-03, with the labels that each got.

#152 Update MapboxCoreMaps and MapboxCommon
  .swiftpm/xcode/xcshareddata/xcschemes/MapboxMaps.xcscheme
  Cartfile
  Cartfile.resolved
  Examples/Examples/All Examples/SwiftUIExample.swift
  MapboxMaps.podspec
  Package.resolved
  Package.swift
  Sources/MapboxMaps/Annotations/AnnotationManager.swift
  Sources/MapboxMaps/Foundation/BaseMapView.swift
  Sources/MapboxMaps/Foundation/Events/Event.swift
  Sources/MapboxMaps/Foundation/Events/EventsManager.swift
  Sources/MapboxMaps/Foundation/Events/EventsStringTokens.swift
  Sources/MapboxMaps/Foundation/Extensions/Core/MapEvents.swift
  Sources/MapboxMaps/MapView/MapView+Supportable.swift
  Sources/MapboxMaps/MapView/MapView.swift
  Tests/MapboxMapsTests/MapView/Integration Tests/Map/MapViewIntegrationTests.swift
Labels: breaking change :warning:

#153 Update Core and Common in packager
  scripts/release/packager/versions.json
Labels: skip changelog

#151 Add crash symbolication
  .circleci/config.yml
  .gitignore
  Makefile
  scripts/xcparty/Package.resolved
  scripts/xcparty/Package.swift
  scripts/xcparty/README.md
  scripts/xcparty/Sources/xcparty/main.swift
Labels: skip changelog

#148 [build] CI Script Fixes
  .circleci/config.yml
  scripts/release/create-github-draft-release.sh
  scripts/release/update-dependency-manager-manifests.sh
Labels: skip changelog

#159 Update point annotation example
  Examples/Examples/All Examples/PointAnnotationExample.swift
  Examples/Examples/Models/Examples.swift
Labels: skip changelog

#160 Update the layer below example
  Examples/Examples/All Examples/LayerBelowExample.swift
Labels: skip changelog

#158 Ensure Examples' finish is called only once.
  Examples/Examples/Models/Examples.swift
Labels: skip changelog, testing :100:

#168 Refactor StyleURL to conform to RawRepresentable
  Mapbox/MapboxMaps.xcodeproj/project.pbxproj
  Sources/MapboxMaps/Style/MapboxStyleURL.swift
  Sources/MapboxMaps/Style/StyleURL.swift
  Tests/MapboxMapsTests/Style/StyleURLTests.swift
Labels: breaking change :warning:

#167 [build] Static automation support
  .circleci/config.yml
  scripts/release/create-api-downloads-pr.sh
  scripts/release/create-github-draft-release.sh
  scripts/release/packager/create-xcframework.sh
  scripts/release/packager/package-mapbox-maps.sh
  scripts/release/upload-to-registry.sh
Labels: skip changelog

#157 Add custom PreferredFPS option
  Sources/MapboxMaps/Foundation/BaseMapView.swift
  Tests/MapboxMapsTests/MapView/Integration Tests/Map/MapViewIntegrationTests.swift
Labels: feature :green_apple:

#170 [tests] Generate source integration tests
  Mapbox/MapboxMaps.xcodeproj/project.pbxproj
  Tests/MapboxMapsTests/Style/Fixtures/Fixtures.swift
  Tests/MapboxMapsTests/Style/Fixtures/SouceProperties+Fixtures.swift
  Tests/MapboxMapsTests/Style/Generated/IntegrationTests/Sources/GeoJsonSourceIntegrationTests.swift
  Tests/MapboxMapsTests/Style/Generated/IntegrationTests/Sources/ImageSourceIntegrationTests.swift
  Tests/MapboxMapsTests/Style/Generated/IntegrationTests/Sources/RasterDemSourceIntegrationTests.swift
  Tests/MapboxMapsTests/Style/Generated/IntegrationTests/Sources/RasterSourceIntegrationTests.swift
  Tests/MapboxMapsTests/Style/Generated/IntegrationTests/Sources/VectorSourceIntegrationTests.swift
  Tests/MapboxMapsTests/Style/MapboxMapsStyleTests.swift
Labels: skip changelog

#175 Circle CI Config Cleanup
  .circleci/config.yml
  .github/stale.yml
  .swiftlint.yml
  .yamllint
  Makefile
  MapboxMaps-Info.plist
  Sources/.swiftlint.yml
  Tests/.swiftlint.yml
  WorkspaceSettings.xcsettings
  codecov.yml
  scripts/device-farm/testspec.yml
  scripts/release/packager/project.yml
Labels: skip changelog

#177 Additional CI Config Cleanup
  .circleci/config.yml
  Dangerfile.swift
  Makefile
Labels: skip changelog

#179 Migrate DebugApp to SPM
  .circleci/config.yml
  Apps/Apps.xcworkspace/contents.xcworkspacedata
  Apps/Apps.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  Apps/Apps.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Apps/DebugApp/Configurations/base.xcconfig
  Apps/DebugApp/Configurations/unitTests.xcconfig
  Apps/DebugApp/DebugApp.xcodeproj/project.pbxproj
  Apps/DebugApp/DebugApp.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  Apps/DebugApp/DebugApp.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  Apps/DebugApp/DebugApp.xcodeproj/xcshareddata/xcschemes/DebugApp.xcscheme
  Apps/DebugApp/DebugApp/AppDelegate.swift
  Apps/DebugApp/DebugApp/Assets.xcassets/AppIcon.appiconset/Contents.json
  Apps/DebugApp/DebugApp/Assets.xcassets/Contents.json
  Apps/DebugApp/DebugApp/Assets.xcassets/star.imageset/Contents.json
  Apps/DebugApp/DebugApp/Assets.xcassets/star.imageset/star.pdf
  Apps/DebugApp/DebugApp/Assets.xcassets/triangle.imageset/Contents.json
  Apps/DebugApp/DebugApp/Assets.xcassets/triangle.imageset/triangle.pdf
  Apps/DebugApp/DebugApp/Base.lproj/LaunchScreen.storyboard
  Apps/DebugApp/DebugApp/Base.lproj/Main.storyboard
  Apps/DebugApp/DebugApp/DebugViewController.swift
  Apps/DebugApp/DebugApp/Info.plist
  Apps/DebugApp/DebugApp/MainViewController.swift
  Apps/DebugApp/DebugApp/third_party_vector_style.json
  Apps/DebugApp/DebugAppTests/ApplicationTestCase.swift
  Apps/DebugApp/DebugAppTests/DebugAppTests.swift
  Apps/DebugApp/DebugAppTests/Info.plist
  Apps/DebugApp/DebugAppUITests/DebugAppUITests.swift
  Apps/DebugApp/DebugAppUITests/Info.plist
  DEVELOPING.md
  Makefile
  MapboxMaps.xcworkspace/contents.xcworkspacedata
  codecov.yml
Labels: skip changelog

#181 Use Xcode 12.4 CI image for swiftlint job
  .circleci/config.yml
  Tests/.swiftlint.yml
Labels: skip changelog

#183 Build and test with SPM
  .circleci/config.yml
  .swiftpm/xcode/xcshareddata/xcschemes/MapboxMaps.xcscheme
  Makefile
Labels: skip changelog

#185 [bugfix] Make all layer layout and paint properties a Value type
  Examples/Examples/All Examples/AnimateGeoJSONLineExample.swift
  Examples/Examples/All Examples/AnimateLayerExample.swift
  Examples/Examples/All Examples/ExternalVectorSourceExample.swift
  Examples/Examples/All Examples/LineGradientExample.swift
  Examples/Examples/All Examples/ModelExample.swift
  Examples/Examples/All Examples/TerrainExample.swift
  Sources/MapboxMaps/Style/Generated/Layers/BackgroundLayer.swift
  Sources/MapboxMaps/Style/Generated/Layers/CircleLayer.swift
  Sources/MapboxMaps/Style/Generated/Layers/FillExtrusionLayer.swift
  Sources/MapboxMaps/Style/Generated/Layers/FillLayer.swift
  Sources/MapboxMaps/Style/Generated/Layers/HeatmapLayer.swift
  Sources/MapboxMaps/Style/Generated/Layers/HillshadeLayer.swift
  Sources/MapboxMaps/Style/Generated/Layers/LineLayer.swift
  Sources/MapboxMaps/Style/Generated/Layers/LocationIndicatorLayer.swift
  Sources/MapboxMaps/Style/Generated/Layers/ModelLayer.swift
  Sources/MapboxMaps/Style/Generated/Layers/RasterLayer.swift
  Sources/MapboxMaps/Style/Generated/Layers/SkyLayer.swift
  Sources/MapboxMaps/Style/Generated/Layers/SymbolLayer.swift
  Tests/MapboxMapsTests/Style/Fixtures/Enums+Fixtures.swift
  Tests/MapboxMapsTests/Style/Fixtures/Value+Fixtures.swift
  Tests/MapboxMapsTests/Style/Generated/IntegrationTests/Layers/BackgroundLayerIntegrationTests.swift
  Tests/MapboxMapsTests/Style/Generated/IntegrationTests/Layers/CircleLayerIntegrationTests.swift
  Tests/MapboxMapsTests/Style/Generated/IntegrationTests/Layers/FillExtrusionLayerIntegrationTests.swift
  Tests/MapboxMapsTests/Style/Generated/IntegrationTests/Layers/FillLayerIntegrationTests.swift
  Tests/MapboxMapsTests/Style/Generated/IntegrationTests/Layers/HeatmapLayerIntegrationTests.swift
  Tests/MapboxMapsTests/Style/Generated/IntegrationTests/Layers/HillshadeLayerIntegrationTests.swift
  Tests/MapboxMapsTests/Style/Generated/IntegrationTests/Layers/LineLayerIntegrationTests.swift
  Tests/MapboxMapsTests/Style/Generated/IntegrationTests/Layers/LocationIndicatorLayerIntegrationTests.swift
  Tests/MapboxMapsTests/Style/Generated/IntegrationTests/Layers/ModelLayerIntegrationTests.swift
  Tests/MapboxMapsTests/Style/Generated/IntegrationTests/Layers/RasterLayerIntegrationTests.swift
  Tests/MapboxMapsTests/Style/Generated/IntegrationTests/Layers/SkyLayerIntegrationTests.swift
  Tests/MapboxMapsTests/Style/Generated/IntegrationTests/Layers/SymbolLayerIntegrationTests.swift
  Tests/MapboxMapsTests/Style/Generated/Layers/BackgroundLayerTests.swift
  Tests/MapboxMapsTests/Style/Generated/Layers/CircleLayerTests.swift
  Tests/MapboxMapsTests/Style/Generated/Layers/FillExtrusionLayerTests.swift
  Tests/MapboxMapsTests/Style/Generated/Layers/FillLayerTests.swift
  Tests/MapboxMapsTests/Style/Generated/Layers/HeatmapLayerTests.swift
  Tests/MapboxMapsTests/Style/Generated/Layers/HillshadeLayerTests.swift
  Tests/MapboxMapsTests/Style/Generated/Layers/LineLayerTests.swift
  Tests/MapboxMapsTests/Style/Generated/Layers/LocationIndicatorLayerTests.swift
  Tests/MapboxMapsTests/Style/Generated/Layers/ModelLayerTests.swift
  Tests/MapboxMapsTests/Style/Generated/Layers/RasterLayerTests.swift
  Tests/MapboxMapsTests/Style/Generated/Layers/SkyLayerTests.swift
  Tests/MapboxMapsTests/Style/Generated/Layers/SymbolLayerTests.swift
Labels: breaking change :warning:

#184 Migrate StressTest App to Apps Directory
  Apps/Apps.xcworkspace/contents.xcworkspacedata
  Apps/Configurations/base.xcconfig
  Apps/Configurations/unitTests.xcconfig
  Apps/DebugApp/DebugApp.xcodeproj/project.pbxproj
  Apps/StressTest/StressTest.xcodeproj/project.pbxproj
  Apps/StressTest/StressTest.xcodeproj/xcshareddata/xcschemes/StressTest.xcscheme
  Apps/StressTest/StressTest/AppDelegate.swift
  Apps/StressTest/StressTest/Assets.xcassets/AccentColor.colorset/Contents.json
  Apps/StressTest/StressTest/Assets.xcassets/AppIcon.appiconset/Contents.json
  Apps/StressTest/StressTest/Assets.xcassets/Contents.json
  Apps/StressTest/StressTest/Base.lproj/LaunchScreen.storyboard
  Apps/StressTest/StressTest/Base.lproj/Main.storyboard
  Apps/StressTest/StressTest/Info.plist
  Apps/StressTest/StressTest/SceneDelegate.swift
  Apps/StressTest/StressTest/ViewController.swift
  Apps/StressTest/StressTestTests/Info.plist
  Apps/StressTest/StressTestTests/StressTestTests.swift
  Apps/StressTest/StressTestUITests/Info.plist
  Apps/StressTest/StressTestUITests/StressTestUITests.swift
  Makefile
  MapboxMaps.xcworkspace/contents.xcworkspacedata
  codecov.yml
Labels: skip changelog

#189 Add layerId to AnnotationManager
  Mapbox/MapboxMaps.xcodeproj/project.pbxproj
  Sources/MapboxMaps/Annotations/AnnotationManager.swift
  Sources/MapboxMaps/Annotations/Configuration/AnnotationOptions.swift
  Sources/MapboxMaps/Foundation/Extensions/Core/LayerPosition.swift
  Sources/MapboxMaps/Foundation/Extensions/Core/ScreenCoordinate.swift
  Sources/MapboxMaps/MapView/Configuration/MapOptions.swift
  Sources/MapboxMaps/MapView/MapView+Managers.swift
  Sources/MapboxMaps/Style/Style.swift
  Tests/MapboxMapsTests/Annotations/AnnotationInteractionDelegateTests.swift
  Tests/MapboxMapsTests/Annotations/AnnotationManagerTests.swift
  Tests/MapboxMapsTests/Foundation/Extensions/Core/LayerPositionTests.swift
  Tests/MapboxMapsTests/MapView/Integration Tests/AnnotationManagerIntegrationTests.swift
  Tests/MapboxMapsTests/Style/StyleIntegrationTests.swift
Labels: feature :green_apple:

#194 Make model layer internal and refactor for increased public API clarity
  Apps/Examples/Examples.xcodeproj/project.pbxproj
  Apps/Examples/Examples/All Examples/Custom2DPuckExample.swift
  Apps/Examples/Examples/All Examples/Custom3DPuckExample.swift
  Apps/Examples/Examples/All Examples/ModelExample.swift
  Apps/Examples/Examples/All Examples/TrackingModeExample.swift
  Apps/Examples/Examples/Models/Examples.swift
  Sources/MapboxMaps/Location/LocationConsumer.swift
  Sources/MapboxMaps/Location/LocationManager.swift
  Sources/MapboxMaps/Location/LocationOptions.swift
  Sources/MapboxMaps/Location/Pucks/LocationPuckManager.swift
  Sources/MapboxMaps/Location/Pucks/Puck.swift
  Sources/MapboxMaps/Location/Pucks/Puck2D.swift
  Sources/MapboxMaps/Location/Pucks/Puck3D.swift
  Sources/MapboxMaps/Style/ModelLayer.swift
  Tests/MapboxMapsTests/Location/LocationConsumerMock.swift
  Tests/MapboxMapsTests/Location/LocationManagerTests.swift
  Tests/MapboxMapsTests/Location/LocationPuckTests.swift
  Tests/MapboxMapsTests/Location/PuckTypeTests.swift
Labels: breaking change :warning:

#195 Fix file references in MapboxMaps Xcode project
  Mapbox/MapboxMaps.xcodeproj/project.pbxproj
Labels: skip changelog

#191 [Animations] Define Camera Animator
  Mapbox/MapboxMaps.xcodeproj/project.pbxproj
  Sources/MapboxMaps/Foundation/BaseMapView.swift
  Sources/MapboxMaps/Foundation/Camera/AnimationOwner.swift
  Sources/MapboxMaps/Foundation/Camera/CameraAnimationDelegate.swift
  Sources/MapboxMaps/Foundation/Camera/CameraAnimator.swift
  Sources/MapboxMaps/Foundation/Camera/CameraManager.swift
  Tests/MapboxMapsTests/Foundation/Camera/CameraAnimatorDelegateMock.swift
  Tests/MapboxMapsTests/Foundation/Camera/CameraAnimatorTests.swift
  Tests/MapboxMapsTests/Foundation/Camera/MapboxMapsCameraTests.swift
  Tests/MapboxMapsTests/Foundation/MapboxMapsFoundationTests.swift
  Tests/MapboxMapsTests/MapView/Integration Tests/Map/MapViewIntegrationTests.swift
Labels: feature :green_apple:

#198 Make ModelSource internal
  Sources/MapboxMaps/Style/ModelSource.swift
Labels: breaking change :warning:

#196 Update metrics triggers
  .circleci/config.yml
  MapboxMaps.podspec
  scripts/release/packager/versions.json
Labels: operations, skip changelog

#203 Merge LocationOptions.puckType & .showUserLocation
  Apps/DebugApp/DebugApp/DebugViewController.swift
  Apps/Examples/Examples/All Examples/Custom2DPuckExample.swift
  Apps/Examples/Examples/All Examples/Custom3DPuckExample.swift
  Apps/Examples/Examples/All Examples/TrackingModeExample.swift
  Sources/MapboxMaps/Location/LocationManager.swift
  Sources/MapboxMaps/Location/LocationOptions.swift
  Tests/MapboxMapsTests/Location/LocationManagerTests.swift
  Tests/MapboxMapsTests/Location/LocationOptionsTests.swift
  Tests/MapboxMapsTests/MapView/OptionsIntegrationTests.swift
Labels: breaking change :warning:

#199 Fix puck update issue
  Apps/DebugApp/DebugApp/DebugViewController.swift
  Apps/Examples/Examples/All Examples/Custom2DPuckExample.swift
  Apps/Examples/Examples/All Examples/Custom3DPuckExample.swift
  Apps/Examples/Examples/All Examples/TrackingModeExample.swift
  Sources/MapboxMaps/Location/LocationManager.swift
  Sources/MapboxMaps/Location/LocationOptions.swift
  Tests/MapboxMapsTests/Location/LocationManagerTests.swift
  Tests/MapboxMapsTests/Location/LocationOptionsTests.swift
  Tests/MapboxMapsTests/MapView/OptionsIntegrationTests.swift
Labels: bug :beetle:

#206 Fix xcparty invocation in CI config
  .circleci/config.yml
Labels: skip changelog

#209 Make LocationManager.locationOptions getter public
  Sources/MapboxMaps/Location/LocationManager.swift
  Tests/MapboxMapsTests/Location/LocationManagerTests.swift
Labels: feature :green_apple:

#212 Fix path for tee
  .circleci/config.yml
Labels: skip changelog

#215 [Animations] Update Documentation
  Sources/MapboxMaps/Foundation/Camera/CameraManager.swift
Labels: docs :scroll:

#219 Fix Puck3D Deinitialization
  .swiftpm/xcode/xcshareddata/xcschemes/MapboxMaps.xcscheme
  Sources/MapboxMaps/Location/Pucks/Puck3D.swift
  Tests/MapboxMapsTests/Helpers/XCTestCase+MapboxAccessToken.swift
  Tests/MapboxMapsTests/Location/Pucks/Puck3DIntegrationTests.swift
  Tests/MapboxMapsTests/MapView/Integration Tests/IntegrationTestCase.swift
Labels: skip changelog

#220 Delete old targets & schemes, fix tests with host
  Mapbox/MapboxMaps.xcodeproj/project.pbxproj
  Mapbox/MapboxMaps.xcodeproj/xcshareddata/xcschemes/All simulator tests.xcscheme
  Mapbox/MapboxMaps.xcodeproj/xcshareddata/xcschemes/MapboxMapsAnnotations.xcscheme
  Mapbox/MapboxMaps.xcodeproj/xcshareddata/xcschemes/MapboxMapsFoundation.xcscheme
  Mapbox/MapboxMaps.xcodeproj/xcshareddata/xcschemes/MapboxMapsGestures.xcscheme
  Mapbox/MapboxMaps.xcodeproj/xcshareddata/xcschemes/MapboxMapsLocation.xcscheme
  Mapbox/MapboxMaps.xcodeproj/xcshareddata/xcschemes/MapboxMapsOffline.xcscheme
  Mapbox/MapboxMaps.xcodeproj/xcshareddata/xcschemes/MapboxMapsOrnaments.xcscheme
  Mapbox/MapboxMaps.xcodeproj/xcshareddata/xcschemes/MapboxMapsSnapshot.xcscheme
  Mapbox/MapboxMaps.xcodeproj/xcshareddata/xcschemes/MapboxMapsStyle.xcscheme
Labels: skip changelog

#217 [Camera Animations v2] Rebuild Camera Animations to be directly powered by CoreAnimation
  Apps/DebugApp/DebugApp/DebugViewController.swift
  Apps/Examples/Examples.xcodeproj/project.pbxproj
  Apps/Examples/Examples/All Examples/CameraAnimatorsExample.swift
  Apps/Examples/Examples/All Examples/CameraUIViewAnimationExample.swift
  Apps/Examples/Examples/All Examples/CustomPointAnnotationExample.swift
  Apps/Examples/Examples/All Examples/FlyToExample.swift
  Apps/Examples/Examples/All Examples/GeoJSONSourceExample.swift
  Apps/Examples/Examples/All Examples/PointAnnotationExample.swift
  Apps/Examples/Examples/All Examples/SceneKitExample.swift
  Apps/Examples/Examples/All Examples/SelectAnnotationExample.swift
  Apps/Examples/Examples/All Examples/SnapshotterExample.swift
  Apps/Examples/Examples/Models/Examples.swift
  Cartfile.resolved
  Mapbox/MapboxMaps.xcodeproj/project.pbxproj
  Sources/MapboxMaps/Foundation/BaseMapView.swift
  Sources/MapboxMaps/Foundation/Camera/AnimationOwner.swift
  Sources/MapboxMaps/Foundation/Camera/CameraAnimationDelegate.swift
  Sources/MapboxMaps/Foundation/Camera/CameraAnimator.swift
  Sources/MapboxMaps/Foundation/Camera/CameraLayer.swift
  Sources/MapboxMaps/Foundation/Camera/CameraManager+CameraAnimatorDelegate.swift
  Sources/MapboxMaps/Foundation/Camera/CameraManager.swift
  Sources/MapboxMaps/Foundation/Camera/CameraView.swift
  Sources/MapboxMaps/Foundation/Camera/FlyToInterpolator.swift
  Sources/MapboxMaps/Foundation/Extensions/Core/MBXEdgeInsets.swift
  Sources/MapboxMaps/Foundation/Extensions/CoreLocation.swift
  Sources/MapboxMaps/Gestures/GestureHandlerDelegate.swift
  Sources/MapboxMaps/Gestures/GestureHandlers/PanGestureHandler.swift
  Sources/MapboxMaps/Gestures/GestureHandlers/TapGestureHandler.swift
  Sources/MapboxMaps/Gestures/GestureManager+GestureHandlerDelegate.swift
  Sources/MapboxMaps/Gestures/GestureManager.swift
  Sources/MapboxMaps/MapView/Configuration/RenderOptions.swift
  Sources/MapboxMaps/MapView/MapView+Managers.swift
  Tests/MapboxMapsTests/Foundation/Camera/CameraAnimatorDelegateMock.swift
  Tests/MapboxMapsTests/Foundation/Camera/CameraAnimatorTests.swift
  Tests/MapboxMapsTests/Foundation/Camera/MapboxAnimationGroupTests.swift
  Tests/MapboxMapsTests/Foundation/Camera/MapboxMapsCameraTests.swift
  Tests/MapboxMapsTests/Foundation/MapboxMapsFoundationTests.swift
  Tests/MapboxMapsTests/Gestures/GestureSupportableViewMock.swift
  Tests/MapboxMapsTests/Gestures/MockCameraManager.swift
  Tests/MapboxMapsTests/MapView/Integration Tests/ExampleIntegrationTest.swift
  Tests/MapboxMapsTests/MapView/Integration Tests/Map/DidIdleFailureIntegrationTest.swift
  Tests/MapboxMapsTests/MapView/Integration Tests/Map/MapViewIntegrationTests.swift
  Tests/MapboxMapsTests/MapView/OptionsIntegrationTests.swift
Labels: feature :green_apple:

#223 Update changelog for CameraAnimators (#217)
  CHANGELOG.md
Labels: skip changelog

#224 Fixes Xcode workspace; restores Cartfile.resolved
  Cartfile.resolved
  Mapbox/MapboxMaps.xcodeproj/project.pbxproj
Labels: skip changelog

#227 [build] Update static download paths
  .circleci/config.yml
  scripts/release/create-api-downloads-pr.sh
  scripts/release/create-github-draft-release.sh
  scripts/release/packager/package-mapbox-maps.sh
  scripts/release/upload-to-registry.sh
Labels: skip changelog

#228 Sync dependency versions
  Cartfile
  MapboxMaps.podspec
  scripts/release/packager/versions.json
Labels: skip changelog

#232 Fixes for release CI
  scripts/release/create-api-downloads-pr.sh
  scripts/release/update-dependency-manager-manifests.sh
Labels: skip changelog

#226 Add test to check values are within range.
  Tests/MapboxMapsTests/Foundation/Camera/FlyToTests.swift
Labels: skip changelog

#235 Fix compilation failure with StressTest app
  Apps/StressTest/StressTest/ViewController.swift
Labels: skip changelog

#231 Make addLayer/addSource not generic.
  Sources/MapboxMaps/Annotations/AnnotationStyleDelegate.swift
  Sources/MapboxMaps/Style/Layers.swift
  Sources/MapboxMaps/Style/Sources.swift
  Sources/MapboxMaps/Style/Style.swift
  Sources/MapboxMaps/Style/StyleEncodable.swift
  Sources/MapboxMaps/Style/StyleErrors.swift
  Tests/MapboxMapsTests/Annotations/AnnotationStyleDelegateMock.swift
  Tests/MapboxMapsTests/MapView/Integration Tests/AnnotationManagerIntegrationTests.swift
Labels: skip changelog

#237 Rename StyleURL to StyleURI
  Apps/Examples/Examples/All Examples/BuildingExtrusionsExample.swift
  Apps/Examples/Examples/All Examples/CustomStyleURLExample.swift
  Apps/Examples/Examples/All Examples/DataDrivenSymbolsExample.swift
  Apps/Examples/Examples/All Examples/ExternalVectorSourceExample.swift
  Apps/Examples/Examples/All Examples/LineGradientExample.swift
  Apps/Examples/Examples/All Examples/MapViewExample.swift
  Apps/Examples/Examples/All Examples/OfflineRegionManagerExample.swift
  Apps/Examples/Examples/All Examples/SnapshotterCoreGraphicsExample.swift
  Apps/Examples/Examples/All Examples/SnapshotterExample.swift
  Apps/Examples/Examples/All Examples/SwiftUIExample.swift
  Apps/Examples/Examples/All Examples/TerrainExample.swift
  Apps/Examples/Examples/All Examples/TrackingModeExample.swift
  Apps/StressTest/StressTest/ViewController.swift
  Mapbox/MapboxMaps.xcodeproj/project.pbxproj
  Sources/MapboxMaps/Foundation/BaseMapView.swift
  Sources/MapboxMaps/MapView/MapView.swift
  Sources/MapboxMaps/Style/Style.swift
  Sources/MapboxMaps/Style/StyleURI.swift
  Tests/MapboxMapsTests/Foundation/Camera/MapboxMapsCameraTests.swift
  Tests/MapboxMapsTests/Foundation/MapboxMapsFoundationTests.swift
  Tests/MapboxMapsTests/Gestures/GestureManagerTests.swift
  Tests/MapboxMapsTests/MapView/Integration Tests/AnnotationManagerIntegrationTests.swift
  Tests/MapboxMapsTests/MapView/Integration Tests/ExampleIntegrationTest.swift
  Tests/MapboxMapsTests/MapView/Integration Tests/FeatureQueryingTest.swift
  Tests/MapboxMapsTests/MapView/Integration Tests/HTTP/HTTPIntegrationTests.swift
  Tests/MapboxMapsTests/MapView/Integration Tests/LocationManagerIntegrationTests.swift
  Tests/MapboxMapsTests/MapView/Integration Tests/Map/DidIdleFailureIntegrationTest.swift
  Tests/MapboxMapsTests/MapView/Integration Tests/Map/MapViewIntegrationTests.swift
  Tests/MapboxMapsTests/MapView/Integration Tests/Map/ObservableIntegrationTests.swift
  Tests/MapboxMapsTests/MapView/Integration Tests/Style/StyleLoadIntegrationTests.swift
  Tests/MapboxMapsTests/Style/Generated/IntegrationTests/Layers/BackgroundLayerIntegrationTests.swift
  Tests/MapboxMapsTests/Style/Generated/IntegrationTests/Layers/CircleLayerIntegrationTests.swift
  Tests/MapboxMapsTests/Style/Generated/IntegrationTests/Layers/FillExtrusionLayerIntegrationTests.swift
  Tests/MapboxMapsTests/Style/Generated/IntegrationTests/Layers/FillLayerIntegrationTests.swift
  Tests/MapboxMapsTests/Style/Generated/IntegrationTests/Layers/HeatmapLayerIntegrationTests.swift
  Tests/MapboxMapsTests/Style/Generated/IntegrationTests/Layers/HillshadeLayerIntegrationTests.swift
  Tests/MapboxMapsTests/Style/Generated/IntegrationTests/Layers/LineLayerIntegrationTests.swift
  Tests/MapboxMapsTests/Style/Generated/IntegrationTests/Layers/LocationIndicatorLayerIntegrationTests.swift
  Tests/MapboxMapsTests/Style/Generated/IntegrationTests/Layers/ModelLayerIntegrationTests.swift
  Tests/MapboxMapsTests/Style/Generated/IntegrationTests/Layers/RasterLayerIntegrationTests.swift
  Tests/MapboxMapsTests/Style/Generated/IntegrationTests/Layers/SkyLayerIntegrationTests.swift
  Tests/MapboxMapsTests/Style/Generated/IntegrationTests/Layers/SymbolLayerIntegrationTests.swift
  Tests/MapboxMapsTests/Style/Generated/IntegrationTests/Sources/GeoJsonSourceIntegrationTests.swift
  Tests/MapboxMapsTests/Style/Generated/IntegrationTests/Sources/ImageSourceIntegrationTests.swift
  Tests/MapboxMapsTests/Style/Generated/IntegrationTests/Sources/RasterDemSourceIntegrationTests.swift
  Tests/MapboxMapsTests/Style/Generated/IntegrationTests/Sources/RasterSourceIntegrationTests.swift
  Tests/MapboxMapsTests/Style/Generated/IntegrationTests/Sources/VectorSourceIntegrationTests.swift
  Tests/MapboxMapsTests/Style/StyleIntegrationTests.swift
  Tests/MapboxMapsTests/Style/StyleURITests.swift
  Tests/MapboxMapsTests/Style/StyleURLTests.swift
Labels: breaking change :warning:

#241 Create non-generic versions of getLayer/getSource
  Sources/MapboxMaps/Style/Layers.swift
  Sources/MapboxMaps/Style/Sources.swift
  Sources/MapboxMaps/Style/Style.swift
  Sources/MapboxMaps/Style/StyleEncodable.swift
Labels: skip changelog

#243 Bumped binary-size baselines
  baselines/binary-size/MapboxMaps.json
Labels: skip changelog
