Repository mapbox/mapbox-maps-ios, pull requests merged in 2022-11, with the labels that each got.

#1659 Support `isDraggable` and `isSelected` for annotations
  Apps/Examples/Examples/All Examples/Annotations/CircleAnnotationExample.swift
  Apps/Examples/Examples/All Examples/Annotations/CustomPointAnnotationExample.swift
  Apps/Examples/Examples/All Examples/Annotations/PolygonAnnotationExample.swift
  CHANGELOG.md
  Sources/MapboxMaps/Annotations/AnnotationOrchestrator.swift
  Sources/MapboxMaps/Annotations/AnnotationOrchestratorImpl.swift
  Sources/MapboxMaps/Annotations/Generated/CircleAnnotation.swift
  Sources/MapboxMaps/Annotations/Generated/CircleAnnotationManager.swift
  Sources/MapboxMaps/Annotations/Generated/PointAnnotation.swift
  Sources/MapboxMaps/Annotations/Generated/PointAnnotationManager.swift
  Sources/MapboxMaps/Annotations/Generated/PolygonAnnotation.swift
  Sources/MapboxMaps/Annotations/Generated/PolygonAnnotationManager.swift
  Sources/MapboxMaps/Annotations/Generated/PolylineAnnotation.swift
  Sources/MapboxMaps/Annotations/Generated/PolylineAnnotationManager.swift
  Sources/MapboxMaps/Annotations/OffsetGeometryCalculator.swift
  Sources/MapboxMaps/Foundation/MapView.swift
  Sources/MapboxMaps/Foundation/MapViewDependencyProvider.swift
  Sources/MapboxMaps/Foundation/MapboxMap.swift
  Sources/MapboxMaps/Foundation/Projection.swift
  Sources/MapboxMaps/Gestures/GestureRecognizers/MapboxLongPressGestureRecognizer.swift
  Sources/MapboxMaps/Style/Style.swift
  Tests/MapboxMapsTests/Annotations/Generated/CircleAnnotationManagerTests.swift
  Tests/MapboxMapsTests/Annotations/Generated/PointAnnotationManagerTests.swift
  Tests/MapboxMapsTests/Annotations/Generated/PolygonAnnotationManagerTests.swift
  Tests/MapboxMapsTests/Annotations/Generated/PolylineAnnotationManagerTests.swift
  Tests/MapboxMapsTests/Annotations/Mocks/MockAnnotationOrchestatorImpl.swift
  Tests/MapboxMapsTests/Foundation/Mocks/MockMapViewDependencyProvider.swift
  Tests/MapboxMapsTests/Foundation/Mocks/MockMapboxMap.swift
  Tests/MapboxMapsTests/Helpers/XCTestCase+ImageComparison.swift
  Tests/MapboxMapsTests/Style/Mocks/MockStyle.swift
Labels: feature :green_apple:

#1694 Add sky layer deprecation docs
  Sources/MapboxMaps/Style/Generated/Layers/SkyLayer.swift
Labels: skip changelog

#1749 Fixes incorrect conversion from MapboxMaps.ResourceOptions to MapboxCoreMaps.ResourceOptions
  CHANGELOG.md
  Sources/MapboxMaps/Foundation/Extensions/Core/ResourceOptions.swift
  Tests/MapboxMapsTests/Foundation/Extensions/Core/ResourceOptionsTests.swift
Labels: bug :beetle:
