Repository mapbox/mapbox-maps-ios, pull requests merged in 2022-01, with the labels that each got.

#974 Examples bug fixes
  .swiftpm/xcode/xcshareddata/xcschemes/MapboxMaps.xcscheme
  Apps/DebugApp/DebugApp.xcodeproj/project.pbxproj
  Apps/DebugApp/DebugApp.xcodeproj/xcshareddata/xcschemes/DebugApp.xcscheme
  Apps/Examples/Examples.xcodeproj/xcshareddata/xcschemes/Examples.xcscheme
  Apps/Examples/Examples/All Examples/ShowHideLayerExample.swift
  Apps/StressTest/StressTest.xcodeproj/xcshareddata/xcschemes/StressTest.xcscheme
  scripts/insert_access_token.sh
Labels: skip changelog

#989 Set location for 2D puck when accuracy is reduced
  CHANGELOG.md
  Sources/MapboxMaps/Location/Puck/Puck2D.swift
  Tests/MapboxMapsTests/Location/Puck/Puck2DTests.swift
Labels: bug :beetle:

#992 Fix bug with setting options on LocationManager
  CHANGELOG.md
  Sources/MapboxMaps/Location/LocationManager.swift
  Tests/MapboxMapsTests/Location/LocationManagerTests.swift
  Tests/MapboxMapsTests/Location/Mocks/MockLocationProducer.swift
  Tests/MapboxMapsTests/Location/Mocks/MockLocationProvider.swift
Labels: bug :beetle:

#975 Deprecated function queryFeatureExtension
  Sources/MapboxMaps/Foundation/MapFeatureQueryable.swift
  Sources/MapboxMaps/Foundation/MapboxMap.swift
Labels: feature :green_apple:

#914 Integrate firebase into CI for examples
  .circleci/config.yml
  Apps/.fastlane/Fastfile
  Apps/.fastlane/Matchfile
  Apps/.fastlane/Pluginfile
  Apps/Examples/Examples.xcodeproj/project.pbxproj
  Apps/Examples/Examples/Info.plist
  Apps/Gemfile
  Apps/Gemfile.lock
  Makefile
  fastlane/Appfile
  fastlane/Fastfile
  fastlane/Matchfile
  fastlane/README.md
Labels: skip changelog

#1028 Upload Examples to TFA with API Keys
  .circleci/config.yml
  .fastlane/Appfile
  .fastlane/Fastfile
  .fastlane/Matchfile
  .fastlane/Pluginfile
  Apps/Examples/Examples.xcodeproj/project.pbxproj
  Gemfile
  Gemfile.lock
Labels: operations

#980 Add extension function to show or hide bearing image
  Apps/Examples/Examples/All Examples/Custom2DPuckExample.swift
  Apps/Examples/Examples/All Examples/TrackingModeExample.swift
  CHANGELOG.md
  Sources/MapboxMaps/Location/Puck/Puck2D.swift
  Tests/MapboxMapsTests/Location/Puck/Puck2DTests.swift
Labels: feature :green_apple:

#1058 Improve support for custom viewport gestures
  CHANGELOG.md
  Sources/MapboxMaps/Camera/CameraAnimationsManager.swift
  Sources/MapboxMaps/Foundation/MapView.swift
  Sources/MapboxMaps/Foundation/MapViewDependencyProvider.swift
  Sources/MapboxMaps/Foundation/TimerProtocol.swift
  Sources/MapboxMaps/Gestures/GestureHandlers/AnyTouchGestureHandler.swift
  Sources/MapboxMaps/Gestures/GestureManager.swift
  Sources/MapboxMaps/Gestures/GestureRecognizers/AnyTouchGestureRecognizer.swift
  Sources/MapboxMaps/Viewport/ViewportImpl.swift
  Tests/MapboxMapsTests/Foundation/Mocks/MockMapViewDependencyProvider.swift
  Tests/MapboxMapsTests/Foundation/Mocks/MockTimer.swift
  Tests/MapboxMapsTests/Gestures/GestureHandlers/AnyTouchGestureHandlerTests.swift
  Tests/MapboxMapsTests/Gestures/GestureManagerTests.swift
  Tests/MapboxMapsTests/Gestures/GestureOptionsTests.swift
  Tests/MapboxMapsTests/Gestures/GestureRecognizers/AnyTouchGestureRecognizerTests.swift
  Tests/MapboxMapsTests/Viewport/ViewportImplTests.swift
Labels: skip changelog

#1062 MapView cleanup
  Sources/MapboxMaps/Foundation/MapView.swift
Labels: skip changelog

#1064 Make generated bearing image square
  Sources/MapboxMaps/Location/Puck/Puck2D.swift
Labels: skip changelog

#1065 End AnyTouchGestureRecognizer in .changed state
  Sources/MapboxMaps/Foundation/MapViewDependencyProvider.swift
  Sources/MapboxMaps/Gestures/GestureRecognizers/AnyTouchGestureRecognizer.swift
  Tests/MapboxMapsTests/Gestures/GestureRecognizers/AnyTouchGestureRecognizerTests.swift
Labels: skip changelog

#1057 Add support for accuracy ring color
  Apps/Examples/Examples/All Examples/Custom2DPuckExample.swift
  CHANGELOG.md
  Sources/MapboxMaps/Location/Puck/Puck2D.swift
  Sources/MapboxMaps/Location/Puck/PuckType.swift
  Tests/MapboxMapsTests/Helpers/Random/UIColor+Random.swift
  Tests/MapboxMapsTests/Location/Puck/Puck2DTests.swift
  Tests/MapboxMapsTests/Location/Puck/PuckTypeTests.swift
Labels: feature :green_apple:
